### ISSUE TITLE
Purchased email notification options?

### ISSUE THREAD

**Issue by antcase** [itchio/itch.io#10]
Would be nice if we had a few options for the email notification when somebody buys your game. So for example, turn them off completely or instead receive a weekly, bi-weekly, or monthly roundup of sales.

**Comment by leafo** [comment]
BTW, since this issue was created, notifications for purchases are now grouped together in our standard notification system, so you only get digest emails. Going to close this, feel free to open if you'd like to see something specific added.

**Comment by tophycrisp** [comment]
> BTW, since this issue was created, notifications for purchases are now grouped together in our standard notification system, so you only get digest emails. Going to close this, feel free to open if you'd like to see something specific added.

Hi @leafo 

Is there a way to receive individual emails for purchases again, plus the buyers' email addresses so that a thank you email can be sent to them automatically via RPA services?
