### ISSUE TITLE
Hosting a game jam - Ranking criteria typo

### ISSUE THREAD

**Issue by hsandt** [itchio/itch.io#1001]
https://itch.io/docs/creators/game-jams#jam-customization/ranking-criteria/primary-criteria

> When you provide a primary critiera

should be

> When you provide a primary **criteria**

**Comment by hsandt** [comment]
Also, in Manual ranking:

entriers -> **entries**

**Comment by leafo** [comment]
Thanks for the report, these should have been fixed a while ago!
