### ISSUE TITLE
itch.io game disappeared

### ISSUE THREAD

**Issue by hl19** [itchio/itch.io#1005]
hello, my twine game on itch.io disappeared or cannot be found. the message is: 
There was a problem loading your project:
No file provided to embed
i'm wondering if anyone's encountered this problem, and if there is a way to retrieve my game somehow. thank you for any and all suggestions!

**Comment by leafo** [comment]
can you give us a link to your game so we can investigate? Thanks

From the error, I'm guessing you may have changed the settings on your project page, either removing the file or changing the embed options in some way that is preventing the file that is uploaded from being used

**Comment by hl19** [comment]
wow thanks for the super fast response! here are a couple links. any help highly appreciated!
https://hl19.itch.io/theres-a-first-time-for-everything
http://file:///Users/Helen/Downloads/There's%20a%20First%20Time%20For%20Everything.html



________________________________

**Comment by leafo** [comment]
You have to upload your game's file to itch.io, click the "Upload files" button. Do not use the "Add external file" button as that's suitable only for people who host files on another webserver.

**Comment by hl19** [comment]
thank you for your reply, leaf! who are you?
unfortunately i constructed my game online through the chrome browser. is there any way to recover the materials of my game?? there is no game file.

________________________________

**Comment by leafo** [comment]
Sorry for not getting back sooner. All you provided to itch.io was the text `http://file:///Users/Helen/Downloads/There's%20a%20First%20Time%20For%20Everything.html`, no game was part of that. 

Maybe you can check that path on your computer to find the file you're searching for?

Thanks

**Comment by hl19** [comment]
oh no apologies at all! i'm totally grateful for any help or advice you can spare.
every time i try to access the game there is an error message:

This site can’t be reached

file’s server IP address could not be found.

  *   Search Google for file Users Helen Downloads There's First Time For Everything<https://www.google.com/search?q=file%20Users%20Helen%20Downloads%20There%27s%20First%20Time%20For%20Everything>

ERR_NAME_NOT_RESOLVED


this is the same error message whether i try to download the game or just open HTML.
i'm hoping that the game (it's actually a story; branching narrative) hasn't completely disappeared and there's some way to access it again.
i composed it directly on chrome browser and uploaded to itch.io. the other game/story that i uploaded is there, but this one seems to have disappeared.
if there's any way whatsoever to retrieve/recover it somehow, i'd greatly appreciate any suggestions!
thank you~


________________________________

**Comment by fasterthanlime** [comment]
@hl19 From this path, it looks like you're using macOS - if you look into your Downloads folder (in Finder), you should be able to find a file named "There's a first time for everything.html".

When uploading to itch.io, click the "Upload files" button in Edit game:

![image](https://user-images.githubusercontent.com/7998310/61580863-e15b5480-ab16-11e9-97d9-ba8eb3d0af51.png)

..then find and select that html file in your downloads folder. Then save the page - it should be up!

**Comment by hl19** [comment]
omg it works, it works! THANK YOU so much, amos! i'm so glad and relieved to have it back!
can't thank you enough. so super. have a great day~!
warmest,
helen

________________________________
