### ISSUE TITLE
Itch.io Profile Header img CSS Incorrect

### ISSUE THREAD

**Issue by onefifth** [itchio/itch.io#1006]
My trash profile ([https://onefifth.itch.io/](https://onefifth.itch.io/)) looks like it accidentally some CSS and the header image is not correctly displayed as "Full Width".

index:10
```
.header .image_header img {
    /*! */
    nil /* */}
```

By pressing "Edit Theme" the CSS is temporally corrected to 
```
.header .image_header img {
    /*! */
    width: 100%;
    /* */}
```
and the banner image is correctly displayed using the desired "Full Width" option. The correction remains after closing the theme editor, but is lost upon refreshing the page.
This profile is not using any fancy or custom CSS.

**Comment by Elendow** [comment]
I have the exact same problem.

This is the banner of my profile after setting full width:
![fullwidth](https://user-images.githubusercontent.com/5699495/63922908-e54b9200-ca45-11e9-9b42-1c71e73b48a3.PNG)

The exact same banner after refreshing the page:
![fullwidthnotworking](https://user-images.githubusercontent.com/5699495/63922910-e54b9200-ca45-11e9-9556-207c7c3118e5.PNG)

**Comment by leafo** [comment]
Sorry I didn't get to this bug sooner. It should be fixed now.

**Comment by onefifth** [comment]
There is nothing to apologize for. You are great.

Thanks for getting to it! Looks fixed to me!
