### ISSUE TITLE
Open-graph metadata configuration for user page

### ISSUE THREAD

**Issue by raysan5** [itchio/itch.io#1008]
I'd like to setup my `user.itch.io` open-graph metadata for sharing it on social networks. At this moment it just picks the first available project metadata and no title or description is provided.

I couldn't find this option, excuse me if I missed it.

**Comment by leafo** [comment]
Could you tell me how you would like it to look? Maybe we can change the default so it's better for everyone.

**Comment by raysan5** [comment]
This is an illustration of the issue, I use my company user ([@raylibtech](https://raylibtech.itch.io/)) as a reference:
![itchio_user_social_card](https://user-images.githubusercontent.com/5766837/62285482-f78ddc80-b455-11e9-88e4-84dc171542ac.png)

The user card requires a wide image and a description.

In the case of games/tools pages, that metadata can be configured on:
 - **`Dashboard > $(GameName) > Metadata > Promo images`**

Maybe for the user that Metadata could be available in:
 - **`Settings > BASIC > Profile`**
or
 - **`Settings > MISC > Social Metadata`**

**Comment by raysan5** [comment]
Any news on this feature?

**Comment by vmenezio** [comment]
I see this issue is marked as complete, but can't find a way to actually set my profile metadata. Was this ever implemented? @leafo
