### ISSUE TITLE
Monkey X-I'm trying to create a enemy sprite which has a delay when he shoots

### ISSUE THREAD

**Issue by ritik0002** [itchio/itch.io#1010]
Is their a inbulid function/way which will allow me to create a delay when he shoots because currently when he shoots its just constant bullets

**Comment by fasterthanlime** [comment]
Hi, this is the issue tracker for the [itch.io website](https://itch.io), which hosts hundreds of thousands of games, not any game in particular.

Please reach out to the developer of Monkey X directly.
