### ISSUE TITLE
Showing source of game purchase

### ISSUE THREAD

**Issue by fluffy-critter** [itchio/itch.io#1011]
Somehow my "games I own" page shows multiple copies of Gone Home. I'm not sure how this happened. Did I buy it on its own and later get it as part of a bundle or something? Who knows!

It'd be neat if I could answer this question, so I can see if I'm, like, totally losing my mind or what.

(For what it's worth according to my email records that is exactly what happened - I bought Gone Home, then bought a bundle which contained it. But it'd be nice to not need to do an email search to find those answers.)

**Comment by leafo** [comment]
If you click into the download page for each purchase you can see a summary of how you obtained it. If it says nothing then you were granted a key from something (developer or service).

**Comment by fluffy-critter** [comment]
Oh, so it does. Why didn’t I think to try that? Sorry about that.
