### ISSUE TITLE
Game Jam not visible even after 1 week of publishing and over 50 joins.

### ISSUE THREAD

**Issue by divinosdev** [itchio/itch.io#1016]
Our game jam at https://itch.io/jam/stareoutgamejam is not visible on the calendar or the upcoming jam page. We promoted the jam on external websites but would love to know if there is a particular issue why our jam is not being featured, when jams with fewer joins and which are more recent have made their way to the calendar. Thank you so much.

**Comment by leafo** [comment]
Looks like it got into a bad state, was it originally published as an empty page?

In any case, it's correctly indexed now. Sorry about that.

**Comment by divinosdev** [comment]
Thank you so much for the quick reply @leafo. Yeah, I think we might have published an empty jam with a description just once to test things out. Thank you again!
