### ISSUE TITLE
Some typos in documentation pages

### ISSUE THREAD

**Issue by gostay** [itchio/itch.io#1017]
https://itch.io/docs/creators/faq
"Can share the information itch.io collected" is missing the word "I".  ("Can I share...")

https://itch.io/docs/creators/interact
"Interacting with your fans is important component to building and marketting"
should be "is an important component"
and "marketing" (one t).

**Comment by Deozaan** [comment]
I think you mean:

> and "marketing" (one t).

😁

**Comment by gostay** [comment]
Haha, fair cop.  Fortunately, _my_ typo is a lot less likely to be seen.  :)

**Comment by leafo** [comment]
fixed
