### ISSUE TITLE
Just a Typo

### ISSUE THREAD

**Issue by BetaTester704** [itchio/itch.io#1024]
Just noticed a type and wanted to point it out.

DashBoard->EditGame->MetaData->Promo Images

The text is as follows.

Logo — A transparent PNG with the logo of your game. **Shold** be legible on both white and black backgrounds, but typically placed on darker background. Logo should be arranged horizontally with a wider, rather than taller, aspect ratio. Logo will be overlayed across promotional modules in place of showing your project's title.

**Comment by leafo** [comment]
Thanks, fixed!
