### ISSUE TITLE
body_content HTML tag visible under comments.

### ISSUE THREAD

**Issue by srcnalt** [itchio/itch.io#1025]
Under some comments a html tag saying `<body_content></body_content>` is visible. That happens to be always at the end of the messages. So far happens on jam entry pages.

Can be seen at:
https://itch.io/jam/autumn-lisp-game-jam-2019/rate/502797
https://itch.io/jam/autumn-lisp-game-jam-2019/rate/502346
https://itch.io/jam/autumn-lisp-game-jam-2019/rate/498480

**Comment by leafo** [comment]
Thanks for the report, a regression that went out with a deploy today. I fixed the underlying issue and ran a script to clean up any posts that had that string appended
