### ISSUE TITLE
please use https for urls

### ISSUE THREAD

**Issue by jsoref** [itchio/itch.io#1028]
https://itch.io/jam/game-off-2019

> <a href="http://phaser.io/" rel="nofollow noopener">Phaser</a>
> <a href="http://www.libgdx.com/" rel="nofollow noopener">libGDX</a>.
> This jam is using <a target="_blank" href="http://itch.io">itch.io</a> to host entries.

Each of these projects has an https: site.

**Comment by Deozaan** [comment]
This has nothing to do with itch.io. It's up to the game jam host(s) to use HTTPS links when they set up the game jam's page. You should contact them about it.
