### ISSUE TITLE
email newsletter leaks info on (semi)private projects

### ISSUE THREAD

**Issue by empty-fortress** [itchio/itch.io#1029]
Hi, I just received a "new updates" newsletter from itch, when clicking the main news item to go read the dev's post I was asked for a password. I'm assuming it is a patreon-supported game or something similar, no big deal, the problem is the newsletter displays a preview of the post so there's a bit of the password-protected text that leaks out.

(Also, from a user experience point of view it's a bit jarring to be taken to a password-protected page with no link to navigate back to, say, the project page, but that's another bug report)

Not posting details because I don't know how secret exactly the project is supposed to be, send me a DM for more details. Cheers!

**Comment by leafo** [comment]
Thanks for the report. The issue has been fixed.
