### ISSUE TITLE
Feature Request: Infinite Scroll + Slow Connections Handling

### ISSUE THREAD

**Issue by Xananax** [itchio/itch.io#1031]
My connection is often spotty or slow. Infinitely scrolling lists, like collections, are problematic in that regard, because when my browser eventually gives up (which always happens), I need to refresh everything from the top, and then scroll back to where I was, counting on cache, and luck, to load just a little more this time.

It's a frustrating experience, which often means I simply can't reach the bottom of even a modestly long list.

### Proposed Solution:

Some websites which implement infinite scrolling reflect the position in the URL; upon refreshing, they start loading from that position on. I think this is a change that is relatively economical, because it requires no UX/UI changes. It "only" requires:

1. To use History to push state to the URL
2. To change the primary loading request if the URL contains a position

A minimal change in UX might be a bar at the top saying "you are on page **22** ([Load From the Top](#)". The link would clear the URL and reload from the beginning, reverting to default behaviour.

### Less Good Solution But Still Good 

In comparison, having a switch for infinite scrolling is less desirable, because it will invite bikeshedding about how exactly it should work, how the pagination should look, and where the checkbox should reside.

Furthermore, I am not *always* afflicted with a bad connection, and when I'm not, the infinite scrolling is welcome. It would be a bother to navigate menus in order to 

Finally, it is actually a less practical solution, because it will probably be hard to discover, which will lead to a very small contingent of power users knowing about it, whereas the first solution requires nothing on the part of the user.

----

Unrelated, but relevant to changes in the way scrolling is handled: https://github.com/itchio/itch.io/issues/23

**Comment by leafo** [comment]
There's already an option to disable infinite scrolling on your account settings. Try that out: [Disable auto-loading next page when browsing](https://itch.io/user/settings).

If it's not working on any pages tell me and I can look into it.

**Comment by Xananax** [comment]
Ooops! No, it works. In that case, I don't think there is anything to do. My comment about discoverability still stands though, I'm living proof :)
