### ISSUE TITLE
Certificate errors (expired?) for HTML5 games

### ISSUE THREAD

**Issue by jaredkrinke** [itchio/itch.io#1042]
As of right now, I'm seeing certificate errors (in both Edge and Chrome) for all HTML5 games I try to open on itch.io.

Example URL:
https://v6p9d9t4.ssl.hwcdn.net/html/1418191-223348/index.html

Error:
```
NET::ERR_CERT_DATE_INVALID
Subject: *.ssl.hwcdn.net
Issuer: COMODO RSA Domain Validation Secure Server CA
Expires on: Jan 20, 2020
Current date: Jan 20, 2020
```

**Comment by jaredkrinke** [comment]
I'm seeing an updated cert now, so it's working again. I'll close this issue.

**Comment by leafo** [comment]
that cert is managed by our CDN, so there's nothing we can do to update it. Glad it was resolved. 

For what it's worth, make sure you computer clock is network synchronized, it can cause certificates to expire early.
