### ISSUE TITLE
 There was a problem during setup: Timed out while connecting to butlerd

### ISSUE THREAD

**Issue by DangerousKitty65** [itchio/itch.io#1047]
So I decided to open the itch app and it just showed

There was a problem during setup: Timed out while connecting to butlerd

My antivirus is Malwarebytes

**Comment by leafo** [comment]
We can't offer any support while you have a virus scanner running. Try temporarily disabling it and try again. 

Thanks

**Comment by DangerousKitty65** [comment]
> We can't offer any support while you have a virus scanner running. Try temporarily disabling it and try again.
> 
> Thanks

I have turned it off and it is still happening

**Comment by fasterthanlime** [comment]
You can try to run https://fasterthanlime.itch.io/itch-diag to troubleshoot
any issues, you can also look at the log file in
%APPDATA%\itch\logs\itch.txt

**Comment by DangerousKitty65** [comment]
oh my god thank you
