### ISSUE TITLE
Can't get my Unity proyect to work in itch.io as a WebGL

### ISSUE THREAD

**Issue by TheDaveTacoMan** [itchio/itch.io#1048]
I builded my game in WebGL, Ziped my files and uploaded them into my proyect in itch.io, but i can't figure out why its not working

**Comment by leafo** [comment]
Do you have any sort of information we can work with? Error message or something? A page you can link to for us to investigate?

Thanks

**Comment by TheDaveTacoMan** [comment]
The itch.io page said "No file provided to embed", but the zip file has the index, do i need to have diferent files for the index and the archive?

**Comment by leafo** [comment]
You uploaded a rar file and marked it as hidden. Try uploading a zip file and don't mark it hidden.

**Comment by TheDaveTacoMan** [comment]
The itch.io page said "No file provided to embed", but the zip file has the index  do i need to have diferent files for the index and the archive?

https://thavi.itch.io/fatguy

**Comment by TheDaveTacoMan** [comment]
the file is not hidden anymore, but it seems like the game is not running from my perspective, it looks like something downloadable

**Comment by leafo** [comment]
You uploaded a file with the extension `.rar`. You must upload a file that is compressed in the zip format, which ends with the extension `.zip`. Your operating system may be configured to hide file extensions by default, so you may need to right click on the file and go to properties to see the full name. You can also see the full name from the itch.io interface.

Do not just rename the file, **you must compress it in the zip format**.

Hope that helps

**Comment by TheDaveTacoMan** [comment]
O my god yes thats it, thank you man im so sorry for the troubles
