### ISSUE TITLE
size problem on itch

### ISSUE THREAD

**Issue by Stigmamax** [itchio/itch.io#1053]
My game is a little more than 1GB and it is no longer accepted on itch. I sent 2 emails and no response!
https://stigmamax.itch.io/cutish

**Comment by fasterthanlime** [comment]
You can use https://itch.io/docs/butler to push up to 30 GiB.

**Comment by Stigmamax** [comment]
Trop compliqué, je n'ai rien compris.







____________________________________________________________________
*Cutish sur Steam <https://store.steampowered.com/app/1222170/Cutish/>*


Le lun. 16 mars 2020 à 09:13, Amos Wenger <notifications@github.com> a
écrit :

**Comment by fasterthanlime** [comment]
Comme steamcmd mais en plus simple - toutes les instructions sont disponibles ici, suivre étape par étape: https://itch.io/docs/butler/installing.html

Y'a quelques vidéos sur YouTube de personnes qui montrent la démarche en entier:

  * Une courte: https://www.youtube.com/watch?v=QT3EFQwoZe0
  * Une plus longue, avec des explications supplémentaires: https://www.youtube.com/watch?v=PXyzYRNLd1I

**Comment by Stigmamax** [comment]
impossible à installer avec Windows 7. J'ai toujours ce message 'butler'
n'est pas une commande reconnue. Portant je l'ai ajouté dans la variable
d'environnement.







____________________________________________________________________
*Cutish sur Steam <https://store.steampowered.com/app/1222170/Cutish/>*
