### ISSUE TITLE
authenticating (no saved credentials): retrieving wharf status: Get https://api.itch.io/wharf/status: context deadline exceeded

### ISSUE THREAD

**Issue by gtnardy** [itchio/itch.io#1056]
Hello I can't login, push or do any action anymore to my itch developer account, it happens both on my pc as on my VM (in another country)

![image](https://user-images.githubusercontent.com/6226807/77231970-f9d7af00-6b7c-11ea-9c84-ed2860be2a65.png)

![image](https://user-images.githubusercontent.com/6226807/77232465-d5c99d00-6b7f-11ea-8369-98b32169938e.png)

I have already tried deleting my API keys and loging out, seems to be something related to my account

**Comment by fasterthanlime** [comment]
The site is under heavy load at the moment, so I'm not surprised you're having this kind of issues. We're working on it, it should get better in the near future.

**Comment by gtnardy** [comment]
hmmm it can be, I'm seeing it since yesterday...
