### ISSUE TITLE
Login through GitHub not working

### ISSUE THREAD

**Issue by ntfshard** [itchio/itch.io#1057]
Attempt to login/create a new account through GitHub leads to page with text:

"We had some trouble connecting your account
Invalid state, please try again"

Even if remove all cookies ¯\_(ツ)_/¯

**Comment by monolifed** [comment]
Same here.
I created a [thread](https://itch.io/t/716631/login-with-github-fails): nothing.
I contacted support: waiting...

I also disconnected both accounts and reconnected to no avail

**Comment by sax0n0xas** [comment]
A workaround: find welcome email with verify link and click it. I'v got logged in this way.

**Comment by amishne** [comment]
> A workaround: find welcome email with verify link and click it. I'v got logged in this way.

I'm getting a "Invalid state, please try again" when trying that, I guess that welcome email needs to be relatively recent.

**Comment by monolifed** [comment]
Generally, those links only work for a short time. Otherwise it could pose a security.
Also I couldn't find mine.

**Comment by airtower-luna** [comment]
I have the same issue, fortunately password reset (using the same email address as my Github account) worked to get access to my account.

**Comment by lewispollard** [comment]
> I have the same issue, fortunately password reset (using the same email address as my Github account) worked to get access to my account.

This doesn't work for me, I am still locked out of my account.

**Comment by radzo73** [comment]
I was not sent an e-mail (as of yet) when connecting my GitHub account to itch.io, so I can't even use _that_ to access my account.

**Comment by goodevilgenius** [comment]
I'm having the same issue.
I didn't receive an email to my primary GitHub address, and when using password reset, it says "don't know anyone with that email". I tried both my public email address and my primary GitHub account email address.

**Comment by Jimbly** [comment]
Also having the same issue, would love an update when it's fixed.

**Comment by jmarsh411** [comment]
Also experiencing the same issue.

**Comment by marcinlazo** [comment]
I am also without access to my account because of this issue, cannot use the email workaround since I never gave itch.io my email. Would love some help to login and add email&pass.

**Comment by radzo73** [comment]
I would assume itch.io would use the email on my GitHub account, but either it doesn't grab it, or doesn't care to send me an email.

**Comment by leafo** [comment]
Could you try again, it should be fixed now. Sorry for the delay in getting a fix out.

**Comment by monolifed** [comment]
It worked! Thanks.

**Comment by Jimbly** [comment]
Works here too, thanks!

**Comment by nodeunit** [comment]
Finally resolved! Thank you

**Comment by marcinlazo** [comment]
Thank you! Added a password, just for future-proofing.

**Comment by zYouz** [comment]
same issue
