### ISSUE TITLE
User JBGarrison72 & Created Projects Not Showing in Search

### ISSUE THREAD

**Issue by JBGarrison72** [itchio/itch.io#1058]
Hi, wonder if someone can help. My username on Itch.io is JBGarrison72 and I have so far successfully created two projects.

Unfortunately my creator page and project pages are not being returned in search results from websites main searches.

Here's a screenshot of the search results and another of my valid creator page which DOES show the projects.
![search](https://user-images.githubusercontent.com/62369113/77604165-14888b80-6ecf-11ea-9df9-3283a24e339d.jpg)
![jbgarrison72](https://user-images.githubusercontent.com/62369113/77604168-15212200-6ecf-11ea-83d1-5bd3a59f442a.jpg)
![jbgarrison72](https://user-images.githubusercontent.com/62369113/77604174-1b170300-6ecf-11ea-8c74-c75a06f6dc8d.jpg)
![search](https://user-images.githubusercontent.com/62369113/77604176-1baf9980-6ecf-11ea-87c6-20d0a6f48718.jpg)
Thanks in advance for your help with this! :D

**Comment by leafo** [comment]
Please read here: https://itch.io/docs/creators/getting-indexed

New sellers may be subject to their pages being reviewed before they are indexed in our search and browse pages for security & safety. Thanks

**Comment by JBGarrison72** [comment]
Thanks very much @leafo !
