### ISSUE TITLE
Search Bar when search a game name keywords

### ISSUE THREAD

**Issue by alemura** [itchio/itch.io#1061]
When I try to search "pirates" my game doesn't appear. If you search "pirates crew" it appear.

Why using only the search key "pirates" my game does not appear, while others appear?

I have content, have title, subdescriptions, images, devlogs, but don't appear, some help?

**Comment by leafo** [comment]
Check here: https://itch.io/docs/creators/getting-indexed#limitations-of-search

Getting search right is hard, so we'll likely make changes in the future, but I don't think there's anything we can do right now to change how your project appears.
