### ISSUE TITLE
Views graph includes spurious extra views?

### ISSUE THREAD

**Issue by llemoi** [itchio/itch.io#1065]
![itch-analytics](https://user-images.githubusercontent.com/9464002/82561340-2010cf80-9b6b-11ea-8452-220f8f139378.png)

The views graph in my dashboard analytics is showing a extra grey bar at the top for some days. (It's for 2 views in both cases, but I don't know if that's a coincidence.) They don't show as being views of any project, but are counted in the total views for those days.

**Comment by llemoi** [comment]
I've had a look at the page in the Firefox Inspector; what's happening is that the SGV rect for the complete bar (class "total_bar") represents a total number of views = (sum of individual project view counts)+2; the grey "bar" is actually just the total_bar showing though from underneath.

So the problem is definitely that the view total is somehow being calculated as > the sum of the individual project view totals.

**Comment by leafo** [comment]
the gray bar represents views from other projects that aren't big enough a portion to get their own bar

**Comment by llemoi** [comment]
Ah, that makes sense. Perhaps a tooltip to say that's an aggregate of all other project views?
