### ISSUE TITLE
Twitch game won't play audio 

### ISSUE THREAD

**Issue by SoNotPaddy** [itchio/itch.io#1066]
Twine Version: 2.3.5
Story Format: SugarCube 2.30.0

I think I’ve found a post in every forum imaginable about this problem, but I still have no solution that works for me.
I can’t make audio play from my game in browser.
I know the code itself is correct: first I cache the sound file in the StoryInit passage - e.g. cacheaudio “mainsong” “Music/Glitterhater.MP3” - then when I need it to play, the code is audio mainsong play.
Whenever I make these changes, I publish to file. The relative pathways are correct, I’ve quadruple checked.
All my audio is MP3, so it’s not an issue with file type.
I know the audio should work, because when I play it from the .html file, the audio plays like a dream. But when I play it in the Twine application, or play it on itch.io, no audio. None.
I have made sure nothing is trying to play in the first passage, which I understand is occasionally a issue due to some bug with this version of Twine. I have tried playing the game on multiple browsers (Chrome, Firefox, Microsoft Edge). I have tried playing the game via itch.io on someone else’s device in multiple browsers.
No. Damn. Sound.
If anybody can help me, I’d be so grateful. I can provide more info upon request.
Thanks.

**Comment by fasterthanlime** [comment]
Can you post a link to the game's itch.io page?

**Comment by SoNotPaddy** [comment]
> Can you post a link to the game's itch.io page?

https://lipstix.itch.io/by-harald-lattimore

**Comment by SoNotPaddy** [comment]
Found the problem. Keep an eye on case-sensitivity people :)
