### ISSUE TITLE
Purchased Bundle Items Not Showing As Owned

### ISSUE THREAD

**Issue by horntm80** [itchio/itch.io#1078]
Bought the bundle Wednesday (2020-06-10), had trouble installing the app so I just waited for today. Finally got the app installed, but it showed nothing in the owned area. So I went to the website, got to the "Bundles you've purchased" page, followed that link. Then I went through all 55 pages of the bundle games from the link and added the ones I was most immediately interested in to collections. The collections show properly both on the web and in the app. However the only two that show as installable are free or name your own price. Everything else still has only the buy option.
![itchappnoowned](https://user-images.githubusercontent.com/45274159/84529566-aa061100-acaf-11ea-815b-91f0c76d6d33.jpg)
![showbundlegamewithonlypurchaseoption](https://user-images.githubusercontent.com/45274159/84529575-ad010180-acaf-11ea-8c07-ad81d47efdc9.jpg)
![showbundleowned](https://user-images.githubusercontent.com/45274159/84529611-bd18e100-acaf-11ea-8140-81af3a0314fe.jpg)

**Comment by JadianRadiator** [comment]
You have to "claim" the items in the bundle for them to show up in the app.
You do so by going to the download page for the bundle,
and manually clicking the download button for each and every item.

**Comment by JadianRadiator** [comment]
I've found something that makes it easier and less grindy to claim it all.
I took the `document.forms[3].children[2].click();` from [this page](https://gsantner.net/blog/2020/06/06/itchio-how-to-claim-all-bundle-games-to-library-racial-justice-and-equality.html?source=itchio),
and book-marked this `javascript:document.forms[3].children[2].click();`
And doing that suggestion this way means fewer button presses, which also take less brain-power.
That way you can do it on auto-pilot.
