### ISSUE TITLE
Feature Request: More Robust DL Feedback

### ISSUE THREAD

**Issue by s-20** [itchio/itch.io#1082]
I am having a problem downloading/installing some new games (from the ***BLM*** bundle). I assume it's a server problem related to the popularity of the bundle, but I don't know for sure. It would be great if there was a way to get more robust download information - maybe something that can be enabled in Advanced settings. Because right now, I have a DL that started 55 minutes ago, with no progress - just the [Cylon-eye feedback](https://imgur.com/zMBojN8) on the DL completion bar, *staring into my soul* and **judging my humanity**

**Comment by fasterthanlime** [comment]
I'd be curious to look at your log file (you can find it in Settings).

I hate indeterminate progress bars as much as everyone (I'm assuming), Cylon-eye is a nice way to refer to it! It's only used when the download is queueing, so in that case it hasn't even started yet, and 55 minutes is definitely way, way too much.

**Comment by s-20** [comment]
Hi! Sorry it's taken so long to get back to you; it's been a busy day and I only just noticed the reply!

I should have looked for a log file to attach - not sure what I was thinking. I gave it a glance over, and I can see where the problem occurs, I just can't tell what the problem is. In any case, I've attached the log (I think).
 
[itch.txt](https://github.com/itchio/itch.io/files/4790210/itch.txt)

**Comment by s-20** [comment]
Just to let you know, the DLs appear to be working now. I also know how to find the logs now, so I guess that this issue is closed. Sorry to cause trouble - looks like I just needed to be patient.

**Comment by fasterthanlime** [comment]
> Sorry to cause trouble

Nah, I'm just as frustrated as everyone else - occasionally our CDN will just misbehave *badly*. We're actively looking into alternatives but there's a lot of factors to take into consideration, so until then, it's a bit of a lottery - some days it works great, some other days.. not that great.
