### ISSUE TITLE
"download bundle" page not allowing to download a bundle

### ISSUE THREAD

**Issue by tuxun** [itchio/itch.io#1086]
![bottomitch](https://user-images.githubusercontent.com/3581513/85892741-c5196a80-b7f1-11ea-9d1e-ccd816abbcb7.png)
![topitch](https://user-images.githubusercontent.com/3581513/85892746-c5b20100-b7f1-11ea-8c99-7c0d3ab992ef.png)

**Comment by tuxun** [comment]
missing "download bundle" link on "download bundle" page? or website lied to more than 8 millions people?

**Comment by leafo** [comment]
There is no button to download the entire bundle, you will have to select the games you want and click the "Download" button to access them individually. It will not start the download immediately but take you to another page where you can access the game files. Hope that helps.

(The first time you click the download button, you will also have those games shown in your main itch.io library)

**Comment by tuxun** [comment]
but why is it called a "download bundle" page if we cant use it to download the bundle?

**Comment by leafo** [comment]
Because that's the page where you go to access all the content in the bundle.

We have no plans to add a bulk download button at this time. Keep in mind you will own this content forever so you're free to return to the page at any time to get something.

Thanks

**Comment by tuxun** [comment]
Meanwhile i'm unable to access to the full bundle, its just a scam

**Comment by tuxun** [comment]
<<We are liers but we don't care cause we close issues of peoples warning us>>

**Comment by leafo** [comment]
> Meanwhile i'm unable to access to the full bundle, its just a scam

I think there's a communication issue going on here, you can access every project from the bundle on your purchase receipt page. If you purchased it, then have access to the full bundle.

It appears you are upset that we don't let you access the bundle in a way that you like. As I said, I'm sorry, but we will not be providing a bulk download button at this time. In the future, if we do larger charity events like this again, we may look into making that user experience better, but our priority at the moment is not investing in new functionality for a one-off event. There are a lot of technical considerations to be made with a bundle of this size, and it's not a trivial thing to add a "download all" button.

Hope that explains

If you have nothing constructive to add to the issue then I will lock the topic.

Thanks

**Comment by tuxun** [comment]
I solved this case asking for a refund and never came back to this platform.
Yes you sold millions of more than 1TB bundle and its not a trivial thing to distribute them.
The real question behind this, is: <<is this a reason for use misleading title on a webpage?>> and <<why would you sell things you cant distribute?>> my NAS was ready, him.
