### ISSUE TITLE
Needing Email Approval

### ISSUE THREAD

**Issue by Giganiky** [itchio/itch.io#1088]
Hello ! 
Looking to get email approval to send download keys for The Baby In The Bean to my kickstarter backers ~ Any help would be much appreciated!

Thanks in advance,
Niky Crawford

**Comment by leafo** [comment]
Have you send in a support email? https://itch.io/support

If not please do so. 

Reply with the email ticket ID when you have one and I'll check the ticket.

Thanks

**Comment by Giganiky** [comment]
Hey there ! I sent an email yesterday but didn't get an email ticket ID ? I'll try again.

**Comment by leafo** [comment]
If you send an email to our support system then you'll get an automated confirmation email back that contains a number in it

**Comment by Giganiky** [comment]
Got it, here's the ticket: 55444

**Comment by leafo** [comment]
Thanks, should be resolved now.
