### ISSUE TITLE
Download links are http

### ISSUE THREAD

**Issue by mimi89999** [itchio/itch.io#1090]
Hello,
I noticed that download links on your website (https://itch.io/app) are http only. After one visits them, he is redirected to teir https version, but it's a bit too late because an attacker could have already served his installer.

**Comment by fasterthanlime** [comment]
Yeah that's not great, @leafo when you have a minute, could you change to https? https://nuts.itch.ovh does serve https.

**Comment by leafo** [comment]
should be fixed now, thanks for the report
