### ISSUE TITLE
Asset pages should have a "Report" option.

### ISSUE THREAD

**Issue by BadCoyoteStudios** [itchio/itch.io#1092]
I have run into pirated assets on the site several times and there's no easy way to report them.

**Comment by leafo** [comment]
There's a report link on the very bottom of every project page, regardless of the type of content it is. Hope that helps. Tell me if you're still having trouble reporting it.

Thanks

**Comment by BadCoyoteStudios** [comment]
I swear those bottom links were missing. Closing.
