### ISSUE TITLE
A Javascript file is being served with the wrong MIME type

### ISSUE THREAD

**Issue by gamma-delta** [itchio/itch.io#1093]
Hello,

I am working on a browser game for a game jam right now. One of the JS files is being served by your servers with the incorrect MIME type `text/html`. So the game won't work on your servers. (It works fine on my local webserver.)

[Here is the link to the game](https://gamma-delta.itch.io/enigma). The problem is with `hitbox.js`. All the other js files get served with `application/javascript` just fine.

I can't think of any difference between `hitbox.js` and any of the other files.

Please send help! The game is due in under 24 hours.

**Comment by gamma-delta** [comment]
The problem seems to be with the name `hitbox.js`. I changed it to `hitboxWithCorrectMimeTypePlease.js` and it works fine.

**Comment by leafo** [comment]
Can you give a link to the original copy of the game that was giving you trouble so we can investigate, we can't test it now that you've uploaded a new version of the game. 

Thanks

**Comment by gamma-delta** [comment]
I've edited this a little since then, but the issue still should be here. (I just changed the name back to `hitbox.js`).

https://www.mediafire.com/file/9r5c7yo99tvmd7b/broken.zip/file

**Comment by leafo** [comment]
I'm unable to reproduce the issue in the archive you provided. Here's what I see:

![image](https://user-images.githubusercontent.com/15198/87748787-bd733300-c7ab-11ea-8d1b-259f3278806c.png)
