### ISSUE TITLE
Adult/NSFW filter is broken

### ISSUE THREAD

**Issue by haikarainen** [itchio/itch.io#1095]
I've been trying to remove some very NSFW/perverted content from my itch.io feeds, and I found a setting to disable NSFW content in my profile, however the NSFW content still remains. I have unchecked the `Show content marked as adult in search & browse` checkbox in my account settings, to no avail.

Please fix this. Not only do I personally find that kind of content highly distasteful, but I also want my kids to be able to enjoy the great collection of indie games on your platform. Obviously they will not be able to if this kind of content can not be filtered out.

Warm regards,

**Comment by leafo** [comment]
Sorry you're having trouble, I need some more information to identify the issue.

* Can you share which piece of content you see that you don't expect to see
* Can you share your account username?

If you don't want to share any of this publicly, please mail support@itch.io and reply back to me with the ticket ID.

Thanks

**Comment by haikarainen** [comment]
@leafo  Thank you! The content is a featured collection featuring BDSM and a bunch of other stuff. My itch username is haikatekk.

**Comment by haikarainen** [comment]
It doesnt seem to be there today. Feel free to close the issue if you want!

**Comment by haikarainen** [comment]
Nevermind, it's back.

![itch-issue-1095-screen000](https://user-images.githubusercontent.com/850310/87874243-8332ad00-c9c8-11ea-8f09-5eba5024837d.png)

**Comment by haikarainen** [comment]
@leafo
