### ISSUE TITLE
PayPal says games cost too much

### ISSUE THREAD

**Issue by samfromcadott** [itchio/itch.io#110]
When ever I attempt to pay more than $1 on itch.io PayPal says there is not enough money in my account and I need to add a card. I have my PayPal account linked to my bank account and have well over the money I need for the games I would like to buy. Itch.io is the only site that this has happened to me.

**Comment by leafo** [comment]
Could you email (or write here if you comfortable with sharing that information) with a game you've tried purchasing recently that hasn't worked so I can look up the logged data. Also if you have an itch.io account and are purchasing while logged in tell me the account name too.

email is leafo@itch.io

**Comment by samgj** [comment]
I tried it again. Still doesn't let me buy.
