### ISSUE TITLE
Content Manager by x4fab purchase - lost key

### ISSUE THREAD

**Issue by xxtecraxx** [itchio/itch.io#1100]
please respond as i have supplied the necessary documentation from my purchase to retrieve my key.  i have waited patiently without a response for days now.  i paid $5, not $3 a year ago.  i've previously emailed support with the transaction ID and copy of the paypal receipt.  i really want to have access to the software without paying for it twice.  thanks

**Comment by leafo** [comment]
We can't provide private account support on our public github issues tracker. Keep in mind we get around 100 tickets a day, so any patience with response times is appreciated. If you want me to investigate an issue you can provide me with a ticket id that you received in the receipt email.

Thanks

**Comment by xxtecraxx** [comment]
57901
thank you for your assistance
