### ISSUE TITLE
Need a secure way to integrate an installed Itch game, its own online service, and the player's Itch account

### ISSUE THREAD

**Issue by PixievoltNo1** [itchio/itch.io#1108]
As I understand it, if I'm making a game to be installed with the Itch app and providing my own online service (for cloud saves / multiplayer / etc.), and I want the player to able to use their Itch account, the best way currently is to have the game request a JWT key and send it to my service, which then contacts Itch to determine whose token it is. Problem is, any game could request a JWT key and pass it to my service, looking just like my game and potentially doing Bad Stuff.

A simple way to secure this would be to have [the /credentials/info endpoint](https://itch.io/docs/api/serverside#reference/httpsitchioapi1keycredentialsinfo) include the id of the game in its response.

(A malicious app could still pretend to be my game by editing my game's files or messing with its network traffic. I hope the sandbox prevents Itch games from doing that to each other!)

**Comment by fasterthanlime** [comment]
I'm going to let Leaf handle the other questions here but just about that point:

> (A malicious app could still pretend to be my game by editing my game's files or messing with its network traffic. I hope the sandbox prevents Itch games from doing that to each other!)

No, that's not part of the security model of the (experimental) itch sandbox - it's meant to protect user data, not the integrity of other games.

**Comment by leafo** [comment]
The only goal of the JWT based API token is to verify who, it is not a method used to secure any network requests you are receiving. It's your responsibility to determine the authenticity of a request with how it relates to your application. Including a game id does not seem like a solution to your problem because the potential user just generate one for your game. It seems like maybe you want to check if a particular user ID owns your game? You can do that with this API call: https://itch.io/docs/api/serverside#download_keys

**Comment by PixievoltNo1** [comment]
No, I'm talking about *game* ids. Those are unique and generated by Itch, right? The Itch app knows which app it's launching when it makes a JWT to pass to it, and I'd like that knowledge shared with my server in some fashion. I'm aware it doesn't guarantee authenticity (especially when a player's hacking themselves, which I'm not interested in preventing), but it'll make it harder for 3rd parties to hack my players than just "submit something to Itch that also asks for a JWT".

**Comment by leafo** [comment]
> No, I'm talking about game ids

That's what I addressed in my response. The JWT API key gives you a scoped API key for a particular user (the one launching your game). It has nothing to do with a particular project. You decide how you want to use that API key to verify if they own a project or to look up their account to see what they should be allowed to do.

> Those are unique and generated by Itch

They are unique and generated, but they are also sequential integers that are public information associated with a game.

> but it'll make it harder for 3rd parties to hack my players than just "submit something to Itch that also asks for a JWT"

This makes it sound like you are accepting any JWT token to make changes to any user account on your backend. As I mentioned above, it's your responsibility to authenticate a request in a way that makes sense to your application. You could, for example, use the JWT API key to [request the user's ID](https://itch.io/docs/api/serverside#reference/profileme-httpsitchioapi1keyme) if you want to have a way to associate an account with actions on your backend. If you have a paid game, then you can use the [download keys endpoint](https://itch.io/docs/api/serverside#download_keys) to lock user activity to only those that buy the game.

**Comment by leafo** [comment]
I'm going to close this ticket now, feel free to tell me if you still have any questions. Thanks
