### ISSUE TITLE
Allow jam submissions to be rated with screen readers

### ISSUE THREAD

**Issue by nicross** [itchio/itch.io#1109]
This seems to be a similar but separate issue to #1094.

I'm running a jam that features blind-friendly games. Some of our judges, who are blind, cannot access the star rating system on the jam submission page. This issue is critical for us because it means that our target audience cannot participate in voting.

In a reply on the linked issue, @leafo mentioned that an accessible star picker exists on the "Things to Rate" page. Is it possible to migrate this before our voting period ends on September 6?

Thanks for understanding.

**Comment by ogomez92** [comment]
Yes, it's really bad because as a blind person I can't rate for a blind-friendly jam. We'll probably have to extend voting period or something, I guess.

**Comment by leafo** [comment]
I'll try to get a fix out for this shortly, thanks!

**Comment by nicross** [comment]
Hi @leafo. Thanks for your quick response and your commitment to our community. Has there been any progress on your end? We're happy to extend our voting period if this week is unrealistic for you.

**Comment by nicross** [comment]
Here's an example of the bookmarklet that I'd share with my community.

Bookmarklet:
```js
javascript:!function(){const e=document.querySelectorAll(".criteria_row");for(let r=0;r<e.length;r++){const t=e[r],c=t.querySelector(".crit_label").innerHTML;let l;do{if(!(l=prompt("Enter rating for "+c+" (1 through 5)")))return;l=Number(l)}while(isNaN(l)||l<1||l>5);t.querySelectorAll(".star")[l-1].click()}confirm("Save rating?")&&document.querySelector(".rate_btn").click()}()
```

Full source:
```js
(function () {
  const rows = document.querySelectorAll('.criteria_row')

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i]
    const label = row.querySelector('.crit_label').innerHTML

    let rating

    do {
      rating = prompt('Enter rating for ' + label + ' (1 through 5)')

      if (!rating) {
        return
      }

      rating = Number(rating)
    } while (isNaN(rating) || rating < 1 || rating > 5)

    row.querySelectorAll('.star')[rating - 1].click()
  }

  if (confirm('Save rating?')) {
    document.querySelector('.rate_btn').click()
  }
})()
```

**Comment by leafo** [comment]
Hey all, I've just deployed an update that uses are newer rating picker that correctly uses button elements for the ratings. I did not get a chance to test on a screen reader yet, I'm unsure about how the criteria name + rating button as associated, if it's confusing what you're rating tell me and I'll look into better labels

**Comment by nicross** [comment]
Awesome! I tested the page with NVDA. The buttons are now in the tab order and able to be selected. Currently they're announced like this: "1 star, button", "2 stars, button", etc. So it's _almost_ there.

What might improve them is to associate them with the name of the criteria. This is a good use case for the `aria-describedby` attribute, but you could also cheat by appending the criteria name to the button title (e.g. in parentheses):

```js
<tr class="criteria_row">
  <td class="crit_label" id="unique_label_id">Criteria Name</td>
  <td>
    <div class="forms_star_picker_widget star_picker interactive">
      <input type="hidden" name="ratings[Accessibility]" value="">
      <button type="button" title="1 Star" aria-describedby="unique_label_id"><span class="star icon icon-star2"></span></button>
      <!-- ... -->
    </div>
  </td>
</tr>
```

With this change a screen reader would announce "1 star, button, criteria name", "2 stars, button, criteria name", etc. Hope this helps.

**Comment by leafo** [comment]
Thanks for the suggestion, I've deployed a change that adds `aria-describedby`

**Comment by nicross** [comment]
Thanks for the quick fix! Overnight I shared the update with a few folks who use screen readers on a daily basis. We encountered one major issue.

The `title` attribute is good for providing a visible tooltip, but not all screen readers use it to provide an accessible label. For some of our users they were just hearing "button, category name". This can be improved with the `aria-label` attribute:

```
<button type="button" title="1 Star" aria-describedby="unique_label_id" aria-label="1 Star"><span class="star icon icon-star2"></span></button>
```

Something that would improve its overall usability would be to use `<input type="radio" />` instead of buttons. If that's not feasible, then you could use the `role` and `aria-checked` attributes to turn your buttons into radio groups. Both solutions help indicate state to screen readers, and they give us better keyboard controls for free (e.g. arrow keys).

Here's an example of that, where the outer div gets `role="radiogroup"`, its buttons get `role="radio"`, and the selected button gets `aria-checked="true"`:

```
<tr class="criteria_row">
  <td class="crit_label" id="unique_label_id">Criteria Name</td>
  <td>
    <div class="forms_star_picker_widget star_picker interactive" role="radiogroup" aria-labeledby="unique_label_id">
      <input type="hidden" name="ratings[Criteria]" value="">
      <button role="radio" type="button" title="1 Star - Selected" aria-checked="true" aria-describedby="unique_label_id" aria-label="1 star"><span class="star icon icon-star2"></span></button>
      <!-- ... -->
    </div>
  </td>
</tr>
```

Thanks again for your help.

**Comment by leafo** [comment]
Thanks for the suggestions, I've made those changes. Tell me if there are any issues.
