### ISSUE TITLE
Asset forge resolution on Mac

### ISSUE THREAD

**Issue by eli-bd** [itchio/itch.io#1114]
I just bought and installed the asset forge. Asset forge 2.1.0 resolution is too hight. I can't see anything since everything is too small (can't read the menu)
I have a Macbook Pro that runs 13 inch MacOS Catalina (10.15.5) with 2560x1600 resolution.
Asset forge 1 looks fine. The problem is only with version 2.1.0

**Comment by leafo** [comment]
Hey, this is the itch.io issues tracker. We host over 200k games & projects. There's no support for individual projects here, you will have to reach out to the creator directly. Typically you can find a way to contact them on their projects page, but if not you can [email our support team](https://itch.io/support) and we can CC you in an email thread with them. Thanks
