### ISSUE TITLE
Bug: Page layout when trying to enable payout mode near unreadable and can't be clicked

### ISSUE THREAD

**Issue by NathanWeasel** [itchio/itch.io#1116]
![itchioscreenshot000](https://user-images.githubusercontent.com/62185664/96351446-52c2e380-1089-11eb-8e79-ed68fa647651.PNG)

"Help" is the only button on this page that does anything.

**Comment by leafo** [comment]
We don't create this page, it's managed by a third party tax management company we use. You can contact their support team to report issues like this here: taxclientsupport-itch AT taxidentity.com
