### ISSUE TITLE
WebXR games do not function correctly because of xr-spatial-tracking feature policy.

### ISSUE THREAD

**Issue by msub2** [itchio/itch.io#1117]
There are currently a handful of WebXR games on itch.io, but nearly all of them do not function correctly. Through some experimenting, I found that by using this [Feature Policy Control](https://chrome.google.com/webstore/detail/feature-policy-control/gnhcejibdkgceebbeljdolienjplkpin) extension on Chrome and creating a rule to override [xr-spatial-tracking](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/xr-spatial-tracking) to be allowed in all contexts, WebXR games started working properly. 

I can't think of a reason for keeping these games broken. I've been wanting to host some jams for WebXR games through itch, and I believe this is the only thing standing in the way of that.

**Comment by bferguson3** [comment]
Can confirm this is the issue causing WebXR games to be unable to find a proper XR context.

Console log shows the following error:
`index.html:71 Uncaught (in promise) DOMException: Failed to execute 'isSessionSupported' on 'XRSystem': Access to the feature "xr" is disallowed by feature policy.`

user: "The iframe needs allow="xr-spatial-tracking", which maybe itch.io would need to set"

Example WebXR game to test policy:
https://shinyogre.itch.io/nocturne-no-1

**Comment by leafo** [comment]
I've added `xr-spatial-tracking` to the allow list, tell me if there's any other changes that need to be done, I don't have anything to test it.

**Comment by De-Panther** [comment]
Thanks. It works :)
