### ISSUE TITLE
Failed to get the purchased item

### ISSUE THREAD

**Issue by llttr** [itchio/itch.io#1119]
My email：445606009@qq.com
I paid for the goods：Halloween Sale 2020
![image](https://user-images.githubusercontent.com/73581240/98203530-2f47d600-1f6f-11eb-9dff-96259d1879b6.png)

**Comment by Bohaska** [comment]
You need to go to https://itch.io/support. Itch.io's staff cannot help you here.
你需要去https://itch.io/support。itch.io的全体职员不可以在这边帮助你。

**Comment by leafo** [comment]
That's correct, we can't offer payment support on the issues tracker. Please contact us from here https://itch.io/support and ensure you include your relevant payment information in the email so we can look up your transaction.

In case anyone else has a similar issue, we have seen instances where PayPal will put a payment on hold for 24 hours for their own internal review before the funds are released to us. I've seen this happen quite a bit with buyers located in China. Once the payment clears then you will automatically receive your download receipt in your email.

Thanks
