### ISSUE TITLE
wont let me install the app Problem during Warm up

### ISSUE THREAD

**Issue by JuanPancho-code** [itchio/itch.io#1120]
Something went wrong

itch-setup, v1.24.0, built on Jun 29 2020 @ 17:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255

Get "https://w3g3a5v6.ssl.hwcdn.net/build/295201/1125554-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1605315323&Signature=JLslEc5OZU1CvKhEzJgYXPncRNWMjWdTXpPIuIsyR2gKoa5wK0lHhmSzkskexFFBqL4Qebpj6L1581tCRTMIVOLH6DfeGH%2Fq4QtZfWU8Y5sJZ611VGm7KTR4My8zuDnMeCkZBCOjnMlLOCKqCJu5e3vdFGbS6Tn%2Fp2Mdm78e7Ebs2dVSahAcr%2FPwQpWz0yc58hueSYOHIK10KAeqJ7AeBNU0o1T%2FWiWGN7L8m7eVw1AOLZUnWb8WxBIz5fEz2JZ0%2FJ%2B6qR9YjTQyTZmDZEPa5BQmaIJh1rMdFAr6sTd%2FKApxUpxuQ9wgM6lsS0qNyVos9y6%2BSydGuMejIeMVh%2BvXvg==&hwexp=1605315613&hwsig=f216fb8b7b1021b1903eedde294511f6": dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.
in conn.tryConnect, while doing GET request
github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:128
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:56
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
in conn.Connect, exhausted retry context
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:88
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
htfs.Open (initial request)
github.com/itchio/httpkit/htfs.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:182
github.com/itchio/httpkit/eos.realOpen
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
while opening remote signature file
Error during warm-up

**Comment by leafo** [comment]
The error tells you want happened, you were not able to connect to the server to download files. Check your network provider or firewall. We're not aware of any widespread outage.
