### ISSUE TITLE
Overlapping sales - game can't be bought at a discount as intended

### ISSUE THREAD

**Issue by Draknek** [itchio/itch.io#1124]
Sale 1: https://itch.io/s/34856/draknek-friends-puzzle-bundle - includes 4 games with no % discount and a "buy all" price of $40
Sale 2: https://itch.io/s/39693/draknek-friends-autumn-sale-2020 - includes the same 4 games with a 15% discount and a lower "buy all" price of $25

Expected behaviour: each game's page shows the game available for 15% off
Actual behaviour: each game's page only shows the game available for full price

E.g. https://draknek.itch.io/a-monsters-expedition

I'm pretty sure this has worked in the past? Not sure what's different here

Possibly related: #663

**Comment by Draknek** [comment]
Update: this doesn't seem to be related to overlapping sales as I thought. Editing the newer/more-discounted sale and saving it made the discount show up. So something else weird is going on I guess.

**Comment by leafo** [comment]
The only thing I can think of is that we use an internal state flag to represent the state of the sale (before, during, after) to check if it's active. It's possible something about you edited it caused this to get out of sync, did you change the dates of it at any time?

**Comment by Draknek** [comment]
Not that I can remember.

I have another scheduled sale for December, I guess I'll see if it happens again then.

**Comment by Draknek** [comment]
Worked this time, big shrug
