### ISSUE TITLE
Dark theme makes card numbers hard to see

### ISSUE THREAD

**Issue by 1011X** [itchio/itch.io#1125]
Ran into this while trying to add a new card to my account. The text is black on a very dark gray background when the dark theme is enabled and makes the numbers hard to see.

![itchio_bug_sample](https://user-images.githubusercontent.com/1851619/100535722-64181780-3213-11eb-82e2-8ac289752985.png)

(rest assured the numbers are just as real as the name)

**Comment by leafo** [comment]
Thanks for the report, this should be fixed now
