### ISSUE TITLE
Backslash can't be typed if game page uses Nanum Gothic font.

### ISSUE THREAD

**Issue by Bananaft** [itchio/itch.io#1126]
Backslash ​symbol can't be typed if game page uses Nanum Gothic font.​ It gets replaced by strikethrough​ W letter. Noticed when copypasted windows path.

![image](https://user-images.githubusercontent.com/11929430/101238327-4fe78500-3701-11eb-82ce-dc3bd226d844.png)

**Comment by leafo** [comment]
This appears to be a feature of that font. If it's a font you have chosen, then I recommend choosing another font, as this font is designed for Korean text.
