### ISSUE TITLE
URLs ending in numbers can corrupt custom game jam rankings

### ISSUE THREAD

**Issue by funkeh** [itchio/itch.io#1134]
Hi! I recently hosted the SCREAM FM game jam. When adding in the rankings for our "Hosts' Choice" category, I stumbled across an error. I put in the rankings as below:
![error_1](https://user-images.githubusercontent.com/1741893/103040788-b1946400-45c8-11eb-83fd-f070b0b0f244.PNG)

But after I had saved, the page looked like this:
![error_2](https://user-images.githubusercontent.com/1741893/103040814-bf49e980-45c8-11eb-811e-2a19efd6194f.PNG)

Clearly the URL from the fourth line is modifying the fifth line. I worked around this by moving the offending URL to the bottom of the list.

**Comment by leafo** [comment]
Sorry about the delay, this issue should be fixed now. Thanks for reporting it
