### ISSUE TITLE
Profile page shows HTML code after editing

### ISSUE THREAD

**Issue by Proliecan** [itchio/itch.io#1140]
I wrote some HTML for my profile page (with css) and now the profile page shows parts of the content not as i intended but as HTML code. I checked the code on other platforms and it seems to be okay. Indeed, in the 'edit profile' tab, it is shown corectly, the problem only occurrs on the final page:

![grafik](https://user-images.githubusercontent.com/65495509/103289093-a84f3100-49e6-11eb-9559-0e2ba1fb7827.png)
![grafik](https://user-images.githubusercontent.com/65495509/103289182-dd5b8380-49e6-11eb-9772-62e7dcce76c6.png)

**And here is my code:**

```html
<style>
.glow-on-hover {
    width: 300px;
    height: 50px;
    border: none;
    outline: none;
    color: #fff;
    background: #4A589B;
    cursor: pointer;
    position: relative;
    z-index: 0;
    border-radius: 10px;
    vertical-align: middle;
}
.glow-on-hover:before {
    content: '';
    background: linear-gradient(45deg, #FEDA77, #F58529, #DD2A7B, #515BD4, #8134AF, #F58529, #FEDA77);
    position: absolute;
    top: -2px;
    left:-2px;
    background-size: 400%;
    z-index: -1;
    filter: blur(5px);
    width: calc(100% + 4px);
    height: calc(100% + 4px);
    animation: glowing 20s linear infinite;
    opacity: 0;
    transition: opacity .3s ease-in-out;
    border-radius: 10px;
}
.glow-on-hover:active {
    color: #fff
}
.glow-on-hover:active:after {
    background: transparent;
}
.glow-on-hover:hover:before {
    opacity: 1;
}
.glow-on-hover:after {
    z-index: -1;
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
    background: #4A589B;
    left: 0;
    top: 0;
    border-radius: 10px;
}
@keyframes glowing {
    0% { background-position: 0 0; }
    50% { background-position: 100% 0; }
    100% { background-position: 0 0; }
}
.right {
  display: flex;
  justify-content: right;
  align-items: center;
  }
.container {
  position: relative;
  text-align: center;
  }
.link{
  text-decoration: underline;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>

<p>
<strong>Hi, I am ---------</strong>
</p>
<p>I try to learn game Development on my own!</p>
<p style="border: 1px solid #ccc;" class="text-center">
<em>"Video games foster the mindset<br>that allows creativity to grow."</em><br>
- Nolan Bushnell</p>
<div class="right">
<button class="glow-on-hover" type="button"> 
---------
<strong class="container">
<img src="---------">
<strong class="link">---------</strong>
</strong>
</button>
</div>
```

**Comment by leafo** [comment]
We only allow a subset of html to be included on pages you can create for security reasons. Any tags that we do not allow accounts to use will show up as plain text.

We do allow for custom CSS on request: https://itch.io/docs/creators/design#the-itchio-theme-editor/custom-css

**Comment by Proliecan** [comment]
> 
> 
> We only allow a subset of html to be included on pages you can create for security reasons. Any tags that we do not allow accounts to use will show up as plain text.
> 
> We do allow for custom CSS on request: https://itch.io/docs/creators/design#the-itchio-theme-editor/custom-css

Thank you for your help!
Where can I find a list of tags that are not allowed?
