### ISSUE TITLE
Incorrect comma usage in jam "Starts in" and "Submission closes in"

### ISSUE THREAD

**Issue by James103** [itchio/itch.io#1157]
Itch.io has recently updated how they display the timers next to "Starts in" and "Submission closes in" on the jam listings to add more precision, but in doing so, there is a comma inserted between the first subdivision and second subdivision that should not be there. For example, "Starts in a day, and 8 hours" should instead be "Starts in a day and 8 hours" as the latter is more consistent with how people would usually write such phrases. Similarly, "Submission closes in 8 years, and 10 months" should instead be "Submission closes in 8 years and 10 months" and "Voting ends in 13 hours, and 16 minutes" should instead be "Voting ends in 13 hours and 16 minutes".

**Example screenshots**
![image](https://user-images.githubusercontent.com/37945304/107839521-1fac0a80-6d72-11eb-8e80-2bce523ddef4.png)
![image](https://user-images.githubusercontent.com/37945304/107839528-29357280-6d72-11eb-9ea6-9132c463c51a.png)
![image](https://user-images.githubusercontent.com/37945304/107839650-ee800a00-6d72-11eb-930d-22bee71ddc6e.png)

**Comment by leafo** [comment]
This change was unintentional and I've referted the format of the timestamp back to showing one unit of time.
