### ISSUE TITLE
No time is mentioned in jam listing where it says "Ended ... ago"

### ISSUE THREAD

**Issue by James103** [itchio/itch.io#1158]
Currently, when you go to the itch.io jam listings and filter by jams that have ended, all of them will say that they have "Ended ago", whereas it should be more like "Ended a year and 4 months ago", "Ended 4 years and 5 months ago", or "Ended 24 days and 3 hours ago".

**Example screenshots**
![image](https://user-images.githubusercontent.com/37945304/107839616-a95bd800-6d72-11eb-869b-356fc5f2094b.png)

**Comment by leafo** [comment]
Thanks for reporting, small bug when updating date library. Should be fixed now.
