### ISSUE TITLE
Duplicate title results in two gamejam submissions

### ISSUE THREAD

**Issue by idbrii** [itchio/itch.io#1165]
I was having problems submitting to a gamejam, so I created a duplicate project *with the same name*.

I was able to submit the duplicate to the gamejam, but when I did so, the original project was also submitted! I guess the drop down is done by name only, so it matched all games with the same name.

I removed the duplicate submission and deleted the game, but [here's the original submission](https://itch.io/jam/eggplant-podcast-community-game-jam/rate/937263).

Specifics about submission problems:

I created the project from the "Upload game" button on the gamejam submit dialog.

I fiddled around with the settings a lot including adjusting the theme before setting Public. When I set Public, I enabled “Don’t show in search”. 

Game showed as green published in my dashboard but was not pickable in the [jam submit dialog](https://itch.io/jam/eggplant-podcast-community-game-jam) (I tried reloading the page before clicking the submit button). 

I changed the project's url to prefix with broken- and then I recreated it with a new project without filling in all the fields and without changing many defaults. I used the original project's unprefixed url. I was able to choose that project to submit to the gamejam. Well, I guess I just submitted that name and both projects were submitted.

**Comment by leafo** [comment]
Project submission is not done by title, but is done by ID. It sounds like you actually did submit your first title but maybe there was something confusing about the UI that made it not clear.
