### ISSUE TITLE
On kitch, Button says "Buy Now" when scrolling through library even though its already owned

### ISSUE THREAD

**Issue by relma2** [itchio/itch.io#1171]
A User had purchased the BLM bundle, and has made a Library with some of the games that stood out to them in that bundle.

However, the button to the side of the non-free games in the bundle still says "Buy" instead of "install" even though they own it.

![image](https://user-images.githubusercontent.com/9358770/111053588-0199fe80-8433-11eb-8842-aec0742570c2.png)

**Comment by leafo** [comment]
Games part of the BLM bundle must be activated via your browser on your purchase page before they are attached to your account for download. Click the download button on the game on your purchase page and it will activate in your library. Hope that helps.
