### ISSUE TITLE
[download page text] Oculus keys are labelled as Steam keys, confusing players

### ISSUE THREAD

**Issue by juliendorra** [itchio/itch.io#1172]
When a buyer redeems an external Oculus key, the text talks about a Steam key (see screen capture by one of our players)

This confuses our buyers that then contact us by email asking where the Oculus key is.

![steam-instead-of-oculus](https://user-images.githubusercontent.com/109677/111071200-4d04e900-84d5-11eb-9e54-23beace29552.png)

**Comment by leafo** [comment]
Thanks for the report, this has been fixed now. It appears this only happened in the specific case when your account is set up only to sell external keys without files (which is disabled by deafult). Tell me if you encounter any issues.
