### ISSUE TITLE
404 on my page

### ISSUE THREAD

**Issue by puketriton** [itchio/itch.io#1174]
a week ago I started getting messages from people that my itch page with all my projects at puketriton.itch.io is displaying a 404 error page! I was unaware because when i'm logged in I can see everything just fine but its true, when I log out and try to look at it that way I also get the same issue. if there's a specific issue that needs to be handled private I can re-send my email to support

**Comment by leafo** [comment]
There's no account at that URL, are you sure you have the right username?

**Comment by puketriton** [comment]
sorry its luketriton.itch.io !

leaf ***@***.***> ezt írta (időpont: 2021. márc. 21., Vas
19:31):

**Comment by leafo** [comment]
Thanks, I will follow up in email.
