### ISSUE TITLE
Feature suggestion: Let physically rename the uploaded files

### ISSUE THREAD

**Issue by anhel-strauke** [itchio/itch.io#1178]
### Preamble

It's possible now to set the visible file name of the downloadable file at the game editing page. But when user clicks on the download link uploaded file will be downloaded with it's original file name. This behavior is a little bit confusing.

Also sometimes there is a typo in a file name, and for now the only way to fix such typo is to remove misspelled file from the downloads, rename it on the PC and then re-upload it again.

### So the suggestion

This issues can be resolved in one of two ways: either

1. Change the downloading file name automatically to match the visible file name (at least allow it as an option), or
2. Add a button allowing to physically rename uploaded file on the game editing page (next to „Change display name” link, see the screenshot below)

![Screenshot 2021-04-08 144249_edited](https://user-images.githubusercontent.com/469912/113988751-f8f1e800-9879-11eb-8031-3194b251b979.jpg)

### Background

Very often games created on the game jams are uploaded few second before the jam ends, and then the uploading is usually blocked while the voting is going. So there is no way to change the name of the uploaded file even when there is a typo in it's name. The „visible” name of the file can be changed, but the real name of the file remains.

**Comment by leafo** [comment]
The reason why we don't have anything like this is because once the file makes it to our storage backend it's considered read only, it could be cached on many different layers. It's possible we could add something to update the headers on the backend but it may not be propagated instantly due to caching
