### ISSUE TITLE
app is a black screen

### ISSUE THREAD

**Issue by Shiroots** [itchio/itch.io#1192]
tried to uninstall and reinstall, not worked
everytime i open the app he's running but its a black screen.
i dont have antiviruses on my computer
![imagem_2021-05-07_002629](https://user-images.githubusercontent.com/83800036/117393608-e1cf0600-aeca-11eb-977c-172af10a11be.png)

**Comment by leafo** [comment]
When you uninstalled the app did you clear out the app data directory as well?

 (note this will remove all downloaded games, all settings and configuration, etc. Some games may save in their install folder so if you need to backup anything do that first.)

* Windows: `%APPDATA%/itch/`
* Linux: `$XDG_CONFIG/.config/itch/`
* macOS: `~/Library/Application Support/itch/`

**Comment by adrianosingolani** [comment]
It happened to me too and I found an easy solution:

Open the preferences.json file inside ~/Library/Application Support/itch/ folder and change the language to pt-BR instead of pt_BR.
See the paths on @leafo comment if you are not using macOS.

I hope it helps

**Comment by SFNGGL** [comment]
I am having the same issues. It all happened after I innocently clicked a help link or support page, I can't recall. I reinstall it almost daily and it work for some days but then it breaks. It also stops loading anything if I don't have wifi meaning all offline use is gone.
