### ISSUE TITLE
"Roulette Buy"

### ISSUE THREAD

**Issue by primaerfunktion** [itchio/itch.io#12]
I read this on Twitter some time ago. This is not my idea and I don't remember whose it was. But I like it, so: 

You enter into a textfield how much money you want to spend and some random games will be bought for you for that money.

**Comment by quantumproducer** [comment]
+1. I think this would be best for new games to give players a way to support fresh launches

**Comment by lparkermg** [comment]
+1 Maybe have a limit on the timeframe (Like 30 days etc)

**Comment by aaronfranke** [comment]
-1. Itch is a site that serves video games, often played by children. This would be a system similar to gambling, which is not appropriate for children and developing minds.

**Comment by Guard13007** [comment]
I don't think this is something itch.io should natively support, but should be possible to support through API calls. I do not recall what the state of itch.io's API is off the top of my head but I'm pretty sure this can't be done yet/now..

**Comment by aaronfranke** [comment]
An API for making purchases sounds scary. But perhaps there should be an API for "pull up a random game", which the user can then manually purchase (or play in the case of free games) if they like it.

**Comment by Guard13007** [comment]
@aaronfranke Such an API, if implemented, would work in a way that requires the user to confirm a purchase, itch.io's developers are not dumb. :P

**Comment by quantumproducer** [comment]
Randomly buying games is not "gambling".
