### ISSUE TITLE
Error during warm-up

### ISSUE THREAD

**Issue by madprojectsoft** [itchio/itch.io#1211]
Something went wrong

itch-setup, v1.26.0, built on Apr 22 2021 @ 06:18:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://w3g3a5v6.ssl.hwcdn.net/build/396930/1518903-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1623571234&Signature=VpHiMaSOPOcaMQ4%2Fzx%2FhhIHeWWZIE5aMJWUlyqhckwKly9Yw99ks029NHEH5ClcRjBuCRJyo%2F0KQeEf6RWXMkpFyyyQAlh%2F%2FQk0EckOEugVg3riEjQJd6RnVd3Kz7T8G38e39tmSQqm8GhoSNy5%2B7uuYchb5rAdqzcxqoVVl4UxgoymLXta9HIjEXty3lwKH9gwpWaw3lngbQ7nW7fXvpdL%2B%2B2h0qu24NvkY5bjn0H%2BvyhfKY2%2BYIxEfRwyAbwjMo8PJU3vovq7PkRKB58TSzHqbMtED%2F%2BoWSQMlSqDrvECscQS%2BYEZpJTQcSUurfyRrZ078Vr8PiruGkXJ%2BE%2Bh4zg==&hwexp=1623571524&hwsig=8299e9e20cb4628d821550a2cc49f142": dial tcp 10.10.34.35:443: i/o timeout
in conn.tryConnect, while doing GET request
github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:128
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:56
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
in conn.Connect, exhausted retry context
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:88
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
htfs.Open (initial request)
github.com/itchio/httpkit/htfs.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:182
github.com/itchio/httpkit/eos.realOpen
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
while opening remote signature file
Error during warm-up

**Comment by leafo** [comment]
This error is saying that your network connection is unable to download from our CDN. This could either be that our CDN is temporarily down in your region, or there is something about your network connection that is blocked access. (Including, but not limited to restrictions from your service provider, or "security" software installed on your computer).

There's nothing we can really do about this on our end, but hopefully that will point you in the right direction on how to resolve it.
