### ISSUE TITLE
Itch.io Construct 3 HTML Randomly Fails to Load

### ISSUE THREAD

**Issue by saturnproductions1** [itchio/itch.io#1215]
I had a quick question with a game that I am trying to release on itch.io and I'm wondering if anyone has any advice. I'm running into problems when I try to export the game from Construct 3 and play it in itch.io. It works perfectly when playing it through the Construct 3 play tester.

I have downloaded the game for HTML and it is around 50 MB. Itch.io (on Chrome) displays the entire loader and loads to completion, however, the screen then goes black and the game won't start. Using the inspect element tool, I can see lots of red error messages appear in the console section. "Uncaught (in promise) TypeError: Failed to fetch" is the most common error; it occurs hundreds of times each time I try and fail to load the game. "Error loading resource:  TypeError: Failed to fetch" is also very common. The number of errors seems to fluctuate each failure, for example, I had 1433 errors last time, but I've had closer to 600 as well. 

Additionally:
-The game can sometimes load, start, and play properly if I repeatedly reload the page until no red errors occur. 
-The game also works all of the time in an Incognito Tab. In this instance, it provides the message "Failed to register service worker". No red errors occur. I also can't save as I am using Incognito.
-On Safari the game will work all the time from what I can tell, however, memory restrictions prevent it from being a viable option as Safari auto reloads pages that take lots of memory.
-I have tried exporting the game to gamejolt which also doesn't work and many errors occur in the console tab of the inspect element tool.

I'm not very knowledgeable on this subject and I'm wondering if there are any fixes for this problem? I have multiple demos for the game available on itch.io as well, none of which have any errors despite the same export method being used.

**Comment by leafo** [comment]
I believe I helped you through this on the message board, but this issue is due to the code you've uploaded. I don't believe there's anything we can do about it. You will have to research more about the game engine you are using, and pay close attention to what is happening in the browser console to diagnose what's going on.
