### ISSUE TITLE
Typo in "Payouts" page

### ISSUE THREAD

**Issue by npckc** [itchio/itch.io#1219]
On the "Payouts" page (https://itch.io/dashboard/payouts) it says

```Final amount might be alter if any new payments become available, refunds are processed, or account debits are applied.```

It should be

```Final amount might be altered if any new payments become available, refunds are processed, or account debits are applied.```

(Sorry if this is the wrong place to report.)

**Comment by leafo** [comment]
Thanks, will be fixed for next deploy
