### ISSUE TITLE
Images not loading site-wide

### ISSUE THREAD

**Issue by EnderShadow8** [itchio/itch.io#1220]
​I'm using Chrome 89 on Windows. I just noticed today that images on the site aren't loading at all.

![images not loading](https://user-images.githubusercontent.com/69184571/123957942-07662080-d9df-11eb-9cea-a8889a3754b8.png)

In the developer tools, it says:

```
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
```

If I right click on the image symbol and click "open image in new tab", I get another error:

This site can’t provide a secure connection
img.itch.zone sent an invalid response.

Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

I did a bit of research and I think something's wrong with the SSL certificate validation but I'm not sure.

**Comment by leafo** [comment]
Do you have any kind of security software on your computer that might be trying to proxy requests? 

We are experiencing no issues on our end, so it's either software on your computer or your network connection that is interfering with the requests.
