### ISSUE TITLE
Typo in the "Payment Processor" section of the Payments docs/creators/payments page

### ISSUE THREAD

**Issue by OverseeingDev** [itchio/itch.io#1221]
The following sentence is taken verbatim from the website

"For this reason we recommend people minimally sell their work **at to** avoid giving up a large percentage of their earnings to the payment processor."

As you may notice, the sentence seems to be missing a part of the sentence ;)

[Link to itch](https://itch.io/docs/creators/payments#:~:text=For%20this%20reason%20we%20recommend%20people%20minimally%20sell%20their%20work%20at%20to%20avoid%20giving%20up%20a%20large%20percentage%20of%20their%20earnings%20to%20the%20payment%20processor.)

**Comment by leafo** [comment]
Thanks, now fixed
