### ISSUE TITLE
Missing option to set root community to a directory.

### ISSUE THREAD

**Issue by random5703** [itchio/itch.io#1225]
I can't find the option to turn a community into a directory or turn it off.

It might be a recent problem according to this post:  https://itch.io/t/1545703/how-to-create-categories-on-the-discussion-board-of-my-gametool

On my new game I only see this:

![image](https://user-images.githubusercontent.com/82656017/126865952-251dda45-6d14-42bd-9f0e-b4f40ebbe9c8.png)

On an older game, I have subcategories.  It says the following, but I still can't find an option, so I also can't disable it.

![image](https://user-images.githubusercontent.com/82656017/126865936-a6f5c91a-d938-418a-94e7-76087ab88f9d.png)

**Comment by random5703** [comment]
Still unable to locate these options.

**Comment by leafo** [comment]
Sorry for taking so long to respond.  This has been fixed for some time now, you can find the option on the tab to edit the respective community. Tell me if you're still having issues.

Thanks
