### ISSUE TITLE
Retracted

### ISSUE THREAD

**Issue by walking-octopus** [itchio/itch.io#1234]
Deleted

**Comment by Zarkonnen** [comment]
As a developer selling games via itch, I actively do not want itch to support cryptocurrencies.

**Comment by walking-octopus** [comment]
Cryptocurrency payments can provide truly international payments. For many users and developers, it might just be the only option. On a side note, nobody is forcing you to support it, just as any other payment system, it's all up to you.

**Comment by equation-group** [comment]
> As a developer selling games via itch, I actively do not want itch to support cryptocurrencies.

why not, you will still receive money in usd. itch just need to integrate a payment gateway which support cryptocurrency payment like coinpayments, bitpay, etc

**Comment by TangentFoxy** [comment]
@eqn-group I can't put words in someone else's mouth, but I can tell you the most common reasons:
- They are incredibly unstable in value and *existence*.
- They are often used to scam people.
- They are inefficient and directly harmful to the environment.

If anyone would like to learn more about them, Dan Olsen did [an amazing video diving into cryptocurrency](https://www.youtube.com/watch?v=YQ_xWvX1n9g).
