### ISSUE TITLE
Can't save in some DISTRIBUTE sections

### ISSUE THREAD

**Issue by rastersoft** [itchio/itch.io#1236]
I did some changes in the DISTRIBUTE sections, like the color palette or the size for embedding, but there is no "SAVE" button.

**Comment by timkrief** [comment]
The changes you make there only affect the code you'll need to use to embed the game, you don't have to save anything, you just have to copy the code once you're done customizing.

**Comment by rastersoft** [comment]
Ops... Now I see it. Closing this, then. Thanks.
