### ISSUE TITLE
Published GameJam not showing in listings

### ISSUE THREAD

**Issue by timkrief** [itchio/itch.io#1238]
Hi, I recently created a page for my upcoming even, the [Crunchless Challenge](https://itch.io/jam/crunchless-challenge)
While I was editing it, I published it as "unlisted", but now I want it to be listed so I unchecked the "unlisted" option. The issue is, I can't see the jam anywhere:
![image](https://user-images.githubusercontent.com/14089949/132772031-8ddd3c40-958c-439c-a14d-5f8a27ab2588.png)
Even if it's marked as published
![image](https://user-images.githubusercontent.com/14089949/132772060-f516958c-851f-4a37-8dac-c12410d71de7.png)
I can't even see it in the calendar
![image](https://user-images.githubusercontent.com/14089949/132772255-83128e95-8e88-47a4-8889-26a29bfb8e5b.png)
This is the first jam I host so I don't know if this is normal or not.

**Comment by adamazing** [comment]
I'm having a similar problem with my first hosted jam too: [https://itch.io/jam/maori-language-week-2021-jam](https://itch.io/jam/maori-language-week-2021-jam) which starts on Monday 13th.

It's neither present in the calendar nor in the listing:
![image](https://user-images.githubusercontent.com/2782959/132781237-0e33a951-b3ba-45c5-8651-e93dcaf52995.png)

If I filter by jams I've joined, I **_can_** see it in the listing:
![image](https://user-images.githubusercontent.com/2782959/132781291-51f8e5d8-33cc-40e1-83d7-a9c8b78c1193.png)


I did not initially publish the jam as "unlisted" however I did try to save it as unlisted and then as listed again immediately afterwards to see if it resolved the issue.

**Comment by timkrief** [comment]
Oh I'm sorry to hear that, especially since it's so close! Hope it gets fixed quickly for you !

**Comment by timkrief** [comment]
This was solved after sending a mail to the support contact
