### ISSUE TITLE
Requesting uploads with a valid download key for a different API throws a server error

### ISSUE THREAD

**Issue by DragoonAethis** [itchio/itch.io#1242]
For example, trying to `GET https://api.itch.io/games/428139/uploads` (uploads for KIDS) with a `download_key_id` that's for a different app returns `{"errors":["There was a server error"]}` - it's not fatal as uploads in question are still not available, but the error suggests there's something wrong going on :)

This is probably as low priority as it gets, so feel free to close this right away if it's too nitpicky.

**Comment by leafo** [comment]
I did a quick test and I'm seeing a `"invalid download_key_id` error when trying to use an incorrect download key.

If you're still having an issue please leave a comment with more details.

Thanks
