### ISSUE TITLE
Add RSS feed support for specific author

### ISSUE THREAD

**Issue by relma2** [itchio/itch.io#1244]
For example, going to https://itch.io/games/AUTHOR_NAME.xml

Would retrieve an RSS feed of all the games that author has published or can edit.

**Comment by leafo** [comment]
Try this: https://itch.io/games/newest/by-leafo.xml

**Comment by relma2** [comment]
Thank you!
I tested it with other users, like https://itch.io/games/newest/by-aplovestudio.xml
and https://itch.io/games/newest/by-jakefriend.xml
and it works

**Comment by ryliejamesthomas** [comment]
This is great, thanks!

Any chance you could also add a link to the feed in the head section of the profile pages, so that browsers can find it.

EG: on https://leafo.itch.io/:

`<link rel="alternate" type="application/rss+xml" title="Latest games by leafo - itch.io" href="https://itch.io/games/newest/by-leafo.xml">`

**Comment by leafo** [comment]
@ryliejamesthomas So the games shown on the RSS feed of the URL I provided aren't an accurate representation of someone's profile. Any URLs on /games go through our indexing process described here: https://itch.io/docs/creators/getting-indexed

For that reason I don't think it makes sense to make it an alternate link.

**Comment by boozook** [comment]
Also for tags - `https://itch.io/games/newest/tag-TAGNAME.xml`. ❤️‍🔥 Thanks!

**Comment by blawnode** [comment]
Tried using the RSS Feed in Fluent Reader and Firefox's Smart RSS extension, both wouldn't work.
Fluent Reader: `An error has occurred when adding the source.: Error: 403`
I'm new to RSS, but I tried debugging with ChatGPT, which claims the returned .xml file might be problematic.
One of its claims is that the `<channel>` should have a `<description>`:
```"But RSS 2.0 spec strongly expects:
<title> ✅
<link> ✅
<description> ❌ missing"
```
`"This alone fixes many reader failures."`

Am I missing something?

**Comment by boozook** [comment]
@blawnode, yes, it's broken :( and almost any rss-reader tells me that there is error or just invalid feed.

 I subscribed to `https://itch.io/games/newest/tag-playdate.xml` and sadly latest update was three months ago.

<img width="1081" height="485" alt="Image" src="https://github.com/user-attachments/assets/9e1cdd15-9ee5-4e0c-b635-dd2623f544d8" />
