### ISSUE TITLE
impossible, install or start anything game.

### ISSUE THREAD

**Issue by AAide** [itchio/itch.io#1247]
impossible to install games, when I click on install a game, it opens the window where you have to select the game version and the destination, the problem is that there is no game version selected, no matter the games and the 2nd problem is that no games are launched, no matter how much I clicked, it didn't work, and I deleted the folder in appdata, but it doesn't change anything, I reinstall it, its change nothing, I deleted the session and reconnected and it still doesn't change anything! where is the problem ?

**Comment by leafo** [comment]
I'm sorry but there's not enough information here to determine if the problem you are encountering is related to itch.io or a particular game you're trying to run.

As a reminder, we're a platform that hosts over 400k games, and it's the page owner's responsibility to ensure they've uploaded a functioning piece of software. If you have issue with a particular page you can often leave a message on their page.

Thanks
