### ISSUE TITLE
"Buy Now" and "Add to Collection" open in a modal

### ISSUE THREAD

**Issue by MarjaE2** [itchio/itch.io#1248]
And this modal scrolls in front of the rest of the page, and migraine triggers can trigger migraines.

**Comment by leafo** [comment]
Most modals should have a standalone page version, if you right click on the button and select "Open in new tab" you should be able to access the same form in a new page without the project page in the background.

If there's a dialog that doesn't provide this functionality please feel free to open a new ticket so we can track it.

Hope that helps,

Thanks
