### ISSUE TITLE
Issue with Itch.io page

### ISSUE THREAD

**Issue by ForwardAg** [itchio/itch.io#1258]
Hi there,

I wasn’t really sure where else to search for help with this issue; we made our new Itch.io page last week and had good interaction for the first day or so, and now there are a LOT of folks who report that our page gives them a 404 error. We tested this, ourselves, and also receive the same error unless we physically copy and paste the link into our browser. To boot, our page sometimes tells people that it’s under moderator inspection, which, we wouldn’t understand why.

We have contacted Itch.io support several times within the past week, and have had zero responses. Nor, have we found any help with the matter via web search. 

Any help would be absolutely appreciated. It’s a bummer, we were looking forward to using Itch.io as our main outlet for projects.

Thank you,

- Forward Ag

**Comment by leafo** [comment]
Please provide a support ticket ID that you received in in the receipt emails when you contacted out support team and I can take a closer look at the ticket.

Thanks

**Comment by ForwardAg** [comment]
Hey there, the ticket seems to be (98221).

We decided to simply create a new page and replace our old page, as we were
losing interaction and it was upsetting our followers. The new page works
wonderfully, however.

Thank you
