### ISSUE TITLE
Processing

### ISSUE THREAD

**Issue by Starhelper11** [itchio/itch.io#1261]
Everytime I send a Comment on Devlogs or Games it says​

Please check the information you provided

We are unable to proccess your request at this time
I want to s​end stuff though! How do i fix it? It's not even just today it happens everytime since i commented on a game page.

**Comment by Raging0Moose** [comment]
I'm having the same issue even trying to submit the issue to the community page on the itch.io website gives the same response
![itch ioissue](https://user-images.githubusercontent.com/35090492/161576952-db1eaa4f-d431-4652-a3f8-1e8863bcb9ac.png)
![itch ioissue2](https://user-images.githubusercontent.com/35090492/161576995-bf612d7e-5997-4e39-aaf2-98c27f5ecf66.png)

**Comment by leafo** [comment]
Your account may be suspended for violating our [community guidelines](https://itch.io/docs/general/community-rules) or [terms of service](https://itch.io/docs/legal/terms).

You will have to [contact support](https://itch.io/support) for account specific help, we can not provide that assistance here in the issues tracker.
