### ISSUE TITLE
My Games are not showing up in collection

### ISSUE THREAD

**Issue by MyBroMonokuma** [itchio/itch.io#1273]
I've been adding my games to my collection for a while now, but none of them seem to show up when I look in the folder.

When I add games to my collection, it says that there's 7 games in it. However, when I check, I can none of them. Is there anything I can do to fix this?

https://itch.io/c/2004930/charon-collection-2013-2021

please fix thiiiis

**Comment by leafo** [comment]
Please sent you an email as we sent you a notice about distributing other people's work on your account. Your account and the pages in question are suspended. We do not discuss account restrictions and suspensions on the issues tracker, if you want to follow up you must reply in the support email.

Thanks

**Comment by MyBroMonokuma** [comment]
So If I delete the games and only upload my work....I can have my account
back?

**Comment by MyBroMonokuma** [comment]
So if I delete The games...I can have my account back? If yes, I will
delete them and start uploading only my work.

**Comment by MyBroMonokuma** [comment]
So if I delete The games...I can have my account back? If yes, I will
delete them and start uploading only my work.
If there are terms and conditions, please let me know. I will react as soon
as possible. Also I'm sorry for uploading other people's work. And can I
ask? If I see other accounts uploading other people's games, do I have to
report them? Cause I've seen some people do that. Alright, I'll just wait
for your reply.
