### ISSUE TITLE
my itch page showing 404 

### ISSUE THREAD

**Issue by PrakharDoneria** [itchio/itch.io#1276]
I am a itch.io user and from the last day I am facing a issue with my itch.io page 
![chrome_screenshot_1642478459634](https://user-images.githubusercontent.com/92568876/149868749-f4f8ccc0-0133-437b-b88c-393bd2cfe524.png)
Page link: [https://protecgames.itch.io/](https://protecgames.itch.io/) 

It shows this when I use without login

**Comment by leafo** [comment]
We don't discuss account restrictions on the issue tracker here. Our records show we notified you via a support email about the status of your account. You will have to follow up there.
