### ISSUE TITLE
Game Page refuses to display to all non developers

### ISSUE THREAD

**Issue by AzuranSHadow** [itchio/itch.io#1286]
Hi there. The game page for the game I develop (MSM: The Lost Landscapes) no longer displays for any users. People have been unable to download the game. If any of our three developers logs into their account, we are able to access the page. 

For now we have worked around this issue by using a download key link and sending that to all people as it works.

**Comment by leafo** [comment]
Hello,

We can only process requests like via our support system: https://itch.io/support

Your page may have been suspended due to using the intellectual property of others, which is against our terms of service.

Thanks
