### ISSUE TITLE
can't add screenshots to uploading project

### ISSUE THREAD

**Issue by stromperton** [itchio/itch.io#1287]
I try to add screenshots, but it does not visible, and if i save project, i see this error. However 1 hour ago all worked........

![image](https://user-images.githubusercontent.com/29544738/155285663-b6382510-5f43-4a9b-8164-11a4a47a1ac8.png)

![image](https://user-images.githubusercontent.com/29544738/155285710-26f2413e-6596-443d-88b9-2ede0000d39b.png)

**when image loading i see code labels**
![image](https://user-images.githubusercontent.com/29544738/155286126-1485eab0-c1ca-4526-8d46-c2fb3d724633.png)

**Comment by leafo** [comment]
Are you using any browser extensions that might mess with the content of the page. This include tools that automatically translate the page.

**Comment by stromperton** [comment]
> Are you using any browser extensions that might mess with the content of the page? This include tools that automatically translate the page.

ohh thank u!! it is be conflict with Simple Translate extension
