### ISSUE TITLE
The seller can't accept PayPal payments at this time

### ISSUE THREAD

**Issue by gh89275** [itchio/itch.io#1298]
Try to buy something using Paypal right now:

> The seller can't accept PayPal payments at this time. Please try again later or return to the seller and choose another way to pay.

![Screen Shot 2022-03-20 at 1 25 29 AM](https://user-images.githubusercontent.com/26887375/159125086-80ece2c1-6aa0-4731-847b-72d2def892ba.png)

**Comment by leafo** [comment]
Sorry for the issue, we're aware of the issue and working with our PayPal rep to get it resolved.

In the meantime we've disabled PayPal payments on pages that are affected by this issue. Only paying via credit card will be available at this time.

Thanks

**Comment by gh89275** [comment]
@leafo may I ask what is the criterion for pages being affected?

**Comment by leafo** [comment]
> @leafo may I ask what is the criterion for pages being affected?

Accounts that are using our Payouts system currently can not accept PayPal payments. There's not much we can do right now since it's the weekend (even it looks like the issues started on the weekend), but hoping it can get resolved by early this week.

**Comment by gh89275** [comment]
Fixed?

**Comment by leafo** [comment]
This should be fixed now, thanks for your patience.
