### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by kalfyra** [itchio/itch.io#1300]
Hi, i did sent my update tax information, I'm waiting for my pending payment to receive needing to pay my bills I hope they can resolve soon.

**Comment by leafo** [comment]
This is not an issue appropriate for our GitHub issues tracker. You must [contact support](https://itch.io/support) to handle private matters for your account.

Keep in mind, generally for issues regarding payments and payouts: We will contact you if there is an issue. Contacting us even though we're operating normally on your account will likely not receive a response, as we are more prioritized on processing the respective payout.

If you think there is a issue that needs response then you can reply to me with the support ticket ID.

Thanks
