### ISSUE TITLE
Itch application does not find game files of Exile’s Journey.

### ISSUE THREAD

**Issue by mcOz1** [itchio/itch.io#1306]
It finds only guide but not the game files.

https://moonphaseproductions.itch.io/exiles-journey
![1](https://user-images.githubusercontent.com/71328023/161418632-6642fe33-5a6d-4af2-8d30-bfbbff4babef.png)
![2](https://user-images.githubusercontent.com/71328023/161418635-b5042390-f8c3-476b-9c4e-63c20b2170d4.png)

**Comment by leafo** [comment]
The developer will need to mark the files they have uploaded with the platforms (Windows, macOS, Linux, etc.) that they support in order for the app to install the game.
