### ISSUE TITLE
```

### ISSUE THREAD

**Issue by metinoy** [itchio/itch.io#1332]
```
2017-12-25 04:56:44> IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\Sammi\AppData\Local\itch\app-23.6.0\itch.exe' is denied.
```

this seems like the relevant log line.

I'd check, in this order:

  * whether the app is still running (Ctrl+Shift+Esc opens the windows Task Manager, in `Details` tab, look for something named `itch.exe`, right click -> `End Task`, then try to install again.)
  * whether an Antivirus software is preventing write access to `C:\Users\Sammi\AppData\Local\itch\app-23.6.0\itch.exe`
  * whether uninstalling it first (you won't lose settings) from the Control Panel and *then* installing it works.

_Originally posted by @fasterthanlime in https://github.com/itchio/itch.io/issues/771#issuecomment-353873305_

**Comment by leafo** [comment]
You seem like some kind of spammer?
