### ISSUE TITLE
Download files without JavaScripts if the price is $0.00

### ISSUE THREAD

**Issue by zzo38** [itchio/itch.io#1335]
I have the request to allow to download the file without JavaScripts (using e.g. curl, wget) if the minimum price is $0.00, and to only require the JavaScripts if a payment is required.

It says "No thanks, just take me to the downloads" but it does not work; it is doing nothing.

**Comment by leafo** [comment]
Unfortunately we will not be providing this. Bandwidth is our largest cost.
