### ISSUE TITLE
MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by kedinik** [itchio/itch.io#1338]
Hello,

I have discovered what appears to be a general technical problem, where a self-signed certificate error within the itch.io site architecture can break embedded HTML5 games.

Purely as an example of what appears to be a general problem within itch.io, please consider my game Hotline Maui. For the last year or so, it had been running fine as an embedded HTML5 game. It is accessible at https://kedinik.itch.io/hotline-maui with the password 1234.

When I tried to run the game in Firefox today, it resulted in the "Potential Security Issue" of MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT, and so the browser refused to continue running the embedded game. Opening the page with Edge resulted in a similar error.

**Comment by kedinik** [comment]
Somehow this cleared up. I don't understand why but I'm no longer seeing the error.

**Comment by leafo** [comment]
Haven't seen this error before. None of our certs on the html cdn have changed recently. Possibly a client side issue?

**Comment by kedinik** [comment]
I think it probably was something on my end, thank you.
