### ISSUE TITLE
Feature Request: Automatic Updates

### ISSUE THREAD

**Issue by Smurf999** [itchio/itch.io#136]
I'd love it if there would be a way for logged in users to receive notifications of an update or even have their app updated automatically.

**Comment by Dave-Parry** [comment]
I think this would be a good idea also.

**Comment by lparkermg** [comment]
That would be really awesome. Having an update notification could be pretty straight forward to do, but I think automatic updates would depend on how the developer has made their game/app.

**Comment by leafo** [comment]
The app currently automatically updates, and automatically updates games.
The website will sent out an email to owners when new files for a game are uploaded.

Tell me if there's anything missing.

**Comment by Guard13007** [comment]
To be clear, replacing a file with a new version triggers the same notification, right?
