### ISSUE TITLE
Game not uploading

### ISSUE THREAD

**Issue by diffenyy** [itchio/itch.io#1362]
I have been trying to upload a HTML file for a game a created but itch.io is telling me that "You already have a game on your account with that URL", when this would be my first game. Does anyone know how to fix this? I tried re-doing everything like creating the project page again and download the HTML file again, but nothing is working.

**Comment by leafo** [comment]
The error message is accurate, so you may have created a page without realizing it and potentially hit the back button and brought up the game creation page again. I suggest returning to your dashboard to find the page you had already saved and work from there.
