### ISSUE TITLE
Expired SSL site-wide 

### ISSUE THREAD

**Issue by SleepyPeko** [itchio/itch.io#1365]
Hello, i would like to report that your website SSL cert expired today and when loading the website it shows me this:
![image](https://user-images.githubusercontent.com/25424568/188523319-6e01455a-7fc2-4126-a115-8f595d2028f5.png)
![image](https://user-images.githubusercontent.com/25424568/188523373-72347165-e9b8-4618-8a8d-7da35cc03d6a.png)
![image](https://user-images.githubusercontent.com/25424568/188523391-cc687cbd-f44c-41d3-b2bc-17638ee7d530.png)

And on The itch.io app when loading a new tab this shows up:
![image](https://user-images.githubusercontent.com/25424568/188523556-f6401a27-42d0-44ff-99db-ada396d9f9ec.png)

**Comment by SleepyPeko** [comment]
Also checked https://broth.itch.ovh/ website works fine but when checking the Package links throws out the same error

> Get "https://api.itch.io/games/239683/uploads": x509: certificate has expired or is not yet valid: current time 2022-09-06T00:41:07Z is after 2022-09-05T23:59:59Z

**Comment by SleepyPeko** [comment]
https://git.itch.ovh/itchio/itch/builds is down for some unknown reason

**Comment by SleepyPeko** [comment]
Seems to be working again and the git is still down.

**Comment by leafo** [comment]
git.itch.ovh is retired. Everything else is fully functional

**Comment by SleepyPeko** [comment]
> git.itch.ovh is retired. Everything else is fully functional

oh, i see. Thanks for the reply.
