### ISSUE TITLE
Clear/delete button on notification page is ambiguous/confusing

### ISSUE THREAD

**Issue by eladnarra** [itchio/itch.io#1367]
It's possible to filter the view on the notifications page (to things like Sales, Replies, Follows, etc). Once you do, a link appears at the end - it has a trash can and says "Clear." 

It's not immediately obvious what this clears - does it clear the filter, or the notifications in that filter view? I figured it out pretty quickly by looking at the code, but even just "Clear Filter" or "Remove Filter" would help a lot, especially for cognitive accessibility. 

Or have an option at the start for "All"? (Not sure which is better UX-wise.)

![Screenshot from the notifications page showing the Clear button ](https://user-images.githubusercontent.com/50590262/189784450-e3ddbd00-310e-4d3d-a438-5bbe4680471b.png)

**Comment by leafo** [comment]
The filters on this page have been updated, there is no longer a clear button
