### ISSUE TITLE
https://itch.io/support email button does nothing.

### ISSUE THREAD

**Issue by Mechputer** [itchio/itch.io#1370]
Went to the support page to tell you about a different issue, and the email button doesn't do anything. It doesn't even copy the email address to your clipboard.

Windows 10 Home 21H1
Chrome Version 105.0.5195.126 (Official Build) (64-bit)

**Comment by leafo** [comment]
It's a standard `mailto:` protocol link. If the button does nothing then your computer has been misconfigured in some way, likely from selecting an option that is invalid or no longer available on your computer when previously clicking a link like that. Helping you fix that is outside the scope of our issues tracker. Feel free to manually type in the address displayed directly into your email client if you need to contact us in the meantime.

Thanks
