### ISSUE TITLE
https://itch.io/ unable to close the spotlight window.

### ISSUE THREAD

**Issue by Mechputer** [itchio/itch.io#1371]
On the main page, the window that pops up to showcase a game or app on the site isn't closable. The x in the top right corner doesn't do anything.

Windows 10 Home 21H1
Chrome Version 105.0.5195.126 (Official Build) (64-bit)
Chrome Version 105.0.5195.127 (Official Build) (64-bit)
Firefox 103.0 (64-bit)
Firefox 104.0.2 (64-bit)

**Comment by VirtualNomad19** [comment]
Same here.

WIN 10:
- Microsoft Edge 107.0.1418.26 (Official build) (64-bit)

Android:
- Chrome Version 107.0.5304.91

**Comment by 00001H** [comment]
Same here.


Technical note:
the "x" button has a `data-url` for some reason, and there doesn't seem to be any code/actions associated with the button.

***
To the itch.io team:
Should be an easy HTML fix. Add an id for example `id=blahblahblah` to the "spotlight box" and set the button to be `onclick="javascrpt: document.getElementById('blahblahblah').style.display='none'"`
***
