### ISSUE TITLE
Not allowing access to school site

### ISSUE THREAD

**Issue by Infinite-Gits** [itchio/itch.io#1373]
Im trying to embed a file on our school site but i just get the error message, that itch.io didnt allow a connection
Im not sure if it's an issue with the project settings or the website but I think I set all settings to the right options
![zuujzzju](https://user-images.githubusercontent.com/115728305/195648198-6bd8621a-70fe-4b24-b049-dd6b9ac32106.JPG)

**Comment by leafo** [comment]
It's hard to tell what's going on just from your screenshot, but it's likely either you embedded invalid code for distribution online, or your school is blocking the connection.

If other people's projects are loading fine then it's unlikely your network connection is blocked.

I recommend going over this guide for distributing HTML5 games to ensure that you didn't miss anything obvious: https://itch.io/docs/creators/html5
