### ISSUE TITLE
I bought a game that didn't even work 

### ISSUE THREAD

**Issue by Pandabro00** [itchio/itch.io#1374]
The game is called Wanderer Game and I needed to pay in order to play the newest updates, but when I payed for it it didn't even show new content or the slightest difference, I am a struggling collage student who needs to make payments that work or else I am wasting money that I set aside to keep me entertained when I could have spent it on my loans, so if I could get a refund I would be very thankful and It would mean the world

**Comment by leafo** [comment]
Customer support is available here: https://itch.io/support

Thanks
