### ISSUE TITLE
CM closes directly

### ISSUE THREAD

**Issue by burashed1987** [itchio/itch.io#1378]
CM closes directly when i start it ,,, stays like for 5 seconds and it closes !! any idea whats goin on ?? i tried re installing + ending tasks through task mngr + process hacker .... didnt work

**Comment by harleyzhao** [comment]
i have exactly the same problem with 5.0 version

**Comment by leafo** [comment]
This doesn't appear to be related to itch.io. If it is, please provide more information. We do not know what "CM" is.

As a reminder itchio hosts over 500k games. If you need help with a particular game you're probably going to have to find a way to reach out to the author of the game. This issues tracker is for issues relating to itch.io directly.
