### ISSUE TITLE
slow downloads with all games

### ISSUE THREAD

**Issue by smeveriss** [itchio/itch.io#1386]
Since start of october I have noticed downloads really slow of your cloud servers.
Never used to be this way.
Average speeds are 9kb and lower.
I have checked my connection and well nothing else is slow in fact my current connection speed is 260mbps down by 80mbps up.
Sometimes if I download from the website in the morning its faster but congestion seems to bog down your secure servers to the extent I just can't download anything.
I like your site, I haven't used the client but being a blind user, I'd use your system over steam any day.
Steam can be used but valve doesn't give a damn about access so your stuff is really good.
Its nice to use its nice to download with but speeds well.
I have tried on at least 3 systems at different locations and I have firefox, edge and chrome all of latest versions and yeah things just don't go fast at all.
I'm sure the servers used are just conjested maybe there should be an option to use different servers or directly from itch instead of the cloud hosted servers.
I can login and go do things just fine so the site is fine.

**Comment by leafo** [comment]
Can you share what region of the world you are in?

All downloads are served through our CDN, which has points of presence globally. Sometimes they have reliability issues on some of their edge nodes which may cause degraded performance in some regions.
