### ISSUE TITLE
Publishing a game

### ISSUE THREAD

**Issue by SenatorInPower** [itchio/itch.io#1387]
I used the window to upload the project, do I understand correctly that I need to upload the zip file there?
When will it be available for my personal download if the page is still in draft?

![Screenshot_32](https://user-images.githubusercontent.com/66920423/200777057-f1990287-4d68-48cf-82e3-1ed708e0ccfd.png)

**Comment by dos1** [comment]
This is not a support forum, a better place for such questions would be at https://itch.io/board/10023/questions-support
