### ISSUE TITLE
Host HTML5 game that makes requests to an API with CORS active

### ISSUE THREAD

**Issue by lpares12** [itchio/itch.io#1412]
I have exported a Godot game to HTML5 and uploaded to Itch.io.

The game works correctly. But there is one level where I need to make some requests to: `https://jisho.org/api/v1/search/words?keyword=%23common`, and that fails with a CORS error. This does not happen with other platforms or with a desktop export, so my only guess is that HTML5 hosted itch.io games go through some proxy, and `jisho.org` has CORS enabled?

Is there any way to avoid this issue or should I host the game somewhere else?

**Comment by leafo** [comment]
Our HTML CDN does not go through a proxy and I see no CORS headers on jisho.org.

We add specific headers to the HTML files for browser games that are necessary for full support for advanced game engines that use SharedArrayBuffer. This pages describes the headers placed on the CDN: https://itch.io/t/2025776/experimental-sharedarraybuffer-support (Note that they can not be turned off regardless of the setting on your game's dashboard)

If the API from jisho.org is designed to be requested via JavaScript then it should have the following header added: `Access-Control-Allow-Origin: *`

**Comment by lpares12** [comment]
You are right, sorry for the noise.

It's just the HTTP client used in the other platforms does not really care about CORS and accepts the request.
