### ISSUE TITLE
itch.io press kit / media kit

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#142]
People need to know where to find high-res assets they can use on their websites/articles/internet scrapbooks.

In the meantime:

## Logos

![Colorful logo](http://itch.io/static/images/itchio-450.png)

![Black logo](http://itch.io/static/images/itchio-black.png)

[SVG Logo](http://itch.io/static/images/itchio-black.svg)

## Badges

![Colorful badge](http://i.imgur.com/32JwnOG.png)

![B&W badge](http://i.imgur.com/ey1xcYM.png)

## Various

![](http://itch.io/static/images/stock.jpg)

## Other

This repository also contains [a few images](https://github.com/leafo/itch.io/tree/master/logos).

**Comment by Natman64** [comment]
This seems like something I could maybe help out with using presskit() if there's no one more qualified planning to do it in the near future? I'd love to give back to the site in some small way.

**Comment by leafo** [comment]
We have an official press kit here now: https://itch.io/press-kit/

**Comment by stolk** [comment]
The logo.zip file from the press-kit is missing the "Available on itch.io" graphic.
