### ISSUE TITLE
On 4/22/2023 at 5:00PM exactly, the itch.io analytics page stopped recording page views.

### ISSUE THREAD

**Issue by story-anon** [itchio/itch.io#1433]
![itch analytics drop off](https://user-images.githubusercontent.com/72540208/233821914-2b9f1a72-c140-4a90-9c14-37a76f178dbb.png)

At 5:00PM PST, the Analytics section for my Itch.io page (https://story-anon.itch.io/out-of-touch) stopped recording page views entirely, and has remained at 0 views for the past 5 hours and 45 minutes.

Downloads are still being recorded and at the same rate that they have been since yesterday. New ratings, comments and other peripheral metrics such as Discord joins have also been continuing at regular levels. Furthermore, the game appears to still be in the same rankings on all its popular tags and visible to all (10+) people I've asked to look.

The only conclusion I can draw is that the views counter for the Analytics section is currently broken. I saw someone on the Itch.io Discord post in the meta channel that he was experiencing the exact same problem as well.

**Comment by bohohon** [comment]
Exactly the same situation.
My Itch.io page (https://bohohon.itch.io/deep-vault-69)
![Screenshot_2](https://user-images.githubusercontent.com/126898722/233822598-7a98e333-5de9-44c9-8459-e4043261ff67.png)

**Comment by leafo** [comment]
Our analytics ingesting system was delayed in processing new data. The issue should be resolved and all pending data is now distributed.
