### ISSUE TITLE
ABUSE REPORT - Hacked game compromising Discord/Web based systems

### ISSUE THREAD

**Issue by STrRedWolf** [itchio/itch.io#1437]
https://1039lucas.itch.io/sweet-volley-high is being used to compromise Discord and artwork communities such as FurAffinity.  Please take down ASAP!

**Comment by leafo** [comment]
The account has been suspended. It looks like the owner's account was hacked. Please keep in mind we have a report tool on the bottom of project pages where you can report suspicious activity.

Thanks

**Comment by STrRedWolf** [comment]
Thanks.  I couldn't find a general abuse reporting page (which I do recommend).
