### ISSUE TITLE
Random Avatar Change and no way to change it back

### ISSUE THREAD

**Issue by abysssal** [itchio/itch.io#1441]
I was on my account page adding a website and after I added that website, my avatar/profile picture just changed out of no where. I hadn't changed it previously or anything, so it took me a moment to find it. Whenever I found it, it was bugged and didn't show the change avatar picture. So I reloaded, and it was the same. I kept reloading but it didn't work.
![image_2023-05-15_200219215](https://github.com/itchio/itch.io/assets/83674439/4220b40a-d307-4067-9c3b-fba3b55f6493)

**Comment by Poishi** [comment]
Not an individual problem, same thing happening to my account
