### ISSUE TITLE
(sec) saw some token in file download

### ISSUE THREAD

**Issue by hacknorris-code** [itchio/itch.io#1458]
this url i got after downloading MY OWN (from project settings page) game/tool/etc IMAGE data: 
https://commondatastorage.googleapis.com/itchio/upload2/game/2123820/8131108?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1687187826&Signature=Pn9gHV0FEC8ezcCcPzdugCiv79IsMTxCiQZPPKw%2FJVrdJJo5AP3qz5Uh5qN19HaSj8IN4aJtvQLyKkm6rQ0FGYasRoPEdaLP4h%2BZ4hsl1xBWoJMqp4QRKjNTCW5VWzxxwzMeirfDoTsC37FLkALmZXyc4kBt3wSWf4%2B1TH3NEPEYPXhybtCakFfio4ZImvfn3StXLQzKS9v1A8rQebU0L548XDlauCLedRjIrYb%2FcG3ig23NE1IAsf%2FjW1xrCMwofXEO7wpK0pjTE8ZTctZ86t9LD2tzplaw3duQFgHyNbGXu2BL6G1GhU6Hk0akIDTxNRnXDZnlo2V4fFkvSnrLoQ==
i just think it contains tokens and all the rest of google cloud used to host itchio...
(yes, putting it here just because its nowhere said where to put security issues...)

**Comment by leafo** [comment]
These are signed URLs with expatriation dates that only grant access to a specific file or a few seconds. No security issue here.
