### ISSUE TITLE
No game download link?

### ISSUE THREAD

**Issue by Charliebeans69** [itchio/itch.io#1470]
I've bought a game with no download link at all

**Comment by Charliebeans69** [comment]
I do not have my download link at all, it's so weird

**Comment by leafo** [comment]
Please check this page here: https://itch.io/docs/buying/already-bought

If you are still having trouble you will need to contact support so they can look up your info and payment: https://itch.io/support

You can reply to me here with your support ticket ID and I can check on it immediately.

Thanks

**Comment by Charliebeans69** [comment]
#1152-7710  I have no link only received the receipt for the game
-------- Original message --------From: leaf ***@***.***> Date: 7/19/23  1:58 PM  (GMT-05:00) To: "itchio/itch.io" ***@***.***> Cc: Charliebeans69 ***@***.***>, Author ***@***.***> Subject: Re: [itchio/itch.io] No game download link? (Issue #1470) 
Please check this page here: https://itch.io/docs/buying/already-bought
If you are still having trouble you will need to contact support so they can look up your info and payment: https://itch.io/support
You can reply to me here with your support ticket ID and I can check on it immediately.
Thanks

**Comment by Charliebeans69** [comment]
-------- Original message --------From: ***@***.*** Date: 7/22/23  12:49 PM  (GMT-05:00) To: gwenbishop712 ***@***.***> Subject: [Request received]   #1152-7710 I do not have my links for the price of flesh, I've bought the game but I am having trouble getting the links for it, it will not open to the links on my receipt.
  
    ##- Please type your reply above this line -##
    Your request (162888) has been received and is being reviewed by our support staff.To add additional comments, reply to this email.
  
  
    This email is a service from itch.io. Delivered by Zendesk
  
[7GP93V-56RWX]
