### ISSUE TITLE
Web GL Zip file size

### ISSUE THREAD

**Issue by GuapoMan0** [itchio/itch.io#1473]
Hello, I can't make a new version of my game work in the online mode; is there a message saying that my zip file is too big for the site; what is the file size limit, and can I do anything to increase that limit?

The size of my zip file is 213 Mb and when extracted 214 Mb. It is a Web GL Unity project (HTML5 game).

**Comment by leafo** [comment]
https://itch.io/docs/creators/html5#zip-file-requirements

> Why do we have limits? Although many game engines allow you to export anything as an HTML5 project, often you need to consider what the user experience of playing the game will be like. You can think of an HTML5 project like a website: many of the same performance optimization recommendations still apply. We have these default limits to encourage developers to consider how their games are distributed, especially since it’s so easy these days to drop in prefab resources from asset-stores that significantly increase the download size for the game.
