### ISSUE TITLE
Typos in the docs

### ISSUE THREAD

**Issue by jooroh** [itchio/itch.io#1474]
I've found a couple typos while reading the docs. I'm not a native english speaker, so i might have misinterpreted some.
All of them are in the creator section of the docs.
https://github.com/itchio/itch.io/blob/master/docs/creators/

In "patreon.md" under "Managing access":
- You can view and manage ---the these--- keys by ---locatin--- the group on your project's download keys page under Edit » Distribute » Download Keys.
- If you revoke a key for a patron, the same patron will not be able to generate ---anouther--- access key.

In "how-buying-works.md" under "The purchase dialog":
- The purchase dialog is opened ---buy--- clicking the Buy Now button on the game's page below the description.

In "faq.md" the header:
---Can share--- the information itch.io collects about my buyers publicly or with third parties?

In "exclusive-content.md" under "How you can use rewards":
- Another use ---cause--- for rewards is selling physical goods along with your digital content.

**Comment by leafo** [comment]
Thanks for all the reports. All of these examples should be fixed now.
