### ISSUE TITLE
Games Bundle i bought has disappeared and the creator has deleted their account.

### ISSUE THREAD

**Issue by Crazymanvon** [itchio/itch.io#1482]
I just bought a game bundle for 14 dollars a few days ago and i went to go download and paly the games and the download link doesnt work. I go to the creator's page and the creator doesn't exist anymore. Can i get a refund for this bundle since i can no longer play a thing?

**Comment by leafo** [comment]
Did you contact support? https://itch.io/support

We can't help you here unless we have a way to reference your ticket ID. Please make sure you've first contacted support, and if you still need help you can reply to me here with your Support Ticket ID that comes in the receipt email.

Thanks
