### ISSUE TITLE
"This page isn't available right now" - My profile page doesn't load 

### ISSUE THREAD

**Issue by Axel0689** [itchio/itch.io#1483]
I have been having this problem for several days. I have contacted support but so far it gives me no sign of life. So here I am. 

My personal page is not loading. It comes out like this:  **This page isn't available right now**

![pV52By2Jeh](https://github.com/itchio/itch.io/assets/33706352/125f8a97-c5fd-4bf7-80fe-23147bd42ea8)

 I do not understand why. I would like to please solve this. Thank you

**Comment by leafo** [comment]
You'll need to either share the link to the page or your support ticket ID if you want someone to look up the problem. 

Thanks

**Comment by Axel0689** [comment]
Ok, my link page is : [https://axel0689.itch.io/](https://axel0689.itch.io/) and my ID Ticket is **168302**

**Comment by leafo** [comment]
Sorry for the delay in getting back to you.

Our automated system flags pages based on certain criteria, such as unusual activity or content patterns, to prevent abuse. This can occasionally affect legitimate creators if their page activities or contents match these criteria. Your page should now be fully functional.
