### ISSUE TITLE
WCs Brambleclan’s Future 

### ISSUE THREAD

**Issue by Catti7264** [itchio/itch.io#1485]
https://scratch.mit.edu/projects/847976138/ How can I upload this anyone

**Comment by leafo** [comment]
This is not support for individual games hosted on itch.io, as itch.io hosts over 1 million projects. 

If you're having an issue, I recommend looking for a community or communication channel directly on the developers page.

If you are a paying customer, then you can contact support with your payment details and we can get you in touch with the developer if necessary.
