### ISSUE TITLE
Cannot Download games and images are not showing along with attempting to download the Itch.io desktop app keeps crashing when attempting to download

### ISSUE THREAD

**Issue by NexusPrime24** [itchio/itch.io#1504]
Recently, when I started to download some games in my library the images are not showing and I am unable to download them I even turned off my adblockers and even tried using different browsers that don't have adblockers and even then the issue is still happening, I even tried to download the desktop app but it keeps crashing (2nd image is the result) and even tried downloading in Epic Games.

![Itch io 1](https://github.com/itchio/itch.io/assets/136771523/65430b73-0e05-43de-a446-0ff84ecc2c83)
![Itch io 2](https://github.com/itchio/itch.io/assets/136771523/68795fc8-a439-433c-ab8c-e127406a615d)
![Itch io 3](https://github.com/itchio/itch.io/assets/136771523/b501d3a3-b621-45e5-a430-9447570a07af)
![Itch io 4](https://github.com/itchio/itch.io/assets/136771523/4e17f894-a605-4edf-b47e-5d301b136e20)
![Itch io 5](https://github.com/itchio/itch.io/assets/136771523/ff5617f0-072f-41ee-8156-bb43409d3fa0)
![Itch io 6](https://github.com/itchio/itch.io/assets/136771523/73eeb433-299a-4eac-903e-ff065b138983)
![Itch io 7](https://github.com/itchio/itch.io/assets/136771523/0d00a55c-101c-4adf-90bf-d1274f404282)

**Comment by leafo** [comment]
Most likely temporary network outage. Comment if still experiencing issue.

**Comment by NexusPrime24** [comment]
It seems to have been fixed around a few weeks later after that was posted not sure how but it was fixed.
