### ISSUE TITLE
FAILED PURCHASE why

### ISSUE THREAD

**Issue by NumiiStyx** [itchio/itch.io#1507]
I purchased a game for 20 bucks, itch took my money and it continues to ask me to purchase the game. I went to purchase the game with 50.36 bucks in my account and now have 30.36 exactly, so it very clearly took the cash for the money and just never gave it?? is there some kinda way I can get the game or a refund or am i just screwed

**Comment by leafo** [comment]
Did you contact support? If you're unable to access something you've purchased then our support team is happy to process a refund of you. https://itch.io/support

If you reply to me here with your support ticket ID that you get in the receipt email I can expedite the processing.

Thanks
