### ISSUE TITLE
2FA Locked Account Deletion

### ISSUE THREAD

**Issue by KalinTDM-Playz** [itchio/itch.io#1511]
I don't remember adding 2FA to my account is there any way I can Delete my Account?

**Comment by KalinTDM-Playz** [comment]
![Screenshot_1](https://github.com/itchio/itch.io/assets/58379398/ff37e4a1-4481-4e7a-a755-e94555e0ea41)

**Comment by leafo** [comment]
You have to contact support for account issues <https://itch.io/support>
