### ISSUE TITLE
/wharf/builds: Account limit reached, contact support

### ISSUE THREAD

**Issue by furrz** [itchio/itch.io#1513]
I just created a new project (currently unlisted) on itch.io and installed butler v15.21.0 to try and publish a build of my game. I am getting an API error in response, suggesting that my itch account has hit some sort of limit.
I've successfully logged in with `butler login`, and tried logout and re-login with no change.
I'm not sure how this is possible, as I only have two projects, the new one which is empty and unlisted, and the previous project only has a single, tiny file uploaded to it.

```
rh-builds % butler push my-windows-build-folder myusername/project-name:win --userversion 0.0.4
creating build on remote server: itch.io API error (400): /wharf/builds: Account limit reached, contact support
```

**Comment by leafo** [comment]
There was a temporary bug that was showing this message to users by accident. It should have been long fixed so I'm going to go ahead and close this issue.
