### ISSUE TITLE
I made a purchase and did not receive the product on Itch.io.

### ISSUE THREAD

**Issue by octeicios** [itchio/itch.io#1532]
I went to buy the game Buckshot Roulette and paid with a credit card, but the page got stuck. Then, I went to my purchases in my account and there was nothing there. I went to the support tab on the website and clicked to send an email to resend my purchase links, but nothing arrived. I need help.

**Comment by leafo** [comment]
This is a payment related issue, you will need to resolve the problem through customer support: https://itch.io/support

Thanks
