### ISSUE TITLE
Itch.io's mail service cannot handle certain email adresses

### ISSUE THREAD

**Issue by madprogramer** [itchio/itch.io#1538]
**Describe the bug**
itch.io fails to send mails to certain email adresses it cannot parse. Strangely, subscriptions work just fine.

**To Reproduce**
1. Register an e-mail address with the characters `--`, for example, `I--like--trains@gmail.com`.
2. itch.io will fail to send the confirmation e-mail.

**Expected behavior**
Itch.io should be able to send an e-mail for account confirmations and 2FA tokens.

**Additional context**
I am locked out of our team account `efegilller--team AT outlook DOT com`, due to never being able to receive the 2FA token. This has been a bug for 3 years and support would usually help us but they have ghosted me for almost a week now.

Strangely, subscriptions work just fine. Our inbox is full of Winter Sale offers from itch, but no 2FA tokens.

**Comment by leafo** [comment]
Can you provide your support ticket ID send from the email that owns the account so we can look it up. There are a handful of circumstances why some emails may not be delivered and we'd like to double check.

**Comment by madprogramer** [comment]
Certainly, 184302

**Comment by madprogramer** [comment]
I would be happy to try and document what characters might cause this error if you keep the issue open
