### ISSUE TITLE
how to access CSS( https://itch.io/docs/creators/css-guide )?

### ISSUE THREAD

**Issue by flyupunity** [itchio/itch.io#1558]
how to access CSS( https://itch.io/docs/creators/css-guide )? #1554 
[feature-request](https://github.com/itchio/itch.io/issues?q=is%3Aopen+label%3Afeature-request)

**Comment by VerzatileDev** [comment]
> how to access CSS( https://itch.io/docs/creators/css-guide )? #1554 [feature-request](https://github.com/itchio/itch.io/issues?q=is%3Aopen+label%3Afeature-request)

https://www.youtube.com/watch?v=iVIBbhHrtRE
