### ISSUE TITLE
i want buy this game 

### ISSUE THREAD

**Issue by ryaanwa** [itchio/itch.io#1561]
i want buy this game but they say  Your card was declined. why??

**Comment by leafo** [comment]
We can't help you if you do't give us any way to look up your transaction. Did you get purchase code, it should look like P-{number}

**Comment by ryaanwa** [comment]
Where can I get it because I pay by card but they say your card is declined? Where do I get the purchase code?

**Comment by leafo** [comment]
The error message should include the purchase code that support can use to reference the transaction.

**Comment by ryaanwa** [comment]
![Uploading AA.png…]()

**Comment by ryaanwa** [comment]
![AA](https://github.com/itchio/itch.io/assets/163046859/3ea74228-519e-4369-81f0-fd72b96a7f56)

**Comment by ryaanwa** [comment]
THERE NO purchase code

**Comment by ryaanwa** [comment]
hello what happened how can i fix this problem i cant buy this game because they say my card declined and you say give me the purchase code how can i give you purchase code and i cant buy it !!!!!?

**Comment by ryaanwa** [comment]
Man, I don't know what to do. I sent an email to support and did not receive any message. I want a solution. I cannot buy the game. It says the card was rejected when I want to pay.
How do I get the purchase code if I haven't paid yet?

**Comment by ryaanwa** [comment]
![AA](https://github.com/itchio/itch.io/assets/163046859/69190fde-3eb2-4341-82ae-7cad7a1efaa6)
