### ISSUE TITLE
My account was charged for a game but it then gave me an error code and told me to contact you for a refund.

### ISSUE THREAD

**Issue by grumpygamer94** [itchio/itch.io#1565]
I recently tried to purchase That's not my neighbour and when I tried purchasing with my paypal, it charged my card but told me something went wrong, gave me this code: P-18163570 and told me to request a refund.

I'd like to just have the game itself, but will also take a refund as well of the 4.22 that you charged me.

**Comment by leafo** [comment]
The payment status in PayPal is marked as failed, so no funds were received by us to complete the transaction. It's likely PayPal put a temporary hold on your card to attempt to purchase it, but since the transaction failed the hold will be released.

Hope that explains
