### ISSUE TITLE
Typo on New Devlog Page

### ISSUE THREAD

**Issue by Psychpsyo** [itchio/itch.io#1570]
**Describe the bug**
This sentence seems to be missing a word:
![image](https://github.com/itchio/itch.io/assets/60073468/6df6f062-ac48-4a24-9f7e-fb0b0cebe022)

**To Reproduce**
1. Go to ``https://itch.io/dashboard/game/<game-id>/new-devlog``
2. Scroll down to **Languages**
4. See typo

**Expected behavior**
No typos.

**Screenshots**
![image](https://github.com/itchio/itch.io/assets/60073468/6df6f062-ac48-4a24-9f7e-fb0b0cebe022)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 123

**Additional context**
---

**Comment by leafo** [comment]
Fixed
