### ISSUE TITLE
Haven't received payout

### ISSUE THREAD

**Issue by S7AWKAT** [itchio/itch.io#1575]
Hi, I made a payout almost a month ago...and it's over 28+ days in review and I didn't get anything... I sent messages to the support several times but got no response.... what should I do?!

**Comment by leafo** [comment]
Do you have as support ticket ID? We have no way to look up your request unless you provide it.

**Comment by S7AWKAT** [comment]
> Do you have as support ticket ID? We have no way to look up your request unless you provide it.

That is the code of the request i sent to the support 199585
And that is the payout  ID 132006

**Comment by zxcv-12345** [comment]
> Do you have as support ticket ID? We have no way to look up your request unless you provide it.

I also encountered the same problem when I made the payment, it showed an error and my PayPal also deducted the money. I sent an email to support@itch.io, but I have not received any reply.

**Comment by leafo** [comment]
> > Do you have as support ticket ID? We have no way to look up your request unless you provide it.
> 
> I also encountered the same problem when I made the payment, it showed an error and my PayPal also deducted the money. I sent an email to [support@itch.io](mailto:support@itch.io), but I have not received any reply.

Same response. If you need help you must provide a support ticket ID. After you reply I'll lock this ticket, since this is not the place for requesting account or purchase specific customer support.

**Comment by S7AWKAT** [comment]
> > > Do you have as support ticket ID? We have no way to look up your request unless you provide it.
> > 
> > 
> > I also encountered the same problem when I made the payment, it showed an error and my PayPal also deducted the money. I sent an email to [support@itch.io](mailto:support@itch.io), but I have not received any reply.
> 
> If you need help you must provide a support ticket ID. Also note: your problem is not the same. This person is a seller requesting information about a payout, you are a buyer requesting information about a purchase.
> 
> If the payment did actually go through then the system will automatically send an email to you with your access link. If the payment didn't go through, then the payment process may have put a temporary hold on your balance to verify the payment. Once the hold is released the funds will be returned to you. itch.io will not generate an access link for you, you will need to purchase again with valid payment information.
> 
> Note: I'm going to lock this ticket in a bit, since this is not the place for requesting account or purchase specific customer support. If you want me to reference your ticket ID please post it before I close the ticket.

 
Thanks for ur replaying!, the payout canceled due to some problem from Paypal...i will fix the problem and remake a payout... But still i took alot of time (28)days, anyway thanks again.

**Comment by leafo** [comment]
Closing this ticket then. In the future please avoid making definitive claims or accusations in your issue title and clearly state the issue you are having. I understand that your particular issue may be distressing to you, but it's unhelpful for the greater community, as you can see we got a person with a different issue attempting to post here.
