### ISSUE TITLE
I keep getting emails for a game even though I've deleted my account.

### ISSUE THREAD

**Issue by audiogamer22** [itchio/itch.io#1578]
For the website owners my email is bradley brown two at live dot co dot uk

I understand I shouldn't give out emails but I'm getting sick of this.

I've emailed you guys a couple weeks ago with no response and the unsubscribe URL doesn't work and just throws up a page not found error.

Please help.

**Comment by leafo** [comment]
Do you have a support ticket ID I can reference? Just for context, it is possible to purchase something without an account, so it's possible there is a purchase that is not associated with the previous account.

> unsubscribe URL doesn't work and just throws up a page not found error

Are you able to share the link here? Sometimes email clients may change the characters in a link if you're trying to copy and paste it.

**Comment by audiogamer22** [comment]
First of all I'd like to say thanks so much for getting back to me so quick.

I don't have a reference but I do have the unsubscribe URL: https://itch.io/unsubscribe-account/WyELynd4sLzo1rv3DL1CJw1JZZDTceAXdzuXZYt6V6YvGr2yGMTtU6ZZ52UUjVnVSpWNNdGwZxqkTRQ1F8TRSrmuKZr2brp

**Comment by audiogamer22** [comment]
Hello, i've got the same email again today, I'm unable to unsubscribe because I get a page not found error.

**Comment by audiogamer22** [comment]
I've already sent you the link but i can send it again, I thought we were getting somewhere but then the person replying just stopped.

**Comment by audiogamer22** [comment]
This is very frustrating, I don't want to block the messages as I might buy something in the future from this company.

Can I contact the creater of ichio?

It does say something like, you are getting this mesage because you perchiced a game from ichio, I understand that but your unsubscribe links don't work and it's very frustrating.

**Comment by audiogamer22** [comment]
I've just tried contacting your company on twitter and am unable to do so.

i don't know where else to go as i don't actually have an account I deleted it.

Here's the unsubscribe link that is broken: https://itch.io/unsubscribe-account/wKVKmggYWmrfMNVh4d5sjr5Ny1kCkk54NfbdJQFnnLvZyRj4g5TPneUDxVfiKEK2cBhV1mzrgoCzw1PTH9ZRSrmuKZr2brp

**Comment by audiogamer22** [comment]
I've sent an email to the support staff and my number is (204590)

**Comment by audiogamer22** [comment]
I've heard nothing back, this reallly isn't good. If here nothing by the end of the week i'll just mark it as junk and it'll be removed and deleted but I don't want to do that.
