### ISSUE TITLE
Sending an email to Game Jam participants is failing

### ISSUE THREAD

**Issue by Jastman** [itchio/itch.io#1586]
![Screenshot 2024-04-27 at 9 14 48 AM](https://github.com/itchio/itch.io/assets/913901/4fefa38d-b897-422d-98d8-67f8dd92629c)

I'm trying to send an email to my game jam participants, but it's failing. See error message in screenshot

I've tried refreshing, logging in/out, but its not fixing it.
Also tried removing an image I had in the message, but that didnt change anything either.

**Comment by leafo** [comment]
Unfortunately it's been so long at this point we don't easily have server logs for this error available. Did you end up fixing the issue?

I'm going to close this ticket for now as we've gotten no other reports.
