### ISSUE TITLE
I still can't unsubscribe from my emails.

### ISSUE THREAD

**Issue by audiogamer22** [itchio/itch.io#1598]
Hello, this is very frustrating, I have this link to unsubscribe: **removed link**

It doesn't work, none of the unsubscribe links I've gotten over the 2 or so months of doing this work.

I've removed my account, but this still happens, please remove all data from your website or I will be forced to take this even further.

I live in the UK and have tried to comply with your website by raising 3 complaints I believe it's been now. You have one month to remove my data, that means my email and any games tied to it.

Here is the link about the law: https://ico.org.uk/for-the-public/your-right-to-get-your-data-deleted/

**Comment by leafo** [comment]
The link you included for unsubscribe is for accounts. It appears your account is deleted, so that link is invalid and can not do anything. Did you receive an email with a link like that after you deleted your account?

**Comment by audiogamer22** [comment]
Thank you for responding. I'm honestly not sure as it was a while back. I'm getting this link for a game I'm no longer interested in. If you like I can try and find you the email although i think I might have deleted it.

**Comment by audiogamer22** [comment]
I understand I can also write the same email address on a page to get a list of games I've perchiced, surely this shouldn't be possible as I've deleted my account?

**Comment by audiogamer22** [comment]
I'm sorry but I can't find the email to the game, but that unsubscribe link was from that games email.

**Comment by leafo** [comment]
> I understand I can also write the same email address on a page to get a list of games I've perchiced, surely this shouldn't be possible as I've deleted my account?

Accounts and purchases are separate entities, and can be linked if you create an account with the same email address and verify that email address. If you delete an account it does not delete your purchase history. We are legally required to maintain information about transactions for tax purposes, so a purchase can not be "deleted" like an account can.

Regardless, you should be able to unsubscribe from an email you get without an error. Do you know if this email was for a product that you had purchased?

**Comment by audiogamer22** [comment]
Ah, ok, that's fine. Yes it was for warsim I believe it's called.

**Comment by audiogamer22** [comment]
I'm trying to find the page to put the email in to bring up the list of games so I can tell you exactly what it's called but i can't find the page, if you can find it I'll put the email in there and let you know the exact title, if that helps at all?

If it hellps, I'm getting an update every time the game releases a new update, please try and fix this if you can as it's quite irrirtating.

**Comment by audiogamer22** [comment]
I'm going to sleep for now, if you have anymore question or can hopefully fix this, i'll check tomorrow/later on.

**Comment by leafo** [comment]
Are you able to confirm if it was something you purchased?

**Comment by audiogamer22** [comment]
Yes, it was.

**Comment by audiogamer22** [comment]
DO you need the name of the game?

**Comment by audiogamer22** [comment]
I don't know it but if you can give me the website where i can put my email in I can let you know.

**Comment by audiogamer22** [comment]
ok, I really am going to bed now, I'll check this tomorrow.

**Comment by audiogamer22** [comment]
Hello, any luck?

**Comment by audiogamer22** [comment]
Hello? Are you there?

I hope you figure this out, I'll not go any further with my right to be forgotten stuff, but please figure out hwat's going on.

**Comment by leafo** [comment]
We've pushed out a fix which should resolve the issue with 404 page showing up for the unsubscribe link for update email s for purchases that aren't associated with account
