### ISSUE TITLE
Can't find my download link

### ISSUE THREAD

**Issue by Mitchell-Lozano** [itchio/itch.io#1603]
I have already purchased the game "That's Not My Neighbor" and I went to go download the update and I cannot find the download link or anything besides my receipt of purchase.
![Screenshot_20240606_083906_Uber Pro Card](https://github.com/itchio/itch.io/assets/61432361/20ee8bde-ef96-44fb-a0f8-6090f0be369d)

**Comment by leafo** [comment]
You'll have to contact support so they can look up a previous transaction: https://itch.io/support
