### ISSUE TITLE
Analytics page Calendar date picker widget does not support dark theme

### ISSUE THREAD

**Issue by hsandt** [itchio/itch.io#1613]
**Describe the bug**
When using dark theme on the website, the Analytics calendar date picker widget shows part of the area in white, making the numbers hard to read.

**To Reproduce**
1. Enable Dark mode
2. Go to some game Analytics page
3. Click on the From or To date to open the calendar widget
4. See white area

**Expected behavior**
Background should be dark everywhere

**Screenshots**

![image](https://github.com/itchio/itch.io/assets/1067772/03d6eae8-113b-4dcd-b618-302d90e3bace)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - Browser: Chrome Version 126.0.6478.61 (Official Build) (64-bit)

**Additional context**
I'm trying to check analytics on older dates.
I'm also unable to enter numerical values in the date field but it doesn't seem related (I'll open another thread for this).

**Comment by leafo** [comment]
All the date  & time pickers on the site have been replaced with browser native ones, which should make them compatible with any themeing
