### ISSUE TITLE
Feature request: support numerical input on Analytics date field

### ISSUE THREAD

**Issue by hsandt** [itchio/itch.io#1614]
**Is your feature request related to a problem? Please describe.**
To see old date analytics I need to click repeatedly on the previous arrow and it's very long (12 clicks per year in the past). Inputting the date with numbers would be much faster.

Edit game > Analytics

![image](https://github.com/itchio/itch.io/assets/1067772/160b9dcf-d112-4321-a51b-0de495922b46)

**Describe the solution you'd like**
Allow date field editing, obviously with valid input date check.

**Describe alternatives you've considered**
If there was a button to jump to previous/next year directly it would also spare 11 clicks every time.

**Additional context**
I released my game years ago and I want to check the 1st month views/downloads for my future business plan.

**Comment by leafo** [comment]
All the date pickers on the site have been replaced with browser native ones which should be easier to manipulate.
