### ISSUE TITLE
Games ranking won't show after jam

### ISSUE THREAD

**Issue by victorvermot** [itchio/itch.io#1616]
The Pixel Game Jam ended but the results are not accessible [here](https://itch.io/jam/-pixel-game-jam-2024/results).
Also seems like there seems to be something weird with the number of games that have been ranked, as the message mentions 9972 ratings on only 145 games (Might only be a display issue)
`726 entries were submitted between May 11th 2024 at 1:00 PM and May 20th 2024 at 5:30 PM. 9,972 ratings were given to 145 entries (20.0%) between May 20th 2024 at 5:30 PM and Yesterday at 11:00 PM. The average number of ratings per game was 13.7 and the median was 6. `

The issue might come from the fact that the ending date was changed several times (as seen in this issue https://github.com/itchio/itch.io/issues/1145)
Thanks for the help.

**Comment by leafo** [comment]
It looks like the results are now there, so I'll mark this as closed.
