### ISSUE TITLE
Completely freezes my quest3 in several circumstances. 

### ISSUE THREAD

**Issue by victorg001** [itchio/itch.io#1617]
Example:
I've launched Grid legends with embedded profile, it's acting like 10-15 fps. After exiting I had a blank screen (only cameras work), no interface, no buttons acted. pressed the power button until device powered down. After reboot launched game outside optimizer, it works fine. Then exited Grid, launched optimizer, got another freeze of system.

**Comment by domexie** [comment]
Please be aware that this is the issue tracker for itch.io, the website itself. If you have issue with any specific  game, please consider get in touch with the developer of that game.
