### ISSUE TITLE
Add Project URL @ Create Co-op Bundle = Broken

### ISSUE THREAD

**Issue by VirtualNomad19** [itchio/itch.io#1619]
[Add]ing Project URL when Creating New Co-op Bundle = Page updates with removal of all Bundle details

1. [Create New Co-op Bundle](https://itch.io/bundle/new)
2. Paste Project URL
3. [Add]

![coop2](https://github.com/itchio/itch.io/assets/52613918/5c2daf6e-4e01-4a15-8355-27ddd7af886a)

WIN10/Edge

**Comment by leafo** [comment]
Thanks for the report, it's now fixed.
