### ISSUE TITLE
Add "web-share" to iframe "allow" attribute

### ISSUE THREAD

**Issue by LauraLaureus** [itchio/itch.io#1621]
**Describe the bug**
The iframe where the WebGL games are played doesn't contain the "web-share" in the "allow" attribute. This prevent using the "navigator.share" JS API which is a useful tool to call the mobile-native share pop-up. 

**To Reproduce**
1. Replicate the code in the Mozilla documentation as HTML file https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#sharing_a_url 
2. Update it to itch.io 
3. Press the button. 
4. Get the "Permission error"

**Expected behavior**
Only on mobile browsers, at pressing the button the native share pop-up is displayed. 

**Screenshots**
Expected behaviour 
![kmknLV](https://github.com/itchio/itch.io/assets/8750232/5db53c48-d13a-4067-a44b-1e91cbe6a09d)

**Smartphone (please complete the following information):**
 - Device: any but tested with Samsung Flip 5
 - OS: Android 14
 - Browser newer browsers but tested with Chrome 124

**Additional context**
Please add this tag. It will help promotion of WebGL Games on mobile :D!

**Comment by leafo** [comment]
It is now there, thanks for the request.
