### ISSUE TITLE
"tags" property empty in getGameData response

### ISSUE THREAD

**Issue by ohiogauze** [itchio/itch.io#1623]
**Describe the bug**
I have been testing `Itch.getGameData` and in my experience, the `tags` array is always blank.

**To Reproduce**
1. Load the [Itch.io JavaScript API](https://itch.io/docs/api/javascript) into a website via `<script>` tag.
2. Paste the example code for `getGameData` into the Developer Tools console:
```javascript
Itch.getGameData({
  user: "leafo",
  game: "x-moon",
  onComplete: function(data) {
    console.log(data)
  }
})
```
3. Observe the response. The `tags` array is empty.

**Expected behavior**
I expected the `tags` array to have the three tags defined on [the game's page](https://leafo.itch.io/x-moon):
`["LÖVE", "Ludum Dare", "Space"]`

**Desktop Details:**
 - OS: macOS
 - Browser: Safari
 - Version: 17.4.1

**Comment by ohiogauze** [comment]
Looking at the code, it seems this is more an issue with the the `data.json` file for any given game. eg. [https://leafo.itch.io/x-moon/data.json](https://leafo.itch.io/x-moon/data.json)

**Comment by leafo** [comment]
Thanks for the report. The tags data originally was undocumented and unused, but it is now being returned in the response.
