### ISSUE TITLE
What happens when you can't remember login?

### ISSUE THREAD

**Issue by ajax0491** [itchio/itch.io#1628]

**Comment by ajax0491** [comment]
I'm 80 and sometimes forget.

**Comment by Psychpsyo** [comment]
If you know what email you used, you can click "Forgot password" on the login screen and it'll send you an email that you can use to reset your password.

**Comment by leafo** [comment]
If you aren't able to use any of the account recovery tools, like the forgot password tool, then you can try contacting support and they can see if there is another way for you to prove ownership of an account.

If that doesn't work, then the account will be lost.
