### ISSUE TITLE
Difference between game before and after download

### ISSUE THREAD

**Issue by burgerking59** [itchio/itch.io#1629]
I have created a game in Godot and have exported and uploaded to Itch. However, the game is not working as intended when I download it from itch but is working in the editor and the exported executable. The main problems I have noticed are physics collisions failing ,the physics tick rate seems to be lower and a signal to disable a collision shape doesn't work.
I don't know how to reproduce this as I have never experienced it before and can't understand where the differences would come from.

The white ball doesn't go through the collision shape because the signal is not disabling it. Downloaded from Itch
https://github.com/user-attachments/assets/2a73f43b-fa04-400a-bbdc-8f316de64aa5

This is what should happen. Exported from Godot
https://github.com/user-attachments/assets/8f5abe77-8e1e-493b-8de9-84aaf775f554

**Comment by leafo** [comment]
We don't modify any files you upload. It's likely your exported game is different than what is running in the editor, and the physics issue you're encountering is a side effect on the game engine you're using.

**Comment by burgerking59** [comment]
The exported version is the same as in the editor it's only once I upload it to itch and download it again that there are changes.
