### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by Zaiayt** [itchio/itch.io#1631]
hey there so i bought among us from itch.io and it wont let me sign into my account how to fix?

**Comment by leafo** [comment]
Do you have any other information you can share? Otherwise I'll close this issue as it isn't actionable.

**Comment by Zaiayt** [comment]
no i dont :(

**Comment by leafo** [comment]
Try contacting support then, this issues tracker is not for account or purchase support: https://itch.io/support
