### ISSUE TITLE
API Key Scopes: Have a way to add scopes to my API KEY

### ISSUE THREAD

**Issue by pinklily69** [itchio/itch.io#1664]
I'm trying to call :

https://itch.io/api/1/KEY/game/GAME_ID/purchases

But I'm getting :
{"errors":["api key does not permit `game:view:purchases`"]}
My API key's information: 
{"oauth_application_id":****,"scopes":["profile"],"type":"key"}

Now my question is: how do I get the scopes: game:view:purchases?

![api_keys](https://github.com/user-attachments/assets/fba81ffc-999f-4e58-b4f1-1315c0382735)

**Solution:** Add an edit field, let us edit the scopes of our API Keys!
**Alternatives:** Allow the request of the game:view:purchases scope and others in the ouauth requests!

For context this is not a web app that can use the manifest and stuff. I'm making an Unreal C++ video game and the api is getting called from my cloud server for authentication and refresh of the micro transaction purchases. There's no way around this, just tell me how to make this request work or add this much needed feature!

**Comment by pinklily69** [comment]
Just understood that this is not an automatic key generated upon OUAUTH creation. It was made during testing. So I can create a custom one by the same means. Thanks anyways lol

**Comment by pinklily69** [comment]
Okay so turns out the ones you generate for yourself using that red button are all the scopes, so I'll use that one. Not very descriptive in name and should need a rename feature but yeah that solves my issues. Thanks!

**Comment by pinklily69** [comment]
closing

**Comment by maxii1996** [comment]
Can you solve it?
