### ISSUE TITLE
broken/bitrotted link on Hosting a sale or bundle page

### ISSUE THREAD

**Issue by DOSisGOOD** [itchio/itch.io#1673]
**broken/bitrotted link**

There's a broken link on this page for"Gamasutra, How deep discounts really affect your games http://www.gamasutra.com/view/news/174587/Steam_sales_How_deep_discounts_really_affect_your_games.php", it looks to have been moved to:  https://www.gamedeveloper.com/business/steam-sales-how-deep-discounts-i-really-i-affect-your-games

**To Reproduce**
1. Go to Hosting a sale or bundle https://itch.io/docs/creators/sales
2. Click on Gamasutra, How deep discounts really affect your games http://www.gamasutra.com/view/news/174587/Steam_sales_How_deep_discounts_really_affect_your_games.php 
3. It leads to https://www.gamedeveloper.com/latest-news 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 131.0.3

**Comment by leafo** [comment]
Hmm, looks  like the pull quote originally in the guide doesn't exist in that new article. I've just removed the quote and article link as I think most people understand the value of sales.
