### ISSUE TITLE
HTML5 game offset in the viewport

### ISSUE THREAD

**Issue by kyle-sylvestre** [itchio/itch.io#1675]
**Describe the bug**
My game is being shifted down and right in the viewport. This problem does not happen in localhost sessions.

**Expected behavior**
I expect the viewport to be 100% used by the program.

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/f366d63c-aa37-4124-a214-8dd6753721f5)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 130.0.6723.92

**Comment by leafo** [comment]
You likely have a margin or padding on your game element in the index.html file you uploaded. You should be able to verify what is causing it with your browser inspector. Start your search from the `iframe` itchio uses to embed your game.
