### ISSUE TITLE
Cannot install launcher

### ISSUE THREAD

**Issue by Hunter-D-Kern** [itchio/itch.io#1684]
Starting the setup executable produces the following error:

> Something went wrong
> 
> itch-setup, v1.26.0, built on Apr 21 2021 @ 20:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd
> 
> Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host
> While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
> while getting latest version
> Error during warm-up

**Comment by Melmirr** [comment]
Seconded. 
![itchsetup](https://github.com/user-attachments/assets/44639e17-4e2a-4811-90be-386b2517bc2f)

**Comment by leafo** [comment]
Can you try downloading and running the bleeding edge version of `itch-setup` for your platform with a year of 2023 to see if it resolves the issue? https://itchio.itch.io/itch-setup

(Note this will install the regular mainline version of the app, not a beta version of the app)

**Comment by yairm210** [comment]
It looks like all of `itch.ovh` is offline - https://docs.itch.ovh/wharf and https://broth.itch.ovh/butler show similar issues
This makes [automated uploads](https://github.com/yairm210/Unciv/actions/runs/12125425617/job/33805779202) fail 

Ping shows 
```
❯ ping itch.ovh
ping: cannot resolve itch.ovh: Unknown host
```

Looks like the [domain is renewed](https://ae.godaddy.com/whois/results.aspx?itc=dlp_domain_whois&domain=itch.ovh) on 28-29.11 each year, probably related
<img width="669" alt="image" src="https://github.com/user-attachments/assets/b68c4d29-ad72-45ce-af19-ddbf76001e45">

**Comment by leafo** [comment]
Please try again, we had some downtime with our legacy update server that was still hard-coded in a few places.

That said, we've since pushed out patched versions of the app and related software. Please make sure you update to the latest version to ensure you don't have any issues accessing the app in the future: https://itch.io/t/4351835/app-and-butler-updates-may-require-manual-intervention#post-11509812

**Comment by yairm210** [comment]
Thank you for all your work!!!
