### ISSUE TITLE
hpx 

### ISSUE THREAD

**Issue by ht75178** [itchio/itch.io#1685]
Meu jogo você tem que derrotar robôs que foram infectados

**Comment by ht75178** [comment]
Eu tô colocando o meu código mas não tá funcionando

**Comment by ht75178** [comment]
Eu já fiz essa m**** mil vezes

**Comment by ht75178** [comment]
![1732997302999](https://github.com/user-attachments/assets/3aea905a-08bc-41f6-af15-8cde780470a3)
![Screenshot_20241130-180006](https://github.com/user-attachments/assets/dcf1e059-981f-40f2-97e6-93a0a5bd7a54)
![Screenshot_20241130-180014](https://github.com/user-attachments/assets/d9ab7680-7363-4ff7-bd69-5366150e4452)
![Screenshot_20241130-180020](https://github.com/user-attachments/assets/6c913fbd-9a58-4941-a7ed-395a27593706)
![Screenshot_20241130-180029](https://github.com/user-attachments/assets/bf9e2b92-085d-4bf0-92c4-2e6f42b35117)
![Screenshot_20241130-180037](https://github.com/user-attachments/assets/123cc4b1-4922-40c8-9825-fc91a474dc77)
![Screenshot_20241130-180044](https://github.com/user-attachments/assets/cbde60e0-bcdd-472a-84cb-3dc9367e6971)
![Screenshot_20241130-180055](https://github.com/user-attachments/assets/faf4a9a2-e1ab-4abb-a819-bee6b59ba66f)
![Screenshot_20241130-180104](https://github.com/user-attachments/assets/c12a95aa-4910-4cb9-b853-707d993ab1d0)
![Screenshot_20241130-180110](https://github.com/user-attachments/assets/6d5a1b3d-e14d-41ea-b645-ad17cf38a502)
![Screenshot_20241130-180117](https://github.com/user-attachments/assets/322cc16f-29ca-4c1d-a8fc-cc03f45785b6)
![Screenshot_20241130-180129](https://github.com/user-attachments/assets/f02f3d17-7008-4412-8d66-0f35c54a96bf)
![Screenshot_20241130-180148](https://github.com/user-attachments/assets/8cd0d1e1-a640-48c3-a0e9-da3ff8813b43)
![Screenshot_20241130-180136](https://github.com/user-attachments/assets/b3e55f74-a5e4-40eb-be66-021f9db7fd2a)
![Screenshot_20241130-180159](https://github.com/user-attachments/assets/a7553cd5-c851-4f95-bc5f-fd9933b4aed4)
![Screenshot_20241130-180205](https://github.com/user-attachments/assets/7dbdc7c5-5391-4320-be0e-81e6bbd3137a)
![Screenshot_20241130-180215](https://github.com/user-attachments/assets/88da1773-8ad0-430f-96d7-1149eacc0c1a)
![Screenshot_20241130-180226](https://github.com/user-attachments/assets/6e78082f-6b16-4af9-96e6-6536b87174ab)

**Comment by leafo** [comment]
Sorry you're having trouble but this is the itchio issues tracker, and not related to the development of your game. Hope you can find help elsewhere.

Thanks
