### ISSUE TITLE
Can add an Apple Store link to my product page

### ISSUE THREAD

**Issue by stephane-archer** [itchio/itch.io#1686]
```
https://apple.co/492UyV2
```

```
app store URL — expected App Store product URL, or empty
```

**Comment by leafo** [comment]
Use the full link, not a shortened one.

**Comment by stephane-archer** [comment]
while the full link works, I would be glad if both would work for ease of use

**Comment by leafo** [comment]
We won't be supporting URL shortened links in that field to make validation simpler on our end.
