### ISSUE TITLE
Different noun ("developer" -> "creator") on purchase appeal

### ISSUE THREAD

**Issue by elementc** [itchio/itch.io#194]
The screen where customers click to purchase an item has this text:
"Support the developer by paying above the minimum price"

I'm putting together a musical album sale page for a friend and he'd much prefer to be referred to as a "creator" than a "developer".

We support custom nouns for items (eg I refer to my item as an "album"), but we don't support custom nouns for creators. "creator" would be more neutral than "developer" for now, but a long term solution would be to support custom nouns here too.

**Comment by elementc** [comment]
@leafo any input here?

**Comment by fasterthanlime** [comment]
I think it's a good idea. custom nouns is a popular feature of itch.io, makes sense to have it for creators too, only thing I'm (eternally) worrying about is the eventual i18n apocalypse.

But it seems we have some time before it happens :)

**Comment by elementc** [comment]
Email to @leafo about an another issue and this got fixed. Thanks so much!

**Comment by leafo** [comment]
:+1:
