### ISSUE TITLE
Bitcoin payouts

### ISSUE THREAD

**Issue by SoniEx2** [itchio/itch.io#199]

**Comment by apatheory** [comment]
You mean as a minimum price, right?
I suppose you could have it at pwyw, with a friendly mention of your bitcoin wallet somewhere in there.

**Comment by chiguireitor** [comment]
This could be great for us developers outside of the US that don't have ways to get cash from paypal and in the end would avoid nonsensical fees imposed by them. Please support it!! :)

**Comment by Deozaan** [comment]
@apatheory I think @SoniEx2 means when the developer receives a payout from Itch.io (or directly from buyers) it will be in Bitcoin rather than e.g., USD via PayPal.

**Comment by bjorn** [comment]
Another vote from my side! It's quite annoying that in order for earnings to arrive on my bank account, PayPal is charging 2.5% just for converting from USD to EUR. And that while it already charges over $0.30 for each transaction. Taken together, transaction fees are a higher cost than the default 10% itch.io cut.

When this is implemented I'll raise my itch.io cut by 2.5%!

**Comment by gordebak** [comment]
In my country, I don't have access to PayPal or Stripe. A universal payout method would be great.

**Comment by bjorn** [comment]
[bountysource.com](https://www.bountysource.com/) has had a Bitcoin payout option (alongside Paypal) since years. They are using Coinbase for it. Maybe you can ask them about any concerns you may have.

**Comment by chiguireitor** [comment]
Itch.io Y U NO, BITCOIN CASHOUTS!!!!!

Really, 2 years and still no bitcoin payouts? what is this? 2008?

Coinbase is non operative for non-us residents, Paypal has crazy fees and isn't possible to use in certain countries (like mine, btw), Stripe is even more restrictive.

Wtf!? Really? What is actually needed for y'all to support this?

I've even stopped selling my new games through itch.io because of this.

Please, btc cashouts, like yesterday.

**Comment by bjorn** [comment]
> Coinbase is non operative for non-us residents

Note that I only mentioned Coinbase as a possible means of doing the payout, where the money is converted automatically. The payout would still happen to any Bitcoin address so the receiver does not need to be using Coinbase.

**Comment by chiguireitor** [comment]
Yeah, but coinbase outright rejects you if you're not in one of the few countries they support.

**Comment by sasa1024** [comment]
It's not about buying games with bitcoin!
It's about paying developers with bitcoin!
So open this issue and please give us this feature!
We need it!
I need it :(

**Comment by chiguireitor** [comment]
I guess most devs are US based, so they don't care :disappointed:

**Comment by leafo** [comment]
Sorry but this is not something we are going to pursue at this time. If there's a third party service that facilities everything for us, we would potentially look into it. But right now we have two primary options for payouts PayPal and Payoneer. And we're also able to provide direct deposit & wire transfers for some sellers.

Thanks
