### ISSUE TITLE
An "Enter" keypress is required to change a download's display name

### ISSUE THREAD

**Issue by madewokherd** [itchio/itch.io#24]
On the edit game page, if I go through the following steps:
 * Click on "Change display name" under a link.
 * Type in a new name.
 * Scroll down and click "Save".

The new display name is not saved.

It is saved if I press enter in the name field.

**Comment by Deozaan** [comment]
This one throws me for a loop, too!

**Comment by Ragzouken** [comment]
Yep same. Always get caught by this

**Comment by Guard13007** [comment]
@fasterthanlime Any chance we can get this fixed? Could we make it recognize when you leave the field focus and save your changes to that field (at least, for the page display)? I find it annoying to have to hit enter every time I update instead of just moving on to the next field.

**Comment by leafo** [comment]
fixed now. Clicking anywhere outside the field when it's active will save its value. Hitting tab or enter will also save it. Hitting ESC will reset it to its previous value. Emptying the field and saving it will restore it to  the filename

**Comment by Deozaan** [comment]
Awesome! Thanks!

**Comment by Guard13007** [comment]
Woo! :D Thank you!
