### ISSUE TITLE
Sell multiple games/tools in one account, but separately from each other

### ISSUE THREAD

**Issue by kujovic** [itchio/itch.io#251]
How can I sell a serious tool without other people seeing some funny games I have in my account too? Should I create multiple accounts for unrelated products or is there a way to have them (privately) organized in one account? I am not in favor of having separate accounts because of the more difficult financing, more frequent but lower payouts and in general more chaotic management of everything in more places instead of in one centralized location. And if I create multiple accounts (is it allowed?), will there be any issues with having the same PayPal email address for payouts on different accounts?

@fasterthanlime mentioned using one account and organizing it with collections which I checked out now, but this doesn't solve the problem if I don't want people to see other stuff in my account.
_For example, let's say I want to sell a serious tool called "Pro Audio Generator" which is tied to my website "Digital Audio Tools" and at the same time I want to sell a funny game called "Bunny Saga" from my other website "Cool Games". I think it is now obvious that I don't want audio industry professionals to see some stupid game on my profile._

Furthermore, this whole issue is in a way tied to issue #96, because I also have the need to have more than 1 public URL in one account, because I need something like `digital-audio-tools.itch.io` for the serious tools and `cool-games.itch.io` for funny games. I think it's also pretty obvious that I don't want people buying the tool to land on the cool-games URL, or vice versa.

**Comment by Deozaan** [comment]
You can create multiple accounts and give permission to one account to edit the details of the products of the other. All products will show up on your dashboard to edit and configure but to customers they will appear as being sold by different companies/people and will have their own subdomain.

**Comment by kujovic** [comment]
Thanks @Deozaan, I wasn't aware of that! Your workaround is definitely the best solution for this issue in the current feature set of itch.io! It's almost exactly like the feature I needed.

So, if I understand correctly, I don't even have to login to other accounts if I'm the admin to those accounts from the "main" account. And even if I lose access to "sub" accounts, I should be able to change the password and everything, because, if I remember correctly, it says that an admin you add has all the privileges like the original account, even editing admins.

In that case, this is perfect for now, because I can manage all games/tools from one dashboard and still have separate URLs. Thanks again.
