### ISSUE TITLE
Disable/improve the "More you might be interested in" section

### ISSUE THREAD

**Issue by kujovic** [itchio/itch.io#252]
The _More you might be interested in_ section appears when you go to download files of a project, below the download buttons. I don't mind having the section shown by default, but it would be great if you could just add a tick option somewhere which would disable showing other projects and provide a clean download interface. Specifically, I want to sell a tool which doesn't have any other related or "recommended" tools on your website.

Otherwise, it would be good to improve the section to at least show relevant projects - if my project is a tool, it should at least show other tools (that is, projects from the same category), not games. And for games the suggestions could be based on much more factors which the downloaded game has, the ones like genre, cost, platform etc.

**Comment by fasterthanlime** [comment]
> if my project is a tool, it should at least show other tools

definitely fair

> disable showing other projects

in my mind this goes together with the functionality we discussed earlier to allow displaying other works directly on a game page (either "automatically-generated related", or a collection, or.. random stuff? the possibilities are endless)

**Comment by kujovic** [comment]
Yes, I think it's better to prioritize works from the same developer, before showing other works.

**Comment by kujovic** [comment]
This feature has since been improved accordingly, closing. 👍
