### ISSUE TITLE
"Pequod" can't be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by tswast** [itchio/itch.io#263]
I'm on OS X 10.10.5 (14F1021) and have disabled Gatekeeper, but I still cannot open Pequod. I donated on http://bearmancer.itch.io/pequod for this, so I'm a bit disappointed.

![no-pequod](https://cloud.githubusercontent.com/assets/247555/11614721/8bced2be-9bff-11e5-8118-7feb91b428f7.gif)

**Comment by fasterthanlime** [comment]
Reached out to the developer, will see what they think: https://twitter.com/fasterthanlime/status/673567678842478592

**Comment by fasterthanlime** [comment]
I've downloaded the game and cannot run it by launching the .app bundle myself either, however, the following works:

```
cd path/to/Pequod.app/Contents/MacOS
./Mac_Runner
```

Note that the app will start in the background (you'll have to switch to the game's window)

(Ideally the developer would upload a new version with a fixed bundle!)
