### ISSUE TITLE
Game page color changer acts weird when typing in color codes?

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#265]
(Sorry I couldn't think of a good way to title this.)

When I go to change colors, I often forget that you have to select the appropriate bullet point before typing in a color code, so I am always overwriting a color a few times before I remember to switch the bullet point before typing in, even though I can freely select other text inputs.

![ewufhweuifew](https://cloud.githubusercontent.com/assets/15093567/11647641/6e306d64-9d1f-11e5-9ee5-0b5c15f20566.png)

Can we either have it so that it automatically selects the correct bullet when you start typing into another text input, or make the text inputs un-editable until selected? It's a minor thing I know, but very frustrating when I end up changing the wrong color and have to remember which color I wanted something and fix it repeatedly.

**Comment by leafo** [comment]
Fixed now, sorry for taking forever. (Managore bugged me about it while I was hanging out with him at GDC)

**Comment by Guard13007** [comment]
Awesome! Thank you! And damn, I'm jealous. xD I'd love to go there.
