### ISSUE TITLE
Automated uploads?

### ISSUE THREAD

**Issue by charliesgames** [itchio/itch.io#270]
Hi,

It would be pretty cool if it was possible to have a direct link/whatever that i can use to update builds of my games without having to log in and replace them every time manually, ideally something i could call from a shell script. Don't know how possible this would be though?

Cheers
Charlie

**Comment by leafo** [comment]
It's planned, not sure when we'll have something available though. We'll be building command line tools to update games.

**Comment by charliesgames** [comment]
Yay!

Cheers
Charlie

**Comment by fasterthanlime** [comment]
@charliesgames and there they are! https://docs.itch.ovh/butler/master/
