### ISSUE TITLE
Click to Play button for HTML5/WebGL

### ISSUE THREAD

**Issue by robertpfeiffer** [itchio/itch.io#275]
I want to read the description of a game first before loading a huge Unity WebGL game. I have Click-To-Embed enabled with Adobe Flash. Can you make it a user setting (for users with not that much bandwith/RAM) that HTML5 games are loaded only on demand?

**Comment by Guard13007** [comment]
This would be very nice to have. +1

**Comment by leafo** [comment]
does it makes more sense to have it as a user wide setting, or a per game setting, or a combination of both?

**Comment by onefifth** [comment]
As a creator, I'd love to turn this on for a single game I'm distributing. Making it an option for consumers also makes a lot of sense.

**Comment by fasterthanlime** [comment]
note that we have access to the size of a web game, so we can have the default vary, for example: <10MB games could load by default, >10MB would be click to play.

(And then have per-game setting + consumer setting)

**Comment by notnsane** [comment]
More options for consumers is good. 
I'd rather have this being opt-out, since I prefer to slap the face of the user with my games without asking.
Just like _real life_.

**Comment by qubodup** [comment]
Opening WebGL games has a huge performance impact. Lack of this feature makes the experience of playing/checking out WebGL games a horrible one for low performance computer owners.

**Comment by Guard13007** [comment]
@fasterthanlime Please do not use size of the game to turn that on/off unless it can be overridden by a user setting. Probably best to default to opt-out since that's been the behavior up till now.

**Comment by leafo** [comment]
![](http://leafo.net/shotsnb/2017-07-14_13-31-02.png)

This is now available as an option from account settings.

**Comment by Guard13007** [comment]
Nice! :D Thank you.
