### ISSUE TITLE
search endpoint

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#289]
Separate endpoints for users, tags, and games:

`/api/1/search/games?q=TERM`

etc. — so we can run concurrent queries

all paginated

games format is well-defined already

tags you can pretty much dump the model (description if there is one, etc.)

users, same as what there is in user fields in game response?

**Comment by fasterthanlime** [comment]
feel free to break down in separate issues

**Comment by leafo** [comment]
* why paginated? do we ever get valuable results past the top 30?
* why separate endpoints?

**Comment by fasterthanlime** [comment]
> do we ever get valuable results past the top 30?

yes because our current ranking could, uh, use some improvement. look at how jimsterling is doing itch.io tasty, he's definitely going past page 1

there's "targeted" searches where you're looking for 1 game, in which case it should definitely be in top 10 (first google page), and larger searches where you want everything that has to do with "word X" (yes, tags and categories and whatever exist but people use search for everything nowadays and I don't think they're wrong)

> why separate endpoints? it will probably be much faster to mimic the web with one search endpoint

so we can paginate those separately? they're separate DB queries anyway.

**Comment by leafo** [comment]
I do agree that our current search isn't the best. There are two types of searches: topic searches and direct matches. For topic searches we should be figuring out how to get people to the respective topic page, the browsing experience will always be better. For direct matches there should never be more than a handful of relevant results.

**Comment by leafo** [comment]
https://itch.io/api/1/me/search/games?query=x-moon

**Comment by Mrmaxmeier** [comment]
Currently `/api/1/me/search/games` requires an api key via cookie.
Could you move it to `/api/1/<key>/me/search/games` or add something like `/api/1/search/games` without requiring an api key?

**Comment by fasterthanlime** [comment]
@Mrmaxmeier `/me` is a fragment you can use instead of your api key :)

**Comment by fasterthanlime** [comment]
@Mrmaxmeier so the real endpoint is `/api/1/<key>/search/games`

**Comment by Mrmaxmeier** [comment]
@fasterthanlime whoops, I should've tried that.

**Comment by fasterthanlime** [comment]
@Mrmaxmeier if you're working on search functionality in your fork, can you open an early PR so we can discuss it in the open and minimize duplicated effort ?

**Comment by Mrmaxmeier** [comment]
@fasterthanlime sure, opened it in [itchio/itch #231](https://github.com/itchio/itch/pull/231)

**Comment by fasterthanlime** [comment]
API has game & creator search, I consider this closed.

(For now!)

**Comment by Enissay** [comment]
@fasterthanlime a link please ?

**Comment by fasterthanlime** [comment]
@Enissay 

https://itch.io/api/1/me/search/games?query=x-moon
https://itch.io/api/1/me/search/users?query=kenney
