### ISSUE TITLE
List apt (deb) and yum (rpm) repositories on itch.io/app with instructions

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#300]
cf. https://github.com/itchio/itch/releases/tag/v0.11.3

Additional deb instructions:

```
Install all itch.io software on Debian-based distributions 

To add our GPG key, run: 

$ curl https://dl.itch.ovh/archive.key | sudo apt-key add -
```

Additional rpm instructions:

```
Install all itch.io software on Yum-based distributions 

To add our GPG key, run: 

$ sudo rpm --import https://dl.itch.ovh/archive.key
```

**Comment by fasterthanlime** [comment]
Bumpity bump, otherwise our dear apt/yum users are always going to run a few versions behind :(

**Comment by fasterthanlime** [comment]
@leafo this is still pretty high-priority

**Comment by fasterthanlime** [comment]
Alright I'll do it myself

**Comment by leafo** [comment]
we still don't got this :(

**Comment by fasterthanlime** [comment]
@leafo of course we do:

  * https://docs.itch.ovh/itch/master/installing/linux/ubuntu-and-debian.html
  * https://docs.itch.ovh/itch/master/installing/linux/fedora.html

**Comment by fasterthanlime** [comment]
itch.io/app links to the docs now
