### ISSUE TITLE
Direct people to support for specific games?

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#301]
My idea is to add a section for developers to specify an email address or GitHub issue tracker or whatever info the developer wants to use for reporting bugs, that could be linked to from a game's page.

Additionally, if this was added, the [support page](http://itch.io/docs/general/support) for Itch.io could have a link "Looking for support for a specific game?" that would then let you search or choose the game from your purchases, and see the support info for that game.

**Comment by leafo** [comment]
Definitely want to do something like this.

**Comment by fasterthanlime** [comment]
:+1:

**Comment by onefifth** [comment]
This seems complete looking at the current support page (https://itch.io/support), which is not the one linked in this issue.

**Comment by fasterthanlime** [comment]
Oh yeah, leaf did that a while ago, for WolfQuest! Closing :)
