### ISSUE TITLE
Use HTTPS on all pages

### ISSUE THREAD

**Issue by ekaris** [itchio/itch.io#302]
Use HTTPS on all pages by default to protect your users privacy and security

**Comment by leafo** [comment]
Just putting this here for reference: http://blog.itch.io/post/134343623599/switching-to-https-everywhere

we were supposed to switch a little while ago but I haven't had a chance to fix all the lingering issues yet

**Comment by ekaris** [comment]
Use this tool to analyse the website and solve the problems currently affecting the HTTPS server:
https://www.ssllabs.com/ssltest/analyze.html?d=itch.io&s=45.33.55.10

**Comment by ekaris** [comment]
Any news?
Server is still not configured optimal as indicated by the scan.

**Comment by leafo** [comment]
https is now used on all pages as of februrary 11th: http://blog.itch.io/post/139136003894/https-now-forced-everywhere. I just updated our ciphers to fix the logjam attack described in the report above.

Thanks
