### ISSUE TITLE
Add gif-less URL in API responses

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#308]
The app is slow when there's a lot of large gifs :(

**Comment by leafo** [comment]
what's the plan, to have both image urls and decide what to do in the app? I think right now if you disable gifs on your account the api would render urls without gifs in them.

**Comment by fasterthanlime** [comment]
> what's the plan, to have both image urls and decide what to do in the app?

that's what I had in mind :+1: 

> I think right now if you disable gifs on your account the api would render urls without gifs in them.

I thought that's what would happen too but it looks like the API returns gifs no matter what your website settings are right now

**Comment by fasterthanlime** [comment]
done back on June 17, 2016 — as `still_cover_image` (not present when `cover_image` is already a still)
