### ISSUE TITLE
img request = 503 backend fetch failed

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#318]
cf. http://itch.io/t/13496/is-anyone-elses-avatar-showing-up-as-a-broken-image

**Comment by leafo** [comment]
image dimensions are 8000x8000, we don't allow that. a client side fix is probably the best solution

**Comment by fasterthanlime** [comment]
@leafo are they actually 8000x8000 or is an image library behaving badly? user seems to say it used to work, & I'm not sure any real-world 8000x8000 image would be under our image size limit, but I could be wrong..

**Comment by leafo** [comment]
the image is actually that big: http://commondatastorage.googleapis.com/itchio/image2/user/64931/221203.png

**Comment by fasterthanlime** [comment]
damn
