### ISSUE TITLE
Update files to download

### ISSUE THREAD

**Issue by matriax** [itchio/itch.io#325]
Maybe i'm missing some feature but i made a mistake and there is no way to update the files with some downloads in the stats.

So i deleted the files and reupload it lossing the download counter.

Is there anyway to update the files without lossing the download counter? When is a major update yes, i create other download with a Xnumber of version, but for minor updates like a readme.txt file added or some little change in the game ¿?

**Comment by leafo** [comment]
if you upload a file with the same name then the stats on that file will be preserved. Otherwise the individual stats are no longer visible when you delete that file.

Also keep in mind that the overall stats for your project are not affected by deleting a file.

**Comment by matriax** [comment]
I see, maybe a small note with that info in the "upload file" word side will be great, like the one in the "external files".

**Comment by matriax** [comment]
Well, not works, i upload again the files from dropbox with the same name and were added as new files not replacing the old ones :S

**Comment by fasterthanlime** [comment]
> Maybe the replacing only works for external files and "upload" from computer but not from Dropbox?

Yup, that's what's happening, as far as I can tell

**Comment by fasterthanlime** [comment]
@matriax The best way to push a new version of something is now to use https://docs.itch.ovh/butler/index.html — it maintains a proper chain of versions & will keep your download stats.
