### ISSUE TITLE
Using "External keys" to buy things inside the game, allowed?

### ISSUE THREAD

**Issue by matriax** [itchio/itch.io#328]
For my next game i was thinking on some ideas and one of them is some html5 rpg game with "in-app" purchases or in this case "Out-App" purchases.

How?: Using the external key given by itchio after buy inside the game to get some Gems/Gold or another things. 

This keys are also in my DB so when they add the key into the game connect and give the gems and erase the key in the DB to avoid being used again.

Obviously the perfect thing will be an In-App purchase API made by Itchio(So take note of this feature too! ;) ) but meanwhile i thought do that. 

So, in the case i go ahead with this game idea, i can do that? or i will violate some kind of rule? What you think?

**Comment by leafo** [comment]
It will not violate any rules. Feel free to do this. Keep in mind though that in order for someone to buy your game, even if you have keys available, you must have some downloadable files.

**Comment by matriax** [comment]
Yes i guess some readme.txt with instructions, some wallpapers or something like that.

Also an In-App purchase API is planned or can be take in consideration?

**Comment by leafo** [comment]
Maybe in the future, but no immediate plans at the moment.

**Comment by Guard13007** [comment]
@matriax I'm curious to see what you do with this, can you link me your Itch profile so I can follow you?

**Comment by matriax** [comment]
Mi itchio profile: http://kronbits.itch.io/ .

Btw at the moment as i said is only an idea, i confirmed that the itchio part can be done, now is how to implement in my game(The DB part) and after see what the user feels in the process, if is easy,etc... or do it in another way.
