### ISSUE TITLE
Rename "public restricted" to "unlisted"

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch.io#331]
Public restricted always sounded kinda weird, and a bit confusing, but people tend to know what "unlisted" means.

(That said, having to have a secret token to access a public restricted page isn't quite the same as unlisted...but I think it's close enough..closer than public restricted.. and shouldn't cause confusion.)

**Comment by hawkerm** [comment]
Is this still relevant given the various modes available now, it seems pretty straight-forward at the moment.

Doc link: https://itch.io/docs/creators/access-control

**Comment by TangentFoxy** [comment]
What's changed since I made this makes so much more sense than what I proposed.
