### ISSUE TITLE
Recommendations include deleted games

### ISSUE THREAD

**Issue by grifdail** [itchio/itch.io#335]
The personalized recomandation feed on my frontpage include Kenney crowdFundick asset pack which doesn't exist anymore.
![capture2](https://cloud.githubusercontent.com/assets/1630194/12481224/ed3c50aa-c047-11e5-9eb0-625bc7089233.PNG)

The thumbnail doesn't have any popover like the other do and link to a 404 page.(http://kenney.itch.io/kenney-land-crowdfunding-pack)

How to reproduce:
Open the front page while connected as me.

**Comment by leafo** [comment]
Fixed now
