### ISSUE TITLE
Following Count Inaccurate

### ISSUE THREAD

**Issue by Doppp** [itchio/itch.io#337]
For some reason, the following count on my [Following](http://itch.io/my-followings) page shows 120 but it seems like I am only following 52 users. I'm not sure why that is.

Edit: The page does not show all the users you are following, just a subset of them.

**Comment by Doppp** [comment]
@leafo @fasterthanlime thoughts on this? Or was this meant to be a feature?

**Comment by fasterthanlime** [comment]
probably not an intended feature

**Comment by Doppp** [comment]
Planning to fix this?
