### ISSUE TITLE
Typos/grammar in docs

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#339]
Typos/grammar: 
http://itch.io/docs/general/about 
>If you like what we're doing please help spread awareness itch.io.

http://itch.io/developers 
>And because it's your game page your won't find anything on it that you didn't put there. 
>Keep tabs on how people are viewing your game with detailed analytics convering views, downloads and purchases.

**Comment by leafo** [comment]
fixed :tangerine:
