### ISSUE TITLE
PayPal payment 

### ISSUE THREAD

**Issue by Devilooper** [itchio/itch.io#340]
Hey, 
I want to buy asset with PayPal, but simply I can't.
When I click "Checkout with PayPal", it tells me to enter my Billing address.
As I know, I should just enter my PayPal's login and password :/

https://itch.io/docs/creators/payments#paypal

**Comment by fasterthanlime** [comment]
The website is asking for your billing address because you're buying from a european IP address, so it needs to know that to collect EUVAT appropriately.
