### ISSUE TITLE
Unable to get to the WolfQuest game key 

### ISSUE THREAD

**Issue by ThePossum** [itchio/itch.io#349]
I downloaded WolfQuest game and everything and the game runs fine on single player, but I can't go to multiplayer. It says I have to login but I don't have an account so I tried registering but it says I need a key. So I followed the instruction and went to the download page but all that pops is is "Your PayPal purchase in pending." But I have already payed for WolfQuest but I can't get the key. I have tried everything the only thing I can think of on how to fix it is help from Itch.io but if not that I was going to try to buy it again but I decides to try this first.  I don't know if this is a bug or something. 

Please help me and see what you can do.

Sincerely,
ThePossum

**Comment by fasterthanlime** [comment]
@ThePossum can you send an e-mail to support@itch.io instead? Thanks! :stars:
