### ISSUE TITLE
I am Violence banning charges

### ISSUE THREAD

**Issue by jonaspeterson** [itchio/itch.io#358]
> violating terms of service
> distributing malware
> trying to game the sales system for exposure

I didn't do any of those things, what are you talking about?
Are you serious? 
Malware? Are you fucking serious?
>inb4 you close this issue too and don't reply to any of my emails
you're a fucking retard dude

**Comment by fasterthanlime** [comment]
Feeding trolls is bad, but I'm posting evidence here anyway for public record:

### Violating terms of service

Our terms of service (<http://itch.io/docs/legal/terms>):

![acceptable-use](https://cloud.githubusercontent.com/assets/7998310/13363881/1f7ef950-dccc-11e5-84e9-1fa67d0082f9.png)

What you uploaded:

![america](https://cloud.githubusercontent.com/assets/7998310/13363856/01a401dc-dccc-11e5-903e-7fb720a573a2.png)

### Distributing malware

Virustotal reports of the three files you uploaded to the site, all ~30MB .exe files:

  * https://www.virustotal.com/en/file/635deb5b0bece36db8d2624d16a289384c39567c552036b131a4133bf0744881/analysis/
  * https://www.virustotal.com/en/file/b5e9c9f2b80d9c16f9b0710a29947b9ffa99fe9462ade33c139befcc355b9551/analysis/1456418223/
  * https://www.virustotal.com/en/file/6acdc838f934eb9e481a0289e75779f0947be70fbc5a0f6a252a78f4832b633b/analysis/1456418229/

### Trying to game the sales system for exposure

Here's a 1% off bundle you made:

![bundle](https://cloud.githubusercontent.com/assets/7998310/13363957/7d19bf96-dccc-11e5-9a13-9279c371d0a3.png)

**Comment by jonaspeterson** [comment]
This is great, did you even look at the virus reports?
1/55
1/55
2/55
All three games were made with Gamemaker. I can send you the source codes to compile it yourself and then compare the hashes of the executables I put up on the site if you want.
Fucks sake, this is some serious mickey mouse bullshit.
I wont even bother commenting on the rest.
But don't accuse me of putting up malware dude, it's just plain dumb.

**Comment by Guard13007** [comment]
(It also seems to be promoting intolerance.)

@fasterthanlime How do you determine when the line has been crossed for promoting intolerance?
