### ISSUE TITLE
problematic downloads

### ISSUE THREAD

**Issue by VinnyVG** [itchio/itch.io#367]
I  have downloaded FR for Apple OS X - I use iMac running Yosemite.
When trying to open the FR app... it reports  the  app cannot be opened!   
As  FR is offered fro Apple OS x - one supposes it should  work with  current  Apple OS on a machine running current updated specidications and having  more than enough RAM and  HDD space.

**Comment by leafo** [comment]
Could you try it again, we had a temporary issue with downloads being canceled before they could finish.

**Comment by VinnyVG** [comment]
I  just downloaded again... more wasted quota connection !

It still does not work.

The Application  FPV Freerder cannot open - is the error message.



 
-- 


On 12 March 2016 at 10:40:57 AM, leaf (notifications@github.com) wrote:

Could you try it again, we had a temporary issue with downloads being canceled before they could finish.

**Comment by leafo** [comment]
Can you provide the exact message on the error dialog. It's possible that OSX's GateKeeper is preventing the unsigned application from opening. To ensure that there's no problem with the download you can also check the file size of what you downloaded, it should be what's listed on your download page.

**Comment by VinnyVG** [comment]
Did you not get the attached screen grab or read what I wrote?

-- 


On 12 March 2016 at 11:25:04 AM, leaf (notifications@github.com) wrote:

Can you provide the exact message on the error dialog. It's possible that OSX's GateKeeper is preventing the unsigned application from opening. To ensure that there's no problem with the download you can also check the file size of what you downloaded, it should be what's listed on your download page.

**Comment by leafo** [comment]
There's no screenshot on the GitHub issues tracker. If you want to email us an attachment you can contact us at support@itch.io, or provide the attachment on GitHub's web interface.

**Comment by VinnyVG** [comment]
Hi,

Sorry - I have contacted  the vendors and - wrongly - assumed it was they who answered.

The error message states - "The application "FPVFreerider.app can't be opened."

-- 


On 12 March 2016 at 11:30:37 AM, leaf (notifications@github.com) wrote:

There's no screenshot on the GitHub issues tracker. If you want to email us an attachment you can contact us at support@itch.io, or provide the attachment on GitHub's web interface.

**Comment by VinnyVG** [comment]
Sorry.. I was replying to emails and  did not know it was a forum reply!!
Situation is  no matter what i do or how many times I download FR - it will not open on  my iMac or mac Mini - both are uptodate and  there is around 400gig of disck space and always around 4gig of ram.

**Comment by leafo** [comment]
Hello,

Sorry about the delay. My guess is that it's related to OSX's Gatekeeper. If you contact us on our support email (support@itch.io) we can forward your message to the developer of the game.

Here's information on Gatekeeper and how to disable it: https://support.apple.com/en-us/HT202491

**Comment by VinnyVG** [comment]
Hi,

Thanks for  your reply.
I am aware of "Gatekeeper" and although trying to open   FR did not give any security warning...  one of the things I tried to get  it to open was to change  to  load apps from anywhere... it does not  change anything - the  app still reports it cannot be opened.
I have also  accepted that I am not the only person with  an Apple OS x system wanting to use FR... but if its an individual "fault" with my 21inch iMac - a 2011 iMac -  the same issue is on my 2016 purchased Mac Mini.

Regards

(  this is a reply  to an email - by an email)

-- 


On 16 March 2016 at 11:51:40 AM, leaf (notifications@github.com) wrote:

Hello,

Sorry about the delay. My guess is that it's related to OSX's Gatekeeper. If you contact us on our support email (support@itch.io) we can forward your message to the developer of the game.

Here's information on Gatekeeper and how to disable it: https://support.apple.com/en-us/HT202491

**Comment by leafo** [comment]
Hello again,

If you're still having trouble and haven't gotten in touch with the developers of FPV Freerider then send us an email, support@itch.io, and we can forward the issue to them. 

Sorry we can't help anymore. Since we don't develop the games we can only provide basic troubleshooting.

Thanks

**Comment by VinnyVG** [comment]
Hi,

I appreciate  its not itch's  problem and  it seems you support have/ will contact the developer.  Still the same will not  open  error report - even tried an my son in laws macbook.
Thanks for  your reply.... will get back if and when I know more.

-- 


On 26 March 2016 at 8:36:42 AM, leaf (notifications@github.com) wrote:

Hello again,

If you're still having trouble and haven't gotten in touch with the developers of FPV Freerider then send us an email, support@itch.io, and we can forward the issue to them.

Sorry we can't help anymore. Since we don't develop the games we can only provide basic troubleshooting.

Thanks

**Comment by simonvc** [comment]
I had this problem, but copying the .app bundle into /Applications fixed it.
