### ISSUE TITLE
game wont work

### ISSUE THREAD

**Issue by nighcat767** [itchio/itch.io#372]
I purchased wolfguest for $10.00 and when I down load it will not open I just keeping getting an error code then it wants to be deleted.  If this is how this game is going to be then I would just like my money back.  I would hate to loose my money on a game I bought for my daughter that she can not play when I could use the $10.00 on a game that she can play.  Thank you for your time

**Comment by fasterthanlime** [comment]
Hey @nighcat767, I'm sorry you're experiencing problems with wolfquest :(

The symptoms you describe sound a lot like OSX Gatekeeper: here's the official documentation page from Apple:

  * https://support.apple.com/en-us/HT202491

The section "How to open an app from a unidentified developer and exempt it from Gatekeeper" is particularly relevant.

**Comment by nighcat767** [comment]
I do not own an apple device.  The problem is when I try to download it on
to my computer.

**Comment by leafo** [comment]
Hello,

We can't troubleshoot the individual games. I suggesting geting in touch with the Wolfquest developers directly through their support page: http://www.wolfquest.org/bb/viewtopic.php?f=2&t=77658

If you're still having trouble getting in touch with them then send us an email to support@itch.io and we'll forward to them.

Thanks
