### ISSUE TITLE
Can't activate community and hide downloads

### ISSUE THREAD

**Issue by mrhelmut** [itchio/itch.io#376]
Hello,

We always had comments activated on our game page, but we recently noticed that they disappeared for no apparent reason (set back to "none"). When trying to set it to either "comments" or "discussion board", nothing happens.

We are also experiencing problems with hiding / setting platforms on some downloads.

For instance, on https://flyingoakgames.itch.io/neurovoider there are these downloads:
- NeuroVoider_Alpha21_Windows.zip 100 MB
- NeuroVoider_Alpha21_MacOS.zip 111 MB
- NeuroVoider_Alpha21_1_Windows.zip 100 MB
- NeuroVoider_Alpha21_1_MacOS.zip 111 MB

None of them has a platform (they did before) and when I tried to either set a platform, or hide them, nothing happens (at best) and sometimes it hides / shows other downloads, which loose their platform in the process. (this particular issue started to appear yesterday when uploading the files for Alpha22)

**Comment by leafo** [comment]
It looks like you have so many uploads that you've hit the max POST size on the web server and it's truncating the tail of the request. The community options are being truncated and so are being reset.

I see you have a lot of hidden files, are you planning on keeping these around for stats? Do you want your buyers to ever access them again? 

I've been thinking of adding an "archive" option for uploads that works like hidden, except it moves it off the main listing, lets you keep stats, and also gives buyers the option to access them through a separate section of the download page.

Is this something you'd want?

**Comment by mrhelmut** [comment]
D'oh!

We've been pondering on to give access to all these versions to early players, but I would totally understand that itch.io isn't the right place for this.

It's not for archiving or for stats. I'll simply clean everything then.

**Comment by mrhelmut** [comment]
I've cleaned everything. :+1:
