### ISSUE TITLE
Stuck on buying games

### ISSUE THREAD

**Issue by Espoiry** [itchio/itch.io#381]
Whenever i try to buy a game in beta 1.2.3 the game is stuck, i can't choose games or buy them or go back, i can't even close the game, i have to Ctrl+alt+del in order to close it, i can't find anyone else with this problem?

- i have tried reinstalling the game up to multiple times, but i can still only create films due to the fact that the game won't allow me to buy games

**Comment by leafo** [comment]
We have a separate issues tracker for the app: https://github.com/itchio/itch/issues

**Comment by Espoiry** [comment]
Ok thanks
