### ISSUE TITLE
payment

### ISSUE THREAD

**Issue by duke4life18** [itchio/itch.io#386]
so i payed for a game and its saying that my zip code is wrong how ever i checked my card and its saying that the payment is being processed soooo what do i do

**Comment by fasterthanlime** [comment]
Hey @duke4life18, could you send an e-mail to support@itch.io with a link to the page you tried to purchase? I'm sorry you went to the trouble of signing up for GitHub, but this place really isn't for private information.

Also, generally speaking:

  * Banks sometimes show 'pre-authorization' transactions that later disappear (we obviously wouldn't be charging you despite the error message)
  * If the charge remains, I'm confident our payment system will let us know, and you will receive an e-mail with your download link
  * If the charge remains for a few days and you still haven't gotten your download e-mail, then we can look deeper into what happened!

Cheers,
- Amos
