### ISSUE TITLE
Notification marked as old before I have seen it

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#392]
On mobile (Chrome on Android), I went to the site and saw I had a notification. When I opened notifications, the new notification was grouped with old notifications instead of separate.

**Comment by leafo** [comment]
If you view the piece of content related to the notification then it will be marked as read. So, for example, if you got a reply in the community, and you go view the reply, then it would clear the notification even though you haven't loaded the notifications page.

Is this what happened? If you don't think so, what kind of notifcation was it?

**Comment by Guard13007** [comment]
I loaded the jams page or the page of the jam (the notification was for a reply in the community of lowrezjam2016), so I do not think I loaded the actual thread. Next time I will pay closer attention to see which of those might be what I did.

**Comment by leafo** [comment]
There's now a notification link on the header, so even if you miss something you should be able to easily go back. Going to close this for now. Feel free to re-open if you're encountering an issue.
