### ISSUE TITLE
linux dumping core when assigning joysticks ( I sent the core file to the support email ) 

### ISSUE THREAD

**Issue by jsheffie** [itchio/itch.io#395]
.......................................................................
 ./FPVFreerider_Recharged.x86_64 
Set current directory to /home/jds/FPVFreerider_Linux_April_15_2016
Found path: /home/jds/FPVFreerider_Linux_April_15_2016/FPVFreerider_Recharged.x86_64
Mono path[0] = '/home/jds/FPVFreerider_Linux_April_15_2016/FPVFreerider_Recharged_Data/Managed'
Mono path[1] = '/home/jds/FPVFreerider_Linux_April_15_2016/FPVFreerider_Recharged_Data/Mono'
Mono config path = '/home/jds/FPVFreerider_Linux_April_15_2016/FPVFreerider_Recharged_Data/Mono/etc'
displaymanager : xrandr version warning. 1.4
client has 5 screens
displaymanager screen (0)(DVI-0): 1920 x 1080
displaymanager screen (1)(HDMI-0): 1920 x 1080
Using libudev for joystick management

Importing game controller configs
/dev/input/js0: driver version: 2.1.0 (20100)
/dev/input/js0: fd 4, buttons 8, axes 8, name FrSky FrSky Taranis Joystick
/dev/input/js0: axis  0: raw      0, mapped 0.000000
/dev/input/js0: axis  1: raw      0, mapped 0.000000
/dev/input/js0: axis  2: raw      0, mapped 0.000000
/dev/input/js0: axis  3: raw      0, mapped 0.000000
/dev/input/js0: axis  4: raw      0, mapped 0.000000
/dev/input/js0: axis  5: raw      0, mapped 0.000000
/dev/input/js0: axis  6: raw      0, mapped 0.000000
/dev/input/js0: axis  7: raw      0, mapped 0.000000
Assigning joystick 1
Aborted (core dumped)

................................................

**Comment by fasterthanlime** [comment]
hey, please try the FPV freerider community instead: https://fpv-freerider.itch.io/fpv-freerider/community — this is a bug tracker for the itch.io website.
