### ISSUE TITLE
Suggestion: display version number for wharf uploads

### ISSUE THREAD

**Issue by mrhelmut** [itchio/itch.io#398]
Hello,

I would find useful to show the version number of builds uploaded with butler on game pages.
Or alternatively itchio/butler#28 (which I believe would be more relevant, because users would be able to sort/compare their downloads by version number if they downloaded a game multiple times -- and most of the itch community seems to use display names to handle version numbers --).

**Comment by Chaser324** [comment]
Theoretically, if more users start using the itch.io client, this will be less of an issue, but I do agree that in the past I've always included a version number or timestamp in the upload name so that users can identify if they have the latest build.

**Comment by fasterthanlime** [comment]
Just wanted to note that, like many other requests in this bug tracker, this is a really easy fix 👍 

We're currently working really hard on a particular deadline, and I'll need some time off after that, but I'm looking forward to finish polishing all the little rough edges.

**Comment by leafo** [comment]
They will now show on download pages (along with date): https://twitter.com/itchio/status/734480470843351040

**Comment by HarmonyHoney** [comment]
can i hide the version number on my game's page?
