### ISSUE TITLE
Cannot share link while 'published' is private; cannot download unless 'published' is private; 'private club'

### ISSUE THREAD

**Issue by JeroenDStout** [itchio/itch.io#400]
Some curious behaviour with sharing links and published status:

If a game page is set to ​**private**​, download links cannot be used, so the game cannot be attached to an account.

If the page is set to **​public restricted​**, download links can be used and the game attached to an account, but the game cannot actually be downloaded.

If the download link is claimed and *then* the page is set to ​**private**​ again, the game can be downloaded by the person who claimed it!

Beyond the curious nature of this, it may be useful to have a "private club" option which allows no regular downloads or pageviews (as in private) but still allows attaching the game to another account (as in public restricted).

**Comment by leafo** [comment]
We've recently reworked how the privacy settings work, there's more information here: https://itch.io/docs/creators/access-control
