### ISSUE TITLE
Activity Summary Lies (Wrong Download Count)

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch.io#402]
On my dashboard, the activity summary shows 0 downloads for Friday, April 15th. But when I look at my game pages, almost all of them show at least 1 download on that day:

![itch io activity summary downloads](https://cloud.githubusercontent.com/assets/227734/14736578/1d50ed16-0835-11e6-93df-6f1d80190496.png)

![itch io ad downloads](https://cloud.githubusercontent.com/assets/227734/14736460/7bff4836-0834-11e6-9cab-7309fcd0acb4.png)

![itch io btw downloads](https://cloud.githubusercontent.com/assets/227734/14736478/9b58bf14-0834-11e6-9487-05a93158e5ba.png)

![itch io blast downloads](https://cloud.githubusercontent.com/assets/227734/14736493/b6325f84-0834-11e6-9165-4cc667cf49bf.png)

Plus several more. Why is my dashboard lying to me about the downloads?

**Comment by leafo** [comment]
looks like the graph on the main dashboard page is not showing values for the first day on the chart! I fixed it
