### ISSUE TITLE
Updating game doesn't update in app.

### ISSUE THREAD

**Issue by SkyTech6** [itchio/itch.io#403]
I go to my game's edit game page, delete the old zip, and put in a new one. 

Then I go to the Itch app, and it doesn't update the newest version, the only way to do it is completely uninstalling the game and then reinstalling.

Game in Question: https://fishagon.itch.io/stand-your-ground

**Comment by fasterthanlime** [comment]
Hey @SkyTech6, I just released v15.0.0 of the app, can you upgrade & check if it's still a problem with it? With that version, it should check for game updates:

  * On app start-up
  * Every 30 minutes
  * If you right-click a game's tab & pick Developer -> Check for updates

**Comment by SkyTech6** [comment]
@fasterthanlime 

Hey Amons! Thanks for the update, it actually fixed a good bit of games that didn't even launch previously. 

However as to this problem, it fixed the game not updating but has revealed a new one to me that is pretty unrelated. 

I know it's a "developer level" issue, but do you know if launching via your program would interfere with an Operating System check? (Or if you'd like, I could ask in a new issue ticket?)

**Comment by fasterthanlime** [comment]
> do you know if launching via your program would interfere with an Operating System check?

What kind of operating system check are we talking about?

**Comment by SkyTech6** [comment]
> What kind of operating system check are we talking about?

Hm, well I'm not exactly sure as it's behind Unity's API wall. But if you're familiar it's a call that can be used to check what the user is currently on. Such as this:

`if(Application.platform == WindowsPlayer)
//do stuff`

This works fine on my game alone, but downloading it via the app seems to have completely caused that check to return null. 

I'll try looking into how Unity checks platform.

**Comment by fasterthanlime** [comment]
@SkyTech6 hmm, interesting. I haven't seen any similar reports to this, and the app is basically running an .exe (if your game is an Unity windows export, not an HTML5 exports - that's a different thing, but not what you're talking about right?)

**Comment by SkyTech6** [comment]
@fasterthanlime Correct, it's a windows export. However with my update of platform checking I added OS X support as well. 

Which the app on OS X did successfully check for platform.

**Comment by SkyTech6** [comment]
@fasterthanlime Unity games on Windows do some file placement in the HKCU, your application wouldn't stop and try to put them in a different folder, would it?

**Comment by fasterthanlime** [comment]
@SkyTech6 nope. All it really does is extract the .zip, launch the .exe. You can open the game's install location (dropdown menu) and launch it yourself

**Comment by SkyTech6** [comment]
@fasterthanlime I may have spoke too soon. I thought since your application had their own install location, that the playerprefs would be different between the application version of the game and my testing one. 

However, strangely, they shared PlayerPrefs and my other game's settings were affecting this one. Completely bypassing the platform check.

**Comment by fasterthanlime** [comment]
@SkyTech6 ah yes, preferences are probably stored under `%AppData%`.

I assume it's safe to close this issue now?

**Comment by SkyTech6** [comment]
@fasterthanlime actually, they are strangely stored in the registry. So to delete them you'd have to open regedit, so every build I have to go in that high risk section of the file hierarchy to delete the file. 
----

Yep. Safe to close.

**Comment by fasterthanlime** [comment]
> actually, they are strangely stored in the registry.

Is that a default Unity feature or a plug-in ? I've been thinking about providing a canonical place to store preferences so that they could be cloud sync'd

**Comment by SkyTech6** [comment]
@fasterthanlime It's the default for Unity games on Windows. 

Here's where they save playerprefs (and other things like your resolution settings and whatnot) for each platform including web-based.

http://docs.unity3d.com/ScriptReference/PlayerPrefs.html

**Comment by Guard13007** [comment]
> a canonical place to store preferences

What kind of preferences?

**Comment by Deozaan** [comment]
@SkyTech6 You can easily erase all PlayerPrefs with [PlayerPrefs.DeleteAll()](http://docs.unity3d.com/ScriptReference/PlayerPrefs.DeleteAll.html)

But PlayerPrefs isn't how/where you should be writing important save data. It's OK for unimportant things (such as resolution, fullscreen/windowed, etc.) which can easily be configured again if they're lost. But save data definitely needs to go somewhere the player can find it and make backups if necessary. Such as [Application.persistentDataPath](http://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html)
