### ISSUE TITLE
[Minor] My Creations Downloading Screen Shake

### ISSUE THREAD

**Issue by SkyTech6** [itchio/itch.io#405]
When downloading a game from "My Collections" it makes a lot of the UI shake pretty rapidly until the download is complete. 

I took a gif for your reference: 
https://gyazo.com/32cffbeb0c630d27f4868584536096f2

Due note the gif highly understates it due framedrop in gifs. It's much quicker and much more shaking.

**Comment by fasterthanlime** [comment]
Should be fixed in the net stable release. By the way, https://github.com/itchio/itch is technically the right place to report bugs with the app :)

**Comment by SkyTech6** [comment]
@fasterthanlime Opps sorry Amons, I didn't know there were two different bug tracking places. My bad.
