### ISSUE TITLE
indexedDB fails when inside an iframe from other domains

### ISSUE THREAD

**Issue by wesleywerner** [itchio/itch.io#406]
I am duly unsure if this issue belongs here, if so I'll understand if this issue is closed, if at least documented.

I have a browser-based game that runs circumstantially in the itch.io iframe. When I open the iframe in it's own window it works. So the issue is likely the cross-browser policy to limit db access. The specific error is:

```
TypeError: IDBFS.indexedDB(...) is null
```

I set up this [test project](https://celestial.itch.io/testproject?secret=nwjhd2OFavqqfcCc9lf1IU8ng) to test this further, and if you open the iframe in [it's own window](https://commondatastorage.googleapis.com/itchio/html/198860/index.html) the game runs.

It is only my suspicion that the cross-domain policy is the cause of this, but I would love some feedback if this is indeed solvable.

I kept digging and found [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=595307), based off [this w3 standard](http://www.w3.org/TR/IndexedDB/#user-tracking), that leads to this Mozilla setting, which did not in fact make any difference:

> Third party window content (e.g. content) can access the IndexedDB store for the origin it is embedded into, unless the browser is set to never accept third party cookies
> https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Security

At this point my brain is jellied and hoping for the best.

**Comment by leafo** [comment]
Indexdb will not be available if third party cookies are disabled when origin of frame doesn't match parent. They're disabled by default with private browsing in most browsers. HTML file games will always be on another domain for security reasons, so I'm not sure if there's a fix I can do.
