### ISSUE TITLE
Unity WebGL server responded with a status of 404

### ISSUE THREAD

**Issue by kunal01** [itchio/itch.io#409]
Hello
I uploaded zip file of Unity WebGl game.
And when I open my game page it shows these error in console of browser
**https://commondatastorage.googleapis.com/itchio/html/202367/ShapeClimb%20Itch/Release/ShapeClimb%20Itch.js Failed to load resource: the server responded with a status of 404 ()
UnityLoader.js:1 Decompressed Release/ShapeClimb Itch.memgz in 160ms. You can remove this delay if you configure your web server to host files using gzip compression.**
And I also can't see progress bar of my game.
So please help me to solve these.

**Comment by leafo** [comment]
it looks like you only uploaded gz files, and the unity webgl environment is trying to load the .js files first.

**Comment by kunal01** [comment]
Hello @leafo 
I zipped the folder which Unity generates after build successful & uploaded it.
In this folder there is UnityLoader.js file.
So what is the problem?

**Comment by thelucre** [comment]
Having the same problem. I uploaded a `.zip` with an `index.html` file and a `Release` folder. 404 thrown when requesting `{{my game path}}/Release/UnityLoader.js`

**Comment by leafo** [comment]
@thelucre are you still having an issue? Can you point me to your itch.io account so I can take a look.

**Comment by kunal01** [comment]
@leafo 
Yes I am still having an issue.
My account name is kunal01.

**Comment by kingdomseed** [comment]
I am having the same issue with my game and my students games: kingdomseed.itch.io, lewisstone85.itch.io, abigaylebrooks.itch.io, kronosreaper.itch.io, cinn_senpai.itch.io. Uploaded all WebGL games with index.html in the root. 
![itchio](https://cloud.githubusercontent.com/assets/9125535/19654576/88bbf880-99de-11e6-9cc1-716246696712.png)

**Comment by leafo** [comment]
Hey @kingdomseed, I'm not able to reproduce the issue right now. Does it happen in other browsers? Just to rule out the network you're on, you're not going through a proxy or anything like that right?

Here are the games I've tested:

https://abigaylebrooks.itch.io/class-escape
https://lewisstone85.itch.io/the-story-of-harmbe-

(The other two accounts you listed have no games on their account)

**Comment by kingdomseed** [comment]
It seems that there is something on my schools network blocking this. I am not sure how to chase it down but I control the filter so I will have a look around. Thanks and sorry about this.
