### ISSUE TITLE
NSFW content recommended, despite preferences

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch.io#410]
NSFW games show up in the "Recommended for you" section, despite settings asking not to show NSFW content.

![itch io nsfw setting](https://cloud.githubusercontent.com/assets/227734/15057304/67840ee2-12d3-11e6-949b-a0189ba83745.png)

![itch nsfw](https://cloud.githubusercontent.com/assets/227734/15057310/6ffe70ee-12d3-11e6-880f-44a8c18d85a7.png)

I'm not sure if it's because of:

1. The content creator did not properly flag his game as being NSFW (which means we need to have a way to flag games as NSFW).
2. The "Recommended for you" section doesn't obey preferences.
3. Maybe the Recommended section is curated by Itch staff so it doesn't take individual preferences into account?

It may also be useful to have a "Not Interested" button so that it stops recommending certain games to people who aren't interested in them.

Along those lines, it may also be interesting/useful to be able to have a "Why did you recommend this to me?" feature.

**Comment by fasterthanlime** [comment]
1. in this case, the game is correctly flagged as NSFW (by user)
2. that seems to be it
3. nope, just an algorithm

> Along those lines, it may also be interesting/useful to be able to have a "Why did you recommend this to me?" feature.

:+1: although I'm not sure how hard this would be to do

**Comment by leafo** [comment]
"Why did you recommend this to me" is tough, there are a few layouts of abstraction in the algorithm and that information gets lost along the way.

I fixed the main bug in any case.

**Comment by Deozaan** [comment]
I can confirm that the NSFW game no longer shows up in the Recommended section. Thanks!

**Comment by Deozaan** [comment]
I can confirm that the NSFW game no longer shows up in the Recommended section. Thanks!

**Comment by Deozaan** [comment]
I can confirm that the NSFW game no longer shows up in the Recommended section. Thanks!

**Comment by zulqurnain34** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\pc\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\pc\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


https://www.agriturismo-pisa.it/agrisite2.php?idagri=3461&possito=1041&chref=https://qxefv.info/
--
https://tributes.goulburnpost.com.au/obituaries/137122/patricia-marie-osmond/?r=https://qxefv.info/
https://tributes.thecourier.com.au/obituaries/138733/tony-re/?r=https://qxefv.info/
https://tributes.theadvocate.com.au/obituaries/437831/eric-stanley-joe-peck/?r=https://qxefv.info/
https://tributes.theage.com.au/obituaries/138576/anthony-francis-re/?r=https://qxefv.info/
https://tributes.theadvocate.com.au/obituaries/437831/eric-stanley-joe-peck/?r=https://qxefv.info/
https://pravoslavie-forum.org/proxy.php?link=https://qxefv.info/&_debug=1
https://identity.oha.com/account/ForgotPassword?returnUrl=https%3A%2F%2Fqxefv.info%2F
https://www.manyzone.com/member/sign-up.aspx?returnURL=https://qxefv.info/
https://www.putneysw15.com/default.asp?section=info&link=https://qxefv.info/
https://www.tomcorf.com/?URL=https://qxefv.info/
http://chillicothechristian.com/System/Login.asp?id=55378&Referer=https%3A%2F%2Fqxefv.info%2F
https://www.3vids.com/cgi-bin/a2/out.cgi?id=18&l=text_top&u=https://qxefv.info/
https://borjomi.tv/a/www/delivery/ck.php?ct=1&oaparams=2__bannerid=53__zoneid=27__cb=1679f4fa96__oadest=https://qxefv.info/
http://portal.darwin.com.br/gerenciamentousuarios/CadastrarDadosAlunoForm.aspx?url=https://qxefv.info/
https://www.ealingtoday.co.uk/default.asp?section=info&link=https://qxefv.info/
https://www.actonw3.com/default.asp?section=info&link=https://qxefv.info/
https://www.konsalko-nn.ru/bitrix/redirect.php?goto=https://qxefv.info/
http://www.peacememorial.org/System/Login.asp?id=52012&Referer=https%3A%2F%2Fqxefv.info%2F
https://wartank.ru/?0-1.ILinkListener-showSigninLink&channelId=30152&partnerUrl=https://qxefv.info/
http://renault-kaptur.su/redirect/?url=https://qxefv.info/
https://www.thetartangroup.com.au/?URL=https://qxefv.info/
https://romhacking.net.ru/go?https://qxefv.info/
https://www.carbonafrica.co.ke/?mobileview_switch=mobile&redirect=https://qxefv.info/
https://aloitus.net/click.php?type=link&id=5ca1f246b73d1&to=https://qxefv.info/
https://www.localmeatmilkeggs.org/facebook.php?URL=https://qxefv.info/
https://lawsociety-barreau.nb.ca/?URL=https://qxefv.info/
https://www.brentfordtw8.com/default.asp?section=info&link=https://qxefv.info/
https://www.delta-xray.net/redir.php?URL=https://qxefv.info/
https://www.bausch.com.sg/redirect/?Url=https://qxefv.info/
https://stazionedellarte.com/?URL=https://qxefv.info/
https://www.mrdr.net.au/?URL=https://qxefv.info/
https://nbbank.com/Leaving-Site?ts=1614204838430&url=https://qxefv.info/
https://www.cafeteriatrend.hu/?URL=https://qxefv.info/
https://carolands.org/?URL=https://qxefv.info/
https://www.cardtrack.com.br/sistema/AbpLocalization/ChangeCulture?cultureName=en&returnUrl=https://qxefv.info/
https://freeadvertisingforyou.com/mypromoclick.php?aff=captkirk&url=https://qxefv.info/
http://www.lanarkcob.org/System/Login.asp?id=45268&Referer=https%3A%2F%2Fqxefv.info%2F
https://schwarzreport.org/?URL=https://qxefv.info/
https://store.pobedavkusa.com/bitrix/redirect.php?goto=https://qxefv.info/
https://crandallconsult.com/?URL=https://qxefv.info/
https://smi-re.jp/contact/index.php?name=ASY&url=https://qxefv.info/
https://www.1erforum.de/proxy.php?link=https://qxefv.info/
https://www.spacoimoveis.com.br/banner/vai.asp?id=5&url=https://qxefv.info/
https://haroldmitchellfoundation.com.au/?URL=https://qxefv.info/
https://www.mambolearn.com/go.php?url=https://qxefv.info/
https://www.infodrogy.sk/poradna/sprava/538?returnURL=https://qxefv.info/
https://www.nurenergie.com/modules/babel/redirect.php?newlang=fr_FR&newurl=https://qxefv.info/
https://www.xpgamesaves.com/proxy.php?link=https://qxefv.info/
https://www.qcyc.ca/?q=node/109&height=730&scroll=auto&url=https://qxefv.info/



</body>

</html>
https://www.agriturismo-pisa.it/agrisite2.php?idagri=3461&possito=1041&chref=https://qxefv.info/
https://tributes.goulburnpost.com.au/obituaries/137122/patricia-marie-osmond/?r=https://qxefv.info/
https://tributes.thecourier.com.au/obituaries/138733/tony-re/?r=https://qxefv.info/
https://tributes.theadvocate.com.au/obituaries/437831/eric-stanley-joe-peck/?r=https://qxefv.info/
https://tributes.theage.com.au/obituaries/138576/anthony-francis-re/?r=https://qxefv.info/
https://tributes.theadvocate.com.au/obituaries/437831/eric-stanley-joe-peck/?r=https://qxefv.info/
https://pravoslavie-forum.org/proxy.php?link=https://qxefv.info/&_debug=1
https://identity.oha.com/account/ForgotPassword?returnUrl=https%3A%2F%2Fqxefv.info%2F
https://www.manyzone.com/member/sign-up.aspx?returnURL=https://qxefv.info/
https://www.putneysw15.com/default.asp?section=info&link=https://qxefv.info/
https://www.tomcorf.com/?URL=https://qxefv.info/
http://chillicothechristian.com/System/Login.asp?id=55378&Referer=https%3A%2F%2Fqxefv.info%2F
https://www.3vids.com/cgi-bin/a2/out.cgi?id=18&l=text_top&u=https://qxefv.info/
https://borjomi.tv/a/www/delivery/ck.php?ct=1&oaparams=2__bannerid=53__zoneid=27__cb=1679f4fa96__oadest=https://qxefv.info/
http://portal.darwin.com.br/gerenciamentousuarios/CadastrarDadosAlunoForm.aspx?url=https://qxefv.info/
https://www.ealingtoday.co.uk/default.asp?section=info&link=https://qxefv.info/
https://www.actonw3.com/default.asp?section=info&link=https://qxefv.info/
https://www.konsalko-nn.ru/bitrix/redirect.php?goto=https://qxefv.info/
http://www.peacememorial.org/System/Login.asp?id=52012&Referer=https%3A%2F%2Fqxefv.info%2F
https://wartank.ru/?0-1.ILinkListener-showSigninLink&channelId=30152&partnerUrl=https://qxefv.info/
http://renault-kaptur.su/redirect/?url=https://qxefv.info/
https://www.thetartangroup.com.au/?URL=https://qxefv.info/
https://romhacking.net.ru/go?https://qxefv.info/
https://www.carbonafrica.co.ke/?mobileview_switch=mobile&redirect=https://qxefv.info/
[https://aloitus.net/click.php?type=link&id=5ca1f246b73d1&to=https://qxefv.info/](https://aloitus.net/click.php?type=link&id=5ca1f246b73d1&to=https://techbizvibe.com/)
https://www.localmeatmilkeggs.org/facebook.php?URL=https://qxefv.info/
https://lawsociety-barreau.nb.ca/?URL=https://qxefv.info/
https://www.brentfordtw8.com/default.asp?section=info&link=https://qxefv.info/
https://www.delta-xray.net/redir.php?URL=https://qxefv.info/
https://www.bausch.com.sg/redirect/?Url=https://qxefv.info/
https://stazionedellarte.com/?URL=https://qxefv.info/
https://www.mrdr.net.au/?URL=https://qxefv.info/
https://nbbank.com/Leaving-Site?ts=1614204838430&url=https://qxefv.info/
https://www.cafeteriatrend.hu/?URL=https://qxefv.info/
https://carolands.org/?URL=https://qxefv.info/
https://www.cardtrack.com.br/sistema/AbpLocalization/ChangeCulture?cultureName=en&returnUrl=https://qxefv.info/
https://freeadvertisingforyou.com/mypromoclick.php?aff=captkirk&url=https://qxefv.info/
http://www.lanarkcob.org/System/Login.asp?id=45268&Referer=https%3A%2F%2Fqxefv.info%2F
https://schwarzreport.org/?URL=https://qxefv.info/
https://store.pobedavkusa.com/bitrix/redirect.php?goto=https://qxefv.info/
https://crandallconsult.com/?URL=https://qxefv.info/
https://smi-re.jp/contact/index.php?name=ASY&url=https://qxefv.info/
https://www.1erforum.de/proxy.php?link=https://qxefv.info/
https://www.spacoimoveis.com.br/banner/vai.asp?id=5&url=https://qxefv.info/
https://haroldmitchellfoundation.com.au/?URL=https://qxefv.info/
https://www.mambolearn.com/go.php?url=https://qxefv.info/
https://www.infodrogy.sk/poradna/sprava/538?returnURL=https://qxefv.info/
[https://www.nurenergie.com/modules/babel/redirect.php?newlang=fr_FR&newurl=https://qxefv.info/](https://www.nurenergie.com/modules/babel/redirect.php?newlang=fr_FR&newurl=https://techbizvibe.com/)
https://www.xpgamesaves.com/proxy.php?link=https://qxefv.info/
https://www.qcyc.ca/?q=node/109&height=730&scroll=auto&url=https://qxefv.info/
