### ISSUE TITLE
`has_demo` field

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#411]
For cases like https://itch.io/api/1/me/game/50878, it'd be useful to have an `has_demo` field so the app could let a user install the demo and/or buy. Right now the app just goes by `min_price`, which is non-zero, so if you don't own it, it wants you to buy it.

**Comment by fasterthanlime** [comment]
cf. https://github.com/itchio/itch/issues/385

**Comment by fasterthanlime** [comment]
still relevant

**Comment by leafo** [comment]
Now deployed
