### ISSUE TITLE
Private page + secret URL = no downloads possible

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#419]
Not sure if it's a bug and how it's going to work with new access levels, but currently: if you give out a secret URL to, say, patreon backers, they won't be able to download it (purchase popup won't load b/c it returns 404).

**Comment by leafo** [comment]
It's kinda intentional, but not very clear. Things will be a lot more flexible and well described this Friday. Essentially private is actually draft mode, so everything should be disabled except for those who can edit the page.

**Comment by Guard13007** [comment]
> Things will be a lot more flexible and well described this Friday.

Ooooh. :D Hinting at something, eh?

**Comment by leafo** [comment]
All set now
