### ISSUE TITLE
Feature Request - Method to view metadata on a game page?

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#422]
Could we have a drop-down button or tab or something to view metadata on a game?

I went to check out [a random game](https://quadolorgames.itch.io/cat-like-shopping-detected) because that bot that tweets new Itch.io games tweeted it, and learned the hard way that it only supports Xbox controllers. It'd be nice to have the metadata accessible somewhere besides search so I could check for such things.

(It looks like this creator didn't add the metadata either, but that's beside the point.)

**Comment by leafo** [comment]
Sure thing. I'm trying to think about how I want to add this without be obtrusive on existing game page designs. I think the the most conservative thing I can do is add a little popup card with all the details that can be opened by clicking a link on the footer.

The downside is that it's the kind of thing that won't get discovered except by people looking for it. I've already received enough complains about how hard it is to get to a developer page from the game pages.

A potential solution is to make this card an optional thing that can show up above the screenshot area. Still thinking about it, probably won't get anything out during itch.io week but I want to have something soon.

**Comment by felixplesoianu** [comment]
Why not a card below the description, before the download button? Or for that matter after the download button, right before the comments, that can get arbitrarily long? It makes sense when reading the page too: "Here's the game author's informal description. And now, for some stats."

**Comment by fasterthanlime** [comment]
The 'More information' link does that now :)
