### ISSUE TITLE
Email verification needed for every steam key purchase.

### ISSUE THREAD

**Issue by psymin** [itchio/itch.io#429]
From this page:
https://evilindiegames.itch.io/no-thing

I clicked "buy now".
I add in a dollar or so.
I click the "bitcoin" option.
I send the appropriate amount to the specified address.
Payment is accepted and I'm redirected to a "thank you" page with download links.
I click on the "Claim Steam key" button.
I verify the email address.
I'm get the steam key and redeem it.

This process seems to be repeated for every purchase I've made today for linux games with steam keys paid for using bitcoin.  I have not made any other types of purchases through itch today.

Is there something I'm missing that will allow me to only verify my email once?

Edit:  System info:

OS: Gentoo x86_64
Browser: Chrome 48.0.2564.103_p1
Personal Itch page: https://psymin.itch.io

**Comment by psymin** [comment]
Today I've purchased the following games and had to verify the email for steam keys:

Airships: Conquer the Skies
And So It Was
Rocket Fist
NO THING
.. and a bundle containing Cube Land Arena

I'll go through the same process for Dungeon Rushers when it is available for sale.

**Comment by leafo** [comment]
If you verify your account's email address then you'll no longer need to individually verify each purchase.

**Comment by psymin** [comment]
I had assumed that the email verification was the process I had been going through.  It appears that it wasn't.  Thanks for pointing this out.  It works now.
