### ISSUE TITLE
Main analysis graph and sub graphs for each game.

### ISSUE THREAD

**Issue by Arowx** [itchio/itch.io#43]
OK Imagine the analysis screen with a main graph on the top, then with two columns, one for the game info on the left and on the right that games graph.  

This would allow people with a few games to see what games people are playing without needing to check each game individually.

**Comment by leafo** [comment]
This is addressed in the new graph style: http://blog.itch.io/post/144762257104/graphs-upgraded-even-more-you-can-hover-over
