### ISSUE TITLE
New Widget: (Un)Checking the "Include link to itch.io page" resets widget colors to default

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch.io#430]
I was playing around with the new widget settings. Whenever I check or uncheck the "Include link to itch.io page" it changes the colors back to the default for the preview. And the button for whatever settings it was on before (dark or "your page style") doesn't update the preview unless you click another theme first.

The code shown to copy/paste is still correct. Just the preview gets messed up.

**Comment by leafo** [comment]
What browser? I'm testing in chrome and firefox (on linux) with no issues, the colors are restored after refreshing after toggling the link.

**Comment by Deozaan** [comment]
I experienced it in Chrome, but didn't test in other browsers. That said, it's working for me now. I guess maybe it has already been fixed or it was just a random hiccup somewhere along the line.

I can no longer reproduce the issue.
