### ISSUE TITLE
Cover image is broken in widget

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch.io#431]
I'm no longer seeing the "cover" image for my game in the widget:

It's not showing in the preview on the widget customization page:
![itch widget preview](https://cloud.githubusercontent.com/assets/227734/15158634/115c6f8a-16ae-11e6-873d-f3544dca4579.png)

And it's not showing on my website with the old widget code:
![itch widget website](https://cloud.githubusercontent.com/assets/227734/15158636/12a6bc7e-16ae-11e6-8dba-9402e218b4cf.png)

**Comment by Deozaan** [comment]
Now it's working for me. Maybe it was just a server hiccup.

**Comment by fasterthanlime** [comment]
img.itch.io was down for a short time today
