### ISSUE TITLE
Key claimed date shows when key was generated(?), not when it was claimed.

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch.io#436]
I claimed a key about an hour ago, but the game page tells me I claimed it 23 hours ago. My guess is that the key was generated/created about 23 hours ago, and that's the date/time it is using when it tells me when I claimed it.

![itch key claimed](https://cloud.githubusercontent.com/assets/227734/15230651/fa63cd76-1853-11e6-8f55-1ceb62d33854.png)

Admittedly, in a couple of years I'm not going to care that the date I claimed the game was off by 22 hours, but it's still a bit weird and confusing to see while the details are fresh in my memory.

**Comment by leafo** [comment]
should be fixed now
