### ISSUE TITLE
The new views and downloads graphs are not displaying correctly.

### ISSUE THREAD

**Issue by CowThing** [itchio/itch.io#438]
The numbers on the left side are cut off, and the graphs themselves are moved way off to the left side. I'm using Firefox 46.0.1

Dashboard:
![Dashboard](http://i.imgur.com/ah5En2a.png)

Analytics page:
![Analytics](http://i.imgur.com/zjM6Ok8.png)

**Comment by Deozaan** [comment]
I can confirm similar behavior in Firefox.

**Comment by rsjaes** [comment]
same problem
![analytics - itch io - mozilla firefox](https://cloud.githubusercontent.com/assets/16105807/15269042/b952f1b8-19c0-11e6-898a-026864f034be.jpg)

**Comment by matriax** [comment]
Same here!, using FIrefox last version.

**Comment by leafo** [comment]
Sorry about that, everything should be fixed now, and I revamped them a bit.
