### ISSUE TITLE
Exclusive Content contradiction

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch.io#449]
Near the top of the page of the [Exclusive Content documentation](https://itch.io/docs/creators/exclusive-content) it says:

> itch.io does not track or guarantee the fulfillment of rewards

But then near the bottom of the page it also says:

> Rewards that have been bought are a different story: they must remain in our database so we can track fulfillment.

These statements contradict each other.

**Comment by leafo** [comment]
hmm, the "track" in the first sentence is supposed to refer to us watching the developer to make sure they do what they need to do to send it. I think it's probably redundant, guarantee should be good enough. It's been updated.
