### ISSUE TITLE
Potential security issue with password field in restricted access settings

### ISSUE THREAD

**Issue by tesselode** [itchio/itch.io#456]
The form I'm talking about is this one:
![a](https://cloud.githubusercontent.com/assets/2637802/15526284/e28f9d88-21fe-11e6-9319-f05969d32316.PNG)
If you focus the field, the password displays as text:
![b](https://cloud.githubusercontent.com/assets/2637802/15526301/ffaab22c-21fe-11e6-9f1c-076a600b0c4d.PNG)
By default, this password is your actual itch.io password. I'm no expert on security, but it seems kind of bad that you can just click there and reveal your itch.io password. Also, why does it default to your itch.io password, anyway? That password is pretty much always going to be used to share your game with other people, and you wouldn't want to share your account password with anybody.

**Comment by fasterthanlime** [comment]
Definitely browser auto-fill (we don't store your password server side obviously) - we gotta use fields to prevent auto fill and change the input name

**Comment by leafo** [comment]
I've removed autocomplete from that password field. Sorry for the confusion.

**Comment by tesselode** [comment]
Ah, that makes sense. Thanks for the fix!

**Comment by fasterthanlime** [comment]
This is still happening (despite `autocomplete=off`) — chrome is very insistent. I still recommend changing the 'name' of the field, as I think it's the only thing chrome will respect.

see https://itch.io/t/25607/restricted-page-password-gets-overwritten-on-edit

**Comment by leafo** [comment]
bleh, bummer. I deployed a fix from here: http://stackoverflow.com/questions/15738259/disabling-chrome-autofill
