### ISSUE TITLE
URLs of external file uploads fail to shift up when removing external files

### ISSUE THREAD

**Issue by bjorn** [itchio/itch.io#460]
Steps to reproduce:

* Create a new project
* Give it a name
* Add external file A with URL A
* Add external file B with URL B
* Click 'Delete file' to remove file A
* Notice you are left with a block called "B", however the URL is "A". When saving, this wrong state is applied.

It seems that all properties, like title, operating system and price point, are shifted as needed when deleting entries, except for the URL.

See also bjorn/tiled#1285 and https://itch.io/post/26278

**Comment by leafo** [comment]
Thanks for the report, fixed
