### ISSUE TITLE
[Press] Downloading the same game multiple times raises the total download count.

### ISSUE THREAD

**Issue by PieCrafted** [itchio/itch.io#466]
Before I write an article, I like to test out the game on a variety of systems, and hence, I download them multiple times through the press dashboard.

My "issue" is that every time I re-download a game I have already downloaded, it raises the public download count. I do not want to come off as a "hog", and hence I ask that this be addressed.

Thanks :)

**Comment by leafo** [comment]
the downloads count has always shown the total number of download attempts for a file. It's unlikely that we'll change it. I wouldn't worry about showing too many times for a single file. We currently don't show what press users have downloaded to the developer, but we'll make it clear to the when we do.

**Comment by PieCrafted** [comment]
Okay, thank you :)

**Comment by Guard13007** [comment]
I had the same worry briefly, but it's not unreasonable to have a few downloads while testing things, I doubt any dev even if they saw the numbers would think it suspicious, unless you had like 50 or 100 downloads.
