### ISSUE TITLE
Add "static_cover_url" to API responses

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#468]
If it's already static, just duplicate the `cover_url` field.

This would be a cost-effective way to fix https://github.com/itchio/itch/issues/118 (e.g. no need to mess with canvas on my side to "freeze" the gif + it'd save bandwidth on initial load).

Additionally, games that don't know how to display GIFs (most non-web-based games) need some sort of static image they can load to a texture.

**Comment by leafo** [comment]
exists now
