### ISSUE TITLE
Just uploaded HTML5 game and it is showing black screen when I try to play it.

### ISSUE THREAD

**Issue by ChaseGwaltney** [itchio/itch.io#476]
Just uploaded HTML5 game and it is showing black screen when I try to play it. 
Ive tried to upload the zip folder of the game and it does not work at all. so I uploaded just the index.Html and It seemed to work but its just a black screen. What am I doing wrong?

Thank you!

**Comment by fasterthanlime** [comment]
Hey, please add a link to your game's page

**Comment by ChaseGwaltney** [comment]
https://chase-gwaltney.itch.io/chimeric

Thanks fasterthanlime

**Comment by fasterthanlime** [comment]
Open the chrome developer tools: there's a bunch of 403 errors because you're using absolute paths when referring to resources (like jQuery.js, etc.). You need to use relative paths.
