### ISSUE TITLE
External links not shown

### ISSUE THREAD

**Issue by IBwWG** [itchio/itch.io#477]
I entered four different categories of links in Metadata -> External links, but they don't appear anywhere on [our game's public page on itch.io](https://ibwwg.itch.io/mathildagame).  Where are they meant to show up?

**Comment by fasterthanlime** [comment]
They'll appear for buyers on their download page.

**Comment by IBwWG** [comment]
Ah, OK.  That would be why I don't see it even as the game's creator.  Thanks :)
