### ISSUE TITLE
Itch.io billing address for invoices

### ISSUE THREAD

**Issue by superfuchs** [itchio/itch.io#483]
In order to comply with my country's (Austria) tax authorities, I need at least a physical address or, even better, some kind of certificate of registration from the US equivalent that indentifies itch.io as a US based company.

Specifically, if I choose the "Collected by itch.io" model, I'd have to file an invoice for every payout, which of course I won't send to you - it's only to please the tax office. That invoice has to contain the address (and the UID for companies located in the EU) and has to be declared as "Reverse Charge".

Currently the website doesn't provide anything in that direction, is it possible to include that?

**Comment by uxTomas** [comment]
Have the same issue with our tax authorities (Lithuania). Already sent several emails, but still did not get the billing information.

**Comment by ironSunr1se** [comment]
That doesn't sound encouraging :(

One (rather supoptimal) option is to use the direct model, set the revenue split to 0% and apply for VAT MOSS.

**Comment by fasterthanlime** [comment]
The issue has been raised internally, hoping to get back with a satisfactory response to you both soon.

**Comment by uxTomas** [comment]
Hello, any progress on this?

**Comment by fasterthanlime** [comment]
Ping @leafo

**Comment by Berobasket** [comment]
I have the same problem. I wrote them email too and they did not respond. They only respond for my first email with request for physicall address: "itch corp., 154 Albion St., San Francisco, CA 94110, United States" but I need theirs VAT number... Anyone could help me?

**Comment by jacknorton** [comment]
I was unable to find this info too - for all european vendors it is required, so it should be put on the site.
However, at  least here, if a company is from US they can't have a VAT ID. For my invoice, it's not required, only the address.

**Comment by equidevium** [comment]
I am having the same exact issue with itch.io. What is happening guys? @fasterthanlime can you please verify that we can get an invoice? Otherwise i must rethink if i want to buy from the store.

**Comment by nikgraf** [comment]
Facing the same issue :(

**Comment by fasterthanlime** [comment]
You can generate an Invoice for any purchase on its download page, by clicking "More => Invoice"

![image](https://user-images.githubusercontent.com/7998310/36018651-d4c59dea-0d7c-11e8-8cc6-abd8751c2efd.png)

The page this opens contains the billing address for itch.io at the bottom.

**Comment by nikgraf** [comment]
Thanks @fasterthanlime
