### ISSUE TITLE
A Game By Its Cover not appearing in jam schedule?

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#487]
Can't seem to find it here https://itch.io/jams

**Comment by Ludonaut** [comment]
Me neither. Even when logged in it doesn't appear in the timeline, only in the "Jams you've created" section at the top.

**Comment by fasterthanlime** [comment]
Ludonaut reported by DM: after unchecking/rechecking 'unlisted', jam appears again. (And on front page too, yay!)
