### ISSUE TITLE
itch.io bug

### ISSUE THREAD

**Issue by bkbyon** [itchio/itch.io#492]
There's a hacker deleting everybody's game they upload to the website. Mine got deleted, and I don't know why. He never told me. So some people uploaded another game, but the game's still not working and not showing on the server. Please help because I don't want terrorist attacking people?
-----
This one I uploaded, and it showed up and got deleted without my awareness.
![5](https://cloud.githubusercontent.com/assets/20325560/16630717/9d88e238-4389-11e6-8233-0cc7b14411dd.png)

![3](https://cloud.githubusercontent.com/assets/20325560/16630662/666e80b4-4389-11e6-9332-9300cccf4bb9.png)
![123](https://cloud.githubusercontent.com/assets/20325560/16630661/666d48de-4389-11e6-8c1e-97aadfdd26a5.png)

**Comment by leafo** [comment]
forwarded to supported

(p.s. it appears that the developer deleted their own game, no security risks detected)
