### ISSUE TITLE
Matchmaking API and in-game content API

### ISSUE THREAD

**Issue by ferreiradaselva** [itchio/itch.io#500]
Hi,

First of all, thank you for the hard work on itch.io!

I was wondering if a matchmaking and in-game content API would be possible in the future (or if there are plans).

I'm aware that both requires processing power and space in the server of itch.io. So, what if the games using the API are required to be non-free? Like, they need to have a minimum price if they are using the API. I imagine that this would be incredible good for both itch.io and game developers.

Matchmaking and in-game content API isn't expensive for servers, since the requests aren't done every frame. Matchmaking status is usually updated in a few minutes interval, and in-game content (purchase, badges, etc.) is done sporadically.

hoping you are willing to take this discussion further,

Cheers

**Comment by felipefs** [comment]
Also, I'm not so sure about your availability to implement this, but I would gladly contribute if you want to make this possible (I currently work with C and Lua).

**Comment by sivri** [comment]
Let's add this topic here too, it looks like related.
"scoreboard and achievements API " https://itch.io/t/17579/scoreboard-and-achievements-api

**Comment by fversnel** [comment]
I'm currently working on master server technology that lets users from different platforms (Itch/Steam/Oculus etc.) play the same game together. It's not mature yet, not even mature enough to open source it yet but we will soon start using it for our game Volo Airsport and if our first tests are successful I will put it on Github. 

The reason I'm building this is to prevent a game community from breaking into smaller pieces. Right now Steam has the largest market share so for most games and most players that means they'll just use Steam to do matchmaking. I want to break that pattern. It shouldn't matter which platform you're using.

**Comment by felipefs** [comment]
Every effort would be great, but nothing can be done if there is no interest from the itch.io guys. :/

**Comment by fasterthanlime** [comment]
We're definitely interested in this, it's just a matter of when to do it :) There's so many proposed features it's not always easy to prioritize.

**Comment by felipefs** [comment]
Hi, @fasterthanlime, thanks for the response! This is great. I wonder if you guys accept contributions? If you do, I would gladly help.
