### ISSUE TITLE
Bad character support in email title

### ISSUE THREAD

**Issue by Bradshaw** [itchio/itch.io#510]
Got this issue on the https://itch.io/game/email/XXXX/new page.

Using "I'd like your opinion" in subject line gives "I&#x27;d like your opinion" in the output

<img width="503" alt="screen shot 2016-08-01 at 15 06 01" src="https://cloud.githubusercontent.com/assets/480553/17294869/9dc64d24-57f9-11e6-94da-04b5dd067358.png">

**Comment by leafo** [comment]
Thanks for the report, was just a bug with the email preview. It's fixed now
