### ISSUE TITLE
Opt-out of Google Analytics

### ISSUE THREAD

**Issue by joewreschnig** [itchio/itch.io#52]
Even if I don't provide a Google Analytics key, my profile and games pages have itch.io's GA code injected in them.

I would like to be able to disable this entirely and let people look at my pages without feeding Google's surveillance machine.

**Comment by joewreschnig** [comment]
Giving up.

**Comment by ssokolow** [comment]
@joewreschnig
Could you leave it open for those of us who don't mind waiting? It seems a little inconsiderate to just close it like that when it costs you nothing to leave it open.

**Comment by joewreschnig** [comment]
It costs me time every time I look at my open issues list. It's also inconsiderate to project maintainers for the original reporter to be unresponsive in an issue report.

So no, I won't leave it open. If you're volunteering to deal with it, you can file the bug.

**Comment by ssokolow** [comment]
Huh. I hadn't noticed that GitHub had a mechanism for retrieving an "all open issues" list for a single user.

(Force of habit. I assumed that the user-specific stuff in the black portion of the header was restricted to the grouping on the right end and I didn't see anything like an issues list in the account drop-down or the pages linked from it.)
