### ISSUE TITLE
accessing steam keys

### ISSUE THREAD

**Issue by thunderpants** [itchio/itch.io#522]
It's nigh impossible to access steam keys on a games page.
Just spent 30mins looking for my steam key for Burst ,with a  message from the dev to "try now !" and sadly the the said key still not appearing on the game page. 
Can't blame the dev i don't think , itch has me frustrating many times as a user/gamer .

Digital Homicide seem to have got it working but even then you have to crawl through each individual game page which is not easy considering the slightly chaotic way games/game libraries are stored and viewed on Itch.

There has to be a better way of listing ones games and accessing steam keys when they become available.
Itch needs to up it's game and become a hell of a lot more user friendly ,PLEASE!!!

I want to like Itch more than i do already but it's not happening for me right now.

**Comment by leafo** [comment]
If there is a Steam key available for a game it is always in the same place. You can find it on your download page for that game. For bundles you've bought, on the bundle's download page, each game that has a Steam key will say so next to the download button, so you can see what they are by scrolling through.

In the case of Burst, it looks like the developer generated keys for Groupees without enabling Steam keys. I've left a message here about it: https://itch.io/post/48496 Once they approve I can flip them on.

As for Digital Homicide, they promised Steam keys on a lot of games in their bundle, but many of their games got rejected from Greenlight. It doesn't appear those games will ever receive Steam keys. That definitely sucks for the people who bought it expecting keys. If you want I can process a refund for you.

Hope this explains the situation!

**Comment by leafo** [comment]
Closing this issue, open if you're still having trouble.
