### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MadeBySaints** [itchio/itch.io#528]
I think it would be a great feature for creators to have an update local files button from the My Creations tab under essentials Category.
![addition](https://cloud.githubusercontent.com/assets/3265397/18813360/bcd29c08-82c5-11e6-8b2f-461c8447dccc.PNG)
Rather than having to delete and re-download each time to test.

**Comment by fasterthanlime** [comment]
Hey, if you open the game as a tab (by clicking on the thumbnail), you can simply hit 'Check for updates' in the bottom right corner, and it'll update it for you!
