### ISSUE TITLE
Problem with collaborators

### ISSUE THREAD

**Issue by Palups** [itchio/itch.io#539]
​​I've added my friends as admins in a project. The project appears in their My Creations page, but it doesn't appear in their profile page. Why?​

**Comment by fasterthanlime** [comment]
That's just how the site behaves currently!

A "workaround" is to have your friends add the game to a collection, and have that collection be shown on their profile (from https://itch.io/my-collections)

**Comment by Guard13007** [comment]
@Palups See #206
