### ISSUE TITLE
HTML5 game throws 404 for index.html

### ISSUE THREAD

**Issue by Ohmnivore** [itchio/itch.io#540]
I have tried to upload my HTML5 build to two projects already. In both cases the .zip uploads correctly, but when I view the game it throws `https://v6p9d9t4.ssl.hwcdn.net/html/291437/assets/index.html?514016 404 (Not Found)`.

I have followed all the guidelines at https://itch.io/docs/creators/html5, I believe the .zip fits the specifications.

Here is the .zip file in question: 
[subsector_web.zip](https://github.com/itchio/itch.io/files/517937/subsector_web.zip)

**Comment by Ohmnivore** [comment]
Tried with `C:\Users\Anon\AppData\Roaming\itch\bin\butler.exe push bin\html5\release\bin\subsector_web.zip ohmnivore/subsect
or:subsector_web.zip` too, index.html in .zip's root still 404s.

**Comment by fasterthanlime** [comment]
This path exists:

  * https://v6p9d9t4.ssl.hwcdn.net/html/291436/index.html

This one doesn't:

  * https://v6p9d9t4.ssl.hwcdn.net/html/291436/assets/index.html

Just like in your zip :)

**Comment by Ohmnivore** [comment]
Oops, my build system had the wrong index.html in the manifest I think. Resolved xD Thanks for the tip!
