### ISSUE TITLE
I can't play any game

### ISSUE THREAD

**Issue by garguelo46** [itchio/itch.io#541]
All the games return an error like this:

`[2016-10-10 @ 22:36:28.783] [tasks/launch] error while launching e75c3efa-629d-4e71-bd9b-2fe0b8f244d8: Error: spawn /home/jimmy/.config/itch/apps/Time Travelling Space Pirates/content/ttsp ENOENT`

I've tried remove  ~/.config/itch and reinstall...
I've tried run the game binary on terminal and it doesn't work too...
  
Here is the itch log, from the path ~/.config/itch/logs:
[itch.txt](https://github.com/itchio/itch.io/files/520785/itch.txt)

**Comment by leafo** [comment]
The app's issue tracker is located here: https://github.com/itchio/itch/issues

This one is for website related bugs

**Comment by fasterthanlime** [comment]
cf. https://github.com/itchio/itch-compatibility-watchlist/issues/199
