### ISSUE TITLE
https URIs mishandled when proxying

### ISSUE THREAD

**Issue by DancerV** [itchio/itch.io#544]
When requesting an **https** object through a proxy, the application should use the **CONNECT** method to establish a pipe to the server, negotiate security and then make object requests.

Instead, the application breaks spec and attempts to make a proxy request of the form: **GET https://dl.itch.ovh/...**

This is incorrect for (at least) three reasons:
1. If it is requesting private data, that data may be improperly cached by the proxy.
2. Data can be snooped off the wire between the application and the proxy in what is intended to be a secure connection.
3. It basically doesn't work in many proxy configurations, and prevents the application from checking for updates or logging in successfully.

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/942
