### ISSUE TITLE
Ruby tag not supported on game page but supported for editing

### ISSUE THREAD

**Issue by Tectorum** [itchio/itch.io#546]
The HTML ruby tag is properly supported when editing a game:
![2016-10-27 13 53 59](https://cloud.githubusercontent.com/assets/5571683/19780955/ddccd6ee-9c4c-11e6-803c-34fa99ff2c48.png)

When viewing the page, though, the ruby tag becomes converted to a string:
![2016-10-27 13 53 54](https://cloud.githubusercontent.com/assets/5571683/19780962/e4d00132-9c4c-11e6-9ac3-a9b806f88a80.png)

**Comment by leafo** [comment]
Fixed now, thanks for the report.
