### ISSUE TITLE
"File too large" but it's not..

### ISSUE THREAD

**Issue by StenSven** [itchio/itch.io#550]
I tried to upload a HTML5 project done in Unreal Engine 4. However, when the project is posted on your website the following error message comes up:
![filetoolarge](https://cloud.githubusercontent.com/assets/9075448/19940122/e3318d94-a12b-11e6-82e4-7f8fea64dca3.jpg)

But as shown in the following image none of my files are larger than 500MB.
![files](https://cloud.githubusercontent.com/assets/9075448/19940216/28d978a2-a12c-11e6-96c1-91a5c463107d.jpg)

Any help is appreciated, thank you!

-- EDIT: 
Sorry, I just found that "The size any single extracted file should not be greater than 200MB." was a rescrition. These kinds of rescrition are kinda annoying. However the project in the images are just a test project, not an actual game I want to submit. So no worries.
Tip to make the site better: Put a link to the "Uploading HTML5 games" page in the error message I posted in the images.
https://itch.io/docs/creators/html5

I will make sure to contact you guys if the size restriction is preventing me from uploading anything in the future. Keep up the good work! 
END OF EDIT --

- Sven

**Comment by leafo** [comment]
The reason why we have the individual file restriction is because It's generally a bad user experience to have a browser based game where the player has to download  a large file like that before playing. I recommend making a downloadable version, or setting up the game to stream files as they're needed.
