### ISSUE TITLE
There's no "Books" category when hovering over "Browse" navigation

### ISSUE THREAD

**Issue by notnsane** [itchio/itch.io#551]
I think I'm going to shoot myself in the foot here by guessing that there are some legal issues with eBooks that I'm probably not super aware of, but... in a magical world, if I write an eBook, I'd like to upload it to itch.io and then having it displayed on the "Books" category, not "Other", because it doesn't belong to "Comics".

**Comment by fasterthanlime** [comment]
Alternatively, it'd be ok to just add a Books category, imho.

**Comment by notnsane** [comment]
Of course :D. Maybe in some years there might be too many categories, though? Just asking to get it right in the first place.

**Comment by leafo** [comment]
It's unlikely we'll rename comics, as comics aren't always books. itch.io already has a books section: https://itch.io/books Did you just not see it on your project edit page?

**Comment by notnsane** [comment]
Hah, I'm an idiot. I though it was a global issue but it's only on the hover of the "Browse" menu. I'll change the title to reflect this.

![m1fk5fi](https://cloud.githubusercontent.com/assets/7162375/20068457/94139fde-a4f7-11e6-8bc3-fc5a99299f11.png)

**Comment by leafo** [comment]
because space is limited, only the most popular content types are shown there now
