### ISSUE TITLE
Widget button does not work in Firefox

### ISSUE THREAD

**Issue by bjorn** [itchio/itch.io#553]
I've seen this issue with multiple embedded widgets on both Windows and Linux. While it used to work some months back, at some point the button in the widget became unresponsive in Firefox.

Example widgets that don't respond for me:

http://www.mapeditor.org/download
http://www.seanba.com/tiled2unity

Note that in Google Chrome and Internet Explorer the button works fine.

**Comment by bjorn** [comment]
Possibly related issue seen in JS Console (location info removed since it was basically all on `widget.js:1` or `bundle.min.js:2`:
```
SecurityError: The operation is insecure.
e.prototype.hasIndexedDB()
e.prototype.indexedDbKey()
e.prototype.get()
I.BaseBuyForm</BaseBuyForm.prototype.set_fingerprint()
bind/<()
BaseBuyForm()
BuyForm()
EmbedBuyForm()
EmbedWidget()
<anonymous>
```

**Comment by bjorn** [comment]
Maybe it has something to do with disabling third-party cookies:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API?redirectlocale=en-US&redirectslug=Web%2FGuide%2FDOM%2FStorage#Web_Storage_concepts_and_usage

> Note: Access to Web Storage from third-party IFrames is denied if the user has disabled third-party cookies (Firefox implements this behaviour from version 43 onwards.)

Maybe this storage access could be made optional and the `hasIndexedDB` call wrapped in `try/catch` pair like for example [done here](http://stackoverflow.com/a/23613052)?

**Comment by leafo** [comment]
thanks for the detailed report, it should be fixed now
