### ISSUE TITLE
Allow sales to be published, but not visible until start date

### ISSUE THREAD

**Issue by nickgravelyn** [itchio/itch.io#555]
I would like to schedule sales for the future but I don't want them to appear publicly until the sale begins. It'd be great to have an option for that when making sales, that way I don't have to remember to return to the page to publish it later.

**Comment by leafo** [comment]
this is effectively how things already work, since there's now way to browse upcoming sales. Sales are only linked to by itch.io while they're active.

**Comment by nickgravelyn** [comment]
Oh, I see. So even though the sale is "public" it's not shown in any UI until active. So the only chance of people seeing it would be to know the URL?

**Comment by leafo** [comment]
Yup

**Comment by nickgravelyn** [comment]
Ah well then never mind. Keep up the good work. :)
