### ISSUE TITLE
"Server-based network multiplayer" games show as single-player in metadata section of page

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#557]
Edit game page:

![nometa](https://cloud.githubusercontent.com/assets/7998310/20112828/25739f96-a5ee-11e6-8590-8893bbfc23af.jpg)

Metadata section:

![screen shot 2016-11-08 at 20 02 35](https://cloud.githubusercontent.com/assets/7998310/20112881/50da527e-a5ee-11e6-8086-759d297bfc78.png)

**Comment by BlueScreen-ISU** [comment]
I would like to see this one fixed. It bothers me for ages already.

**Comment by fasterthanlime** [comment]
Wrote a fix, will be deployed soon.

**Comment by Deozaan** [comment]
Does that mean this can be closed now? :)

**Comment by fasterthanlime** [comment]
Looks like it hasn't been deployed yet: https://pheonise.itch.io/last-man-standing /cc @leafo

**Comment by leafo** [comment]
Uh, what commit was this in @fasterthanlime? It should have been deployed

**Comment by fasterthanlime** [comment]
Oh my bad, actually Last Man Standing has local multiplayer so it's correct that it shows Single Player (since the developer didn't specify a player count), and the fix was indeed deployed.

Closing.
