### ISSUE TITLE
Export purchases as CSV appends .html to the downloaded file

### ISSUE THREAD

**Issue by shadiradio** [itchio/itch.io#558]
I think this is a recent bug as I use the export feature very frequently. This is on OS X Sierra, Safari 10.0.1. Removing the .html extra extension results in the proper, regular .csv file.

**Comment by leafo** [comment]
Which export link are you using? I don't see any issues with the ones that show up on this page: https://itch.io/export-purchases

**Comment by shadiradio** [comment]
Hmm, that's the page, and it happens with all links there (export everything, by year, or by month). It works correctly for me in Chrome on both Mac and PC, but in Safari on Mac I get ".html" appended after ".csv". This could be a Safari issue, though I don't recall updating Safari or Sierra recently, and this definitely didn't happen a few days ago. I'll try poking around my system to see if it's a local issue.

**Comment by shadiradio** [comment]
Maybe the content-type header is weird for the downloads?

**Comment by Guard13007** [comment]
I'm on Firefox 50.0, on Windows 10, and when I click the export link it says purchases.csv is an HTML document. It saves correctly as a csv. My guess is like @shadiradio said the content-type header is wrong and Safari sees that and "corrects" the file extension.

**Comment by leafo** [comment]
Try it again. I noticed the issue, should be fixed now. Thanks for the report!

**Comment by shadiradio** [comment]
Verified that it's fixed! :)

- Shadi
Sombr Studio <http://www.sombr.com> | @shadiradio
<http://www.twitter.com/shadiradio>
