### ISSUE TITLE
Games not "on sale" are being shown in the "on sale" link

### ISSUE THREAD

**Issue by notnsane** [itchio/itch.io#565]
Steps:

1. Go to the itch.io
2. Click on "On sale" link (under GAMES BY PRICE)
3. Scroll down

![xxfpdof](https://cloud.githubusercontent.com/assets/7162375/20549337/0c75c9fc-b10a-11e6-8e05-c80ffe501e4e.png)

This creates a quite confusing UX for the users.

**Comment by GranPC** [comment]
Looks like this is happening because these games are in a bundle.

**Comment by leafo** [comment]
There was an issue with hidden sales contributing to the on sale list, fixed now
