### ISSUE TITLE
404 on game from "A Good Bundle" bundle

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#566]
I just bought [A Good Bundle](https://itch.io/b/149/a-good-bundle), which includes [Bullet Hell Onslaught of the Mean-Spirited Ancient Deities](https://alexh.itch.io/bullet-hell-onslaught), however, when I click the download link (something like https://alexh.itch.io/bullet-hell-onslaught/download/KEY ) I get a 404 page and when I view the game's page, it does not say I own it as it does the other bundle's games.

**Comment by leafo** [comment]
Thanks for the report, will be fixed shortly. The version of the game in the bundle is accidentally pointing to an older deleted version of the game.

**Comment by Guard13007** [comment]
Woop woop. :P

**Comment by leafo** [comment]
Fixed now

**Comment by gh89275** [comment]
This is unfortunately a [broader issue](https://github.com/itchio/itch.io/issues/858#issuecomment-404714770) than just one game :(

**Comment by leafo** [comment]
@gh89275 is your reply related to this issue? if not please don't resurrect closed issues with separate problem since it notifies everyone involved.

**Comment by gh89275** [comment]
I figured "404 on lots of games" was a superset of "404 on one specific game", but if that's not related enough I won't further comment.
