### ISSUE TITLE
Can't change Community type from Post List to Directory

### ISSUE THREAD

**Issue by cairn4** [itchio/itch.io#573]
![community-type](https://cloud.githubusercontent.com/assets/1270001/20985030/af8f3740-bc90-11e6-90e1-f63e228fba1f.png)

Feel like this is a bug, or I'm missing a step?

I go into the game's community section, then Moderator -> Edit Game Community
Then I change the community type to "Directory", then click Save at the bottom of the page.

It says "Game community updated!", but if I go back into the Moderator -> Edit section, the type radio button field is still set to "Post List".

**Comment by leafo** [comment]
Sorry about that, should be fixed now.

**Comment by cairn4** [comment]
Thanks!
