### ISSUE TITLE
WebGL warning is a pop-up

### ISSUE THREAD

**Issue by qubodup** [itchio/itch.io#575]
![f](https://cloud.githubusercontent.com/assets/18312/21141179/1a8094cc-c13c-11e6-9e28-f45c0b129ac4.jpg)

This shows up in Chromium, even if WebGL actually does work.
It also shows up when using WebGL blocker extension.

The main problem is that the info is in a pop-up, which forces the  browser to switch tabs. Extremely annoying.

Please make the info appear as part of the page and do not use pop-ups.

**Comment by fasterthanlime** [comment]
Which game does that happen with? It doesn't sound like something itch.io can solve, but perhaps we can relay the issue upstream.

**Comment by leafo** [comment]
This alert dialog is triggered by the game engine that the game is built in, not sure what we can do in this case. Does the game load normally when the tab is visible?

**Comment by qubodup** [comment]
> Does the game load normally when the tab is visible?
It seems to always happen, whether the tab is currently active or not.

By the way, this report applies to when **Use hardware acceleration when available** is enabled.

If **Use hardware acceleration when available** is disabled, the popup will show up and once I press OK, it will close the tab like a hyperagressive adblocker (all extensions were disabled for testing).

**Comment by leafo** [comment]
can you include a link to a game that does this

**Comment by qubodup** [comment]
> can you include a link to a game that does this

Here's a few:
https://grifdail.itch.io/danger-classroom
https://conradte3.itch.io/put-it-out
https://jorgegamedev.itch.io/hyper-holomayhem
https://gumboot.itch.io/come-on-up
https://mistysouls.itch.io/four-crystals

**Comment by leafo** [comment]
Are you still seeing this popup? I think something with chromium was updated that prevents it from happening now. I don't see it anymore

**Comment by leafo** [comment]
I haven't been able to reproduce this lately. I'm going to close this, open again if you're still seeing it.
