### ISSUE TITLE
Please Help! The Penguins Need You! 

### ISSUE THREAD

**Issue by Jonnydark84** [itchio/itch.io#576]
My game is "Ice in the Sky" and it doesn't work. Any idea why?

It's a 2D unity game that uses the web browser and keyboard input.

It's my first upload so I might be missing something obvious. 

I know that's not a lot to go on... Thanks for your help. 

Jonathan

**Comment by leafo** [comment]
Help us help you: include a link to your game, and explain how it doesn't work.

Thanks

**Comment by Guard13007** [comment]
@leafo https://jonnydark.itch.io/ice-in-the-sky

It goes to a loading page for me and then never loads. Using Firefox latest fresh install at the moment.

**Comment by Jonnydark84** [comment]
https://jonnydark.itch.io/ice-in-the-sky

Hi @leafo 

Yeah, exactly what @Guard13007  said

It didn't work in either Firefox or Explorer. It said in explorer "Could not download the file" 

I tried setting the display size exactly as it is in the regular HTML upload code file. 

The game works on my website:

http://jonathanbarkerillustration.com/Games/Final%20Game.html

**Comment by fasterthanlime** [comment]
Regardless of the issue, the Unity webplayer is deprecated and shouldn't be used for recent projects - please use the HTML5 export instead, which will work on all browsers, not just Firefox (the last browser that still hasn't blacklisted the legacy Unity webplayer).

**Comment by Jonnydark84** [comment]
Drat. Thanks @fasterthanlime I guess I can't host it anymore. I don't have the origional unity files to export. :(

**Comment by Jonnydark84** [comment]
I've deleted the game. Thanks for your concern everyone.

**Comment by GranPC** [comment]
I've put a standalone Windows build of your game, just in case you want to preserve it or upload it to itch.io.
[Final Game.zip](https://github.com/itchio/itch.io/files/655410/Final.Game.zip)
