### ISSUE TITLE
Late jam submission url pop-up incorrectly describes purpose of link

### ISSUE THREAD

**Issue by jessicahayley** [itchio/itch.io#579]
Steps to reproduce:
* Have a finished jam
* Edit Jam > Edit submissions > paste in a game link > click "Get URL"
* Note incorrect wording in pop-up

<img width="572" alt="screen shot 2016-12-21 at 8 11 09 pm" src="https://cloud.githubusercontent.com/assets/1892337/21415038/57c9b53c-c7ba-11e6-8af6-355bffe575d9.png">

Nothin too major, just made me worry for a split-second that I was mistakenly giving out admin access to my jam.

**Comment by leafo** [comment]
ah, sorry about that. It's fixed now!
