### ISSUE TITLE
HTML5 game not receiving keyboard focus

### ISSUE THREAD

**Issue by hylyh** [itchio/itch.io#58]
Hello,

I have a game that was created in LibGDX and exported as an HTML5 canvas project. I have uploaded the game as an HTML project in a .zip and it displays correctly, but keyboard input does not work (mouse input, however, does). It affects multiple browsers across different OS's (I can get a list of where I've tested it if that's needed).

Upon further research this appears to be related to the focusing of the iframe in which the game is embedded. When I navigate to the static page that the iframe points to the keyboard input works correctly, and on the itch.io page I can call $("#game_drop").focus() from the console and the keyboard input will then work correctly (the arrow keys still scroll the page, but baby steps).

I can get more information if it is needed.
Thanks!

**Comment by jpcloud** [comment]
I had the same problem: libgdx game on itch.io wasn't receiving keyboard intput.
The fix:
Withing the uploaded zip, in the index.html:

Put window.setFocus(); in the "handleMouseDown" function.

This ways key presses are received.
If you also want to stop the page from scrolling when pressing "space" for example, do this:

1) add a event to the body tag:
  <body onkeydown="preventUseOfDefaultKeys(event);">

2) implement the event within the script-tag, eating away all unwanted default keys:

			  function preventUseOfDefaultKeys(event) {
				if (event.keyCode == 32 || event.keyCode == 27) {
					event.preventDefault();
				}
			  }

This for example kills space (32) and esc (27).
