### ISSUE TITLE
Embed not working on wordpress

### ISSUE THREAD

**Issue by AlexFili** [itchio/itch.io#580]
I tried to copy the embed code onto my wordpress site in HTML mode but it didn't work. Any ideas what could be wrong?

**Comment by leafo** [comment]
What do you see in the source of the page when you look at the post? Does the embed code get stripped, or malformed?

**Comment by leafo** [comment]
The embed code we generate is not malformed, so there's something about how it's being inserted into the post that's preventing it from working. You'll need to make sure the HTML is rendered directly for the embed to work.

Going to close this, if you're still having an issue please open again with more information.

Thanks
