### ISSUE TITLE
C# Path.GetTempFileName method fails if run through itch.io app

### ISSUE THREAD

**Issue by Enichan** [itchio/itch.io#581]
Found a bug where if you run a C# program through the app and call [Path.GetTempFileName](https://msdn.microsoft.com/en-us/library/system.io.path.gettempfilename(v=vs.110).aspx) it throws an [IOException](https://msdn.microsoft.com/en-us/library/system.io.ioexception(v=vs.110).aspx) saying the directory is not valid. This does not happen if you manually run the program outside the launcher.

**Comment by fasterthanlime** [comment]
Moving over to https://github.com/itchio/itch/issues/1092
