### ISSUE TITLE
Switch to Let’s Encrypt certificates

### ISSUE THREAD

**Issue by ekaris** [itchio/itch.io#586]
Let’s Encrypt certificates are free, automatic, transparent and secure.

https://letsencrypt.org

**Comment by fasterthanlime** [comment]
We're using Let's Encrypt certificates for a bunch of our services - but not the main itch.io site, since [wildcard certificates](https://github.com/certbot/certbot/issues/66) are a well-known limitation of Let's Encrypt / the ACME spec so far.
