### ISSUE TITLE
redactor bug on Firefox: cursor ends up outside <p> tag

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#587]
(reported by @eevee)

type "foo"
enter
type "bar"
home
shift-up
delete

the cursor will now be on its own line outside of a paragraph  :)  i think what i did accidentally was this similar variant:

type "foo"
enter
type "bar"
up, end (cursor is now at the end of "foo")
shift-down
delete

same effect, but with the non-paragraph at the end rather than the beginning.  and now the focus gets lost if you start trying to type

i guess by using shift-up/down i'm selecting and deleting the entire paragraph, rather than just its contents, and the cursor gets left outside it by accident...?  i've also noticed a couple times the selection is still drawn after i've cleared it, and sometimes i get paragraphs with a spurious invisible <br> at the very end; no idea if related

**Comment by leafo** [comment]
redactor is really buggy (at least the version we use), I need to look into updating to the latest release but I don't know if it will have any effect on our existing markup.

**Comment by fasterthanlime** [comment]
there's a 10.2.5 floating somewhere - but that's Redactor I - Redactor II is $200 afaict

**Comment by leafo** [comment]
I can update to latest version of redactor 1, hope it doesn't break anything

**Comment by leafo** [comment]
deployed latest version of redactor, hopefully many of the bugs we've experienced are fixed

**Comment by Guard13007** [comment]
@leafo Has there been any thought towards using something else entirely? Or is there nothing else suitable?

**Comment by leafo** [comment]
it's complicated, the choices aren't great and this rich text editor fits our requirements pretty well. Are you noticing issues with the newest version?
