### ISSUE TITLE
Theme reverting to default whenever I edit the game.

### ISSUE THREAD

**Issue by humblegrove** [itchio/itch.io#589]
Over the last couple of days whenever I've updated my game page the page's theme has reverted to the default. The images remain, but the colours and font/font size change back to their default. I've just been changing them back each time so far, but it's been quite irritating. I've only changed the description each time.

Here's a link to the game: https://humblegrove.itch.io/29

(I've been editing the game in Chrome.)
<img width="1423" alt="screen shot 2017-01-11 at 15 33 39" src="https://cloud.githubusercontent.com/assets/19796102/21854673/847f38f4-d813-11e6-9ca7-8232d91a0e32.png">

**Comment by Reinards** [comment]
Happened to me too :(

**Comment by leafo** [comment]
Sorry about that, it should be fixed now. 

If you're not sure what settings you had on your game page's layout, I can pull them from a backup. Just tell me the link of the game.
