### ISSUE TITLE
Show version number on Butler channel downloads on main store page

### ISSUE THREAD

**Issue by Enichan** [itchio/itch.io#590]
I keep old versions of MidBoss up on [https://eniko.itch.io/midboss](https://eniko.itch.io/midboss), and use Butler with a 'midboss-windows-latest' channel for auto-updating. On the download page the version for this channel is shown properly, but on the main store page it is not shown, just the file/channel name. I've gotten some comments from people confused because they could not find the latest version. Displaying the current version of channel-based downloads here would help confusion.

**Comment by leafo** [comment]
the butler version now shows up on the game page next to the file name, does that work for you? (thank to @GranPC)

**Comment by Enichan** [comment]
That's perfect, thanks! :D
