### ISSUE TITLE
Feature Request: Mac App Store badge

### ISSUE THREAD

**Issue by technicat** [itchio/itch.io#593]
In addition to the App Store badge, it would be nice to have the Mac App Store badge among the external download options (see for example http://technicat.com/ )

**Comment by technicat** [comment]
I've lost interest in the Mac App Store, so now this is a low, low priority for me, and can be closed if you wish.

**Comment by fasterthanlime** [comment]
Ha, apologies for never responding to this issue earlier!

I don't think anyone else has requested that, so I'll happily close it for now :star2:
