### ISSUE TITLE
Username redirects don't work for purchase urls

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch.io#594]
e.g https://ragzouken.itch.io/unity-bitmap-drawing/purchase should redirect to https://candle.itch.io/unity-bitmap-drawing/purchase

it seems a bit trivial, but the first google result i got searching for my thing was the purchase page, which now just displays "{"errors":["invalid user"]}" text

**Comment by leafo** [comment]
Woops, those URLs shouldn't be indexed by google anymore

**Comment by leafo** [comment]
Thanks, fixed now
