### ISSUE TITLE
"Support & contact" page has broken links to some game's websites

### ISSUE THREAD

**Issue by Draknek** [itchio/itch.io#601]
https://itch.io/support

"Are you looking for support for Lew Pulsipher's Doomstar?
Go to the official support page" - links to https://itch.io/doomstargame.com not http://doomstargame.com

**Comment by Guard13007** [comment]
I'm guessing the developer put in a link to their website somewhere without an http:// in front of it, so it's treated as a relative path instead of a separate domain..

I don't think that should be allowed anyhow, but it's been a while since I paid close attention to how Itch.io works myself.

**Comment by leafo** [comment]
we should be correctly providing the protocol in front of the URL if they the developer didn't provide it, I'll get out a patch shortly

**Comment by leafo** [comment]
fixed now, thanks
