### ISSUE TITLE
Hidden/Secret games show up when searching in press panel

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#603]
Note sure if this is intentional or not, but for example, [searching for "airships"](https://itch.io/press/games?platform=&status=&genre=&q=airships#results) leads to a 404 page for Airships Asunder.

It looks like the developer got their game on Steam and then hid it on Itch.io (since their profile has a link with the game's title pointing to its Steam page).

**Comment by leafo** [comment]
Thanks for the report. Restricted games no longer show up in the press panel
