### ISSUE TITLE
Add "View all by @xxx" at the top of game page

### ISSUE THREAD

**Issue by buckle2000** [itchio/itch.io#609]
In every game page, there is a link says "View all by xxx" at the bottom", which links to the author's page.

This link is so important and used frequently that it should also appear at the top of the page, beside "Add to Collection".

**Comment by Guard13007** [comment]
Is it actually used frequently though? Do you know that from analytics or no?

**Comment by felixplesoianu** [comment]
For what it's worth, I use it every single time after looking at some game I didn't know. Even if other people don't, the link deserves to be at least a little bigger and more visible, otherwise it will just be stuck in a vicious circle of irrelevance.

**Comment by buckle2000** [comment]
e....
I doubt that any developer has seen this.

**Comment by leafo** [comment]
It's now there, thanks
