### ISSUE TITLE
Creator-removed games still appear in collections API

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#611]
This causes https://github.com/itchio/itch/issues/1031

**Comment by leafo** [comment]
We'll just hide it like we do on web. It's now deployed.

Note this commit also removed `total_items` from the api result.

**Comment by khbecker** [comment]
I noticed that the game in my collection that was stuck (Pirate Pop) showed up again in the collection view on the website. I was able to successfully remove it from my account, unlike previously. If creator-removed games can't be automatically removed, I think keeping them visible for manual removal is better than the previous situation of being able to see it but not remove it.

I see the previous comment about hiding the removed games. I don't know if I ever saw that working for me, but I wasn't looking for it, so it's possible that I didn't notice.
