### ISSUE TITLE
Can't block users, blocking should be possible without reporting

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#612]
Originally reported by @iwanPlays [here](https://github.com/itchio/itch/issues/1144):

It is impossible to block users using the report form, as seen in this video:
https://youtu.be/k20awYJ6nns

Expected: after blocking, a user's comments won't appear for me any more.

Actual result: nothing changes.

**Comment by leafo** [comment]
Blocking was working, but it was not hiding the posts. It should be working now

**Comment by iwanPlays** [comment]
Thanks, it's beautiful. I'd suggest allowing to block users without having
to report them too
