### ISSUE TITLE
Allow html injection to sales flow pages for conversion tracking

### ISSUE THREAD

**Issue by slowriot** [itchio/itch.io#613]
Feature request.

Many analytics tools such as google analytics, Twitter ads etc allow conversion tracking by injecting a snippet of javascript or a one-pixel image into the page that's shown to the user when they complete a purchase.

It would be helpful to be able to specify custom html to inject (including javascript etc) into pages along the customer purchase flow - but especially at the checkout page after they've completed a purchase.  That way we could inject things like the Twitter ads conversion tracking code, and create conversion-directed campaigns, among others.

This is related to but not the same issue as #516.

**Comment by leafo** [comment]
we will never allow custom html/javascript to be inserted for security reasons. If there's conversion code you want to add you should tell us who it's for and I can add support for it. We already have support for facebook but I don't think twitter is there yet

**Comment by kujovic** [comment]
> We already have support for facebook

@leafo 
Where to add Facebook conversion code? I think I went through all docs and menus, and I couldn't find it.

And #169 perhaps needs to be updated.

**Comment by slowriot** [comment]
@leafo for twitter, please add support for the following, with TRACKING_ID substituted appropriately:

Twitter single event conversion tag:
```
<!-- Twitter single-event website tag code -->
<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<script type="text/javascript">twttr.conversion.trackPid('TRACKING_ID', { tw_sale_amount: 0, tw_order_quantity: 0 });</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=TRACKING_ID&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=TRACKING_ID&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0" />
</noscript>
<!-- End Twitter single-event website tag code -->
```

Twitter ads pixel:
```
<!-- Twitter universal website tag code -->
<script>
!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
// Insert Twitter Pixel ID and Standard Event data below
twq('init','TRACKING_ID');
twq('track','PageView');
</script>
<!-- End Twitter universal website tag code -->
```

You can get sample code for other conversion types at https://ads.twitter.com/accounts/YOUR_ACCOUNT/conversion_tracking?type=web

There's more information at https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html?utm_source=twitterads&utm_medium=ads&utm_campaign=twitterads

**Comment by slowriot** [comment]
Facebook's new tracking pixel code is as follows, again substitute TRACKING_ID as appropriate:

```
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', 'TRACKING_ID'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=TRACKING_ID&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->
```

Their "advanced matching" variant:

```
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', 'TRACKING_ID', {
em: 'insert_email_variable,'
});
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=TRACKING_ID&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->
```

There are a lot of variants of tracking metadata they support, such as from their own example:
```
<script>
fbq('track', 'Search', {
search_string: 'leather sandals'
});
</script>
```

and

```
<script>
fbq('track', 'Purchase', {
value: 247.35,
currency: 'USD'
});
</script>
```

Then there's the event code...
```
<head>
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '401588750220794'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=401588750220794&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->
</head>
<script>fbq('track', '<EVENT_NAME>');</script>
```

They seem to allow a lot of customisation so it would be worthwhile to have a look at https://www.facebook.com/ads/manager/pixel/facebook_pixel when integrating.

**Comment by slowriot** [comment]
@leafo P.S. You say you already have support for Facebook, but this is all I see in the analytics tab:

![](https://i.imgur.com/YJWgwn2.png)

**Comment by slowriot** [comment]
@leafo I hate to pester, but this is a very high priority for us at the moment.  We would love to start running a set of conversion-oriented advertising campaigns using our itch.io page, but if this isn't available we'll have to simply set up our own storefront for the same purpose instead.  Obviously we'd prefer to use itch.io.

**Comment by leafo** [comment]
You can now set twitter and facebook conversion tracking on an account level from the settings page

**Comment by slowriot** [comment]
@leafo there is now a form that accepts those conversion tracking values, but they do not appear to actually generate code anywhere on the site.  Opening a new issue for this.
