### ISSUE TITLE
Add a way to change the "feature graphic" for a game

### ISSUE THREAD

**Issue by Draknek** [itchio/itch.io#614]
Right now if a game is featured on the homepage, it shows the cover image even though the feature spot is a different aspect ratio. IIRC you can email to have this image replaced, but it would be more convenient if games that are featured or have been featured had an additional field on the game page where you could just upload an image and have it be used.

**Comment by leafo** [comment]
You can set it here: https://itch.io/game/promo-images/121614

"Wide Cover" is the image you can upload

**Comment by Draknek** [comment]
Aha, hidden URLs! Thanks!

It would be good if there was guidance on that page for what size images are expected?

**Comment by leafo** [comment]
there aren't good rules right now, the aspect ratio of that area changes. I want to change how it works with a future update to the homepage. generally though, pick something wider than taller, and try to avoid putting text on it since there's a chance it will get cropped
