### ISSUE TITLE
"Edit game" page autoscrolls weirdly for me

### ISSUE THREAD

**Issue by Draknek** [itchio/itch.io#615]
Chrome 57.0.2987.110, Windows 10

If I scroll the page (e.g. https://itch.io/game/edit/121614), after a certain point it starts autoscrolling down by ~10 pixels per second. It seems to start when the top of the cover image starts to be offscreen. Scrolling back up to the top of the page stop the autoscroll until I scroll down again.

This seems to happen on the edit page for all games I manage.

**Comment by fasterthanlime** [comment]
Any extensions installed?

Is that with a mouse, a touchpad, a trackball, a VR controller?

**Comment by Draknek** [comment]
Happens in Incognito, where uBlock Origin is the only extension enabled

The mode of scrolling doesn't matter, it happens whether I scroll down with a touchpad or with arrow keys. It seems to be dependent on where the page is currently scrolled to rather than the act of scrolling.

**Comment by leafo** [comment]
should be fixed now!
