### ISSUE TITLE
Published notification email incorrectly warns about missing cover image

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#619]
I had a project on private for quite a while with a cover image uploaded, when I published it and received an email for it, it warned that it lacked a cover image:

![image](https://cloud.githubusercontent.com/assets/15093567/24321503/7861f15c-110b-11e7-90dc-aa45a2bc443e.png)

I was worried it got deleted somehow, so I went on to check, and everything appears fine. For reference, the project is [this](https://guard13007.itch.io/minipixel-font).

**Comment by felixplesoianu** [comment]
Yep, that's definitely happening every single time.

**Comment by leafo** [comment]
Thanks, should be fixed now
