### ISSUE TITLE
API to check latest version of game on Itch.io ?

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#624]
I thought I saw a way to do this in the docs a while back, but I can't find it.. So is there a way to make a simple request to find the latest build on Itch.io? I want to make it so my game can notify users of a newer version if they're not using the app.

**Comment by fasterthanlime** [comment]
It's (maybe unfortunately) in the butler docs: https://itch.io/docs/butler/pushing.html#looking-for-updates

**Comment by Guard13007** [comment]
I feel you should make that a bit more prominent somewhere else as well. Perhaps a location where ALL API functions are listed? Right now they're a bit scattered.

Thank you though, much appreciated. ^^

**Comment by fasterthanlime** [comment]
Yep, ideally the central location for these would be https://itch.io/docs/api/serverside, it needs a lot of love :)
