### ISSUE TITLE
Download pages are not injected with analytics code

### ISSUE THREAD

**Issue by slowriot** [itchio/itch.io#626]
Related to #613.

At the time of writing, the only supported analytics code injection is for Google Analytics.  This does seem to inject your tracking code into every page under your subdomain... except the one that matters most!

After someone has purchased your game (or clicked "download" for unpaid games), they are taken to
`subdomain.itch.io/game_name/download/whatever`.   This page is not injected with your analytics tracking code, making it impossible to track user downloads as conversions.

This page does have google analytics tracking code, as with all other pages, but the only tracking ID that's there is UA-136625-6 - itch.io's own analytics code.

Ideally as per issue #613, it would be possible to inject custom analytics conversion tracking code as well into this page, so we can set up advertising campaigns that target downloads - or failing that, support for Facebook and Twitter conversion tracking as well.

**Comment by leafo** [comment]
User GA is now on download pages

https://twitter.com/itchdude/status/861152227859193858

Thanks

**Comment by slowriot** [comment]
@leafo thank you!  When do you think we'll be able to use Twitter and Facebook conversion tracking code on these pages as well, as per #613?
