### ISSUE TITLE
Some Game Jams not showing on active jams list/chart.

### ISSUE THREAD

**Issue by syntaxseed** [itchio/itch.io#630]
A few people are reporting game jams (marked as public/published and currently open) are not showing on the jams chart/calendar or in the list of Jams in Progress:

https://itch.io/t/69534/game-jam-not-listed-in-game-jams-page

This is making them very hard to find. And there doesn't seem to be any sort of link to expand the entire list (if the jams page is showing a subset).

**Comment by leafo** [comment]
Jams that last longer than 30 days do not get a slot in the calendar to prevent them from taking up a large permanent row in the calendar. They previously did not show up on the grid below, but they do now.
