### ISSUE TITLE
Comment gets posted multiple times?

### ISSUE THREAD

**Issue by elisee** [itchio/itch.io#631]
Looks like comments on game pages sometimes get posted multiple times? This is the second or third time this happened over the last few days:

![image](https://cloud.githubusercontent.com/assets/446986/25358734/d7bafa00-2942-11e7-93f1-06f94975740c.png)

![image](https://cloud.githubusercontent.com/assets/446986/25358740/dc41fa60-2942-11e7-8ec9-f3419a8895af.png)

See https://sparklinlabs.itch.io/craftstudio/comments

**Comment by leafo** [comment]
Hmm, there's a cors error on the comments page that doesn't let the redirect happen, so if you press comment over and over it re-submits it

**Comment by leafo** [comment]
It's now fixed, and I cleaned up the comments. broke approx 1 week ago with our new blog updates

**Comment by elisee** [comment]
Thanks a lot!
