### ISSUE TITLE
Typo on game page after uploading a new build

### ISSUE THREAD

**Issue by kennygoff** [itchio/itch.io#633]
Minor typo on the banner that shows up on my game's page after I pushed a new build through butler. This helpful message shows, but it says "Addded" instead of "Added".

Reproduction:
1. Have an uploaded game on itch
2. Upload a *new* build of that game through butler
3. Visit the game page (`username.itch.io/game`)
4. Banner message shows up at the top of the page, as show below

![screen shot 2017-05-02 at 10 51 49 am](https://cloud.githubusercontent.com/assets/1051880/25623861/e06348b8-2f25-11e7-8094-11958dc02052.png)

**Comment by leafo** [comment]
Thanks for the detailed report! Fixed now
