### ISSUE TITLE
Zombie Items in Collection

### ISSUE THREAD

**Issue by ilexp** [itchio/itch.io#634]
Hey there,

I'm experiencing problems with a [games collection on itch.io](https://itch.io/c/39251/duality-games) that I maintain. It appears that some of the games have been removed from itch after I added them to the collection and now I don't see any way to remove them.

They do not show up on the "My Collections" page, so I can't remove them from there, but they do show up when opening the collection. Clicking their link ends up in a 404, so I can't remove them through that page either.

The affected games are:

- [Super Racers](https://ymrymr.itch.io/super-racers)
- [Insomniac](https://ymrymr.itch.io/insomiac)

**Comment by leafo** [comment]
Thanks for the report, the games should no longer show up. (but they will come back if the games are published again.
