### ISSUE TITLE
Float not working on game pages

### ISSUE THREAD

**Issue by Gramps** [itchio/itch.io#638]
I have images that float left or right which were set with the game page interface.  However, when I view the page (public view) the floats are missing from the style, as if they were never set.  But the page looks correct when in the editor.  Why does the public view remove these floats?

**Comment by leafo** [comment]
For security reasons why strip any markup or styles that are not approved. Float currently isn't approved. Alternatively, I can give you CSS access on your page.

**Comment by Gramps** [comment]
That makes sense except I added the float with the editor itself as shown here:
![itch](https://cloud.githubusercontent.com/assets/1097098/26085072/008cf32e-39a7-11e7-9f6b-6794fab25041.jpg)

Not sure if these is meant for images or not but it  does add the float style to the images even though it doesn't seem to work on the public view.

Yeah, CSS access would be great. I only actually need it for image alignment in the description.  It is for this game page: https://coaguco.itch.io/haulin-oats

**Comment by leafo** [comment]
I've enabled CSS access on your account, you can find it in the theme editor.

Regarding that dialog, the rich text editor we use doesn't align directly with the markup we permit on the game pages. I'll see about adding support for float to our sanitizer.

**Comment by Gramps** [comment]
Sounds good, sir.  Thanks for enabling that.  Yeah, while I have never needed the float thing before it might be nice to add it in.  Cheers!

**Comment by Gramps** [comment]
Hmm, without being allowed to apply class names I can't really specify these images in the CSS.  Might require some really crafty wizardry to make this work!
