### ISSUE TITLE
"Community" shows as heading when not logged in, but shows no info

### ISSUE THREAD

**Issue by ice-queen** [itchio/itch.io#639]
If you are not logged in to itch.io you can see the heading for the "Community" section on a game's storefront, but if there have never been any posts then this section does not have anything beneath it so looks odd.

![](http://i.imgur.com/lCK7m62.jpg)

When there have actually been posts then these do show up, otherwise the section is completely blank.

**Comment by leafo** [comment]
Thanks for the report now, the button should correctly show for logged out users
