### ISSUE TITLE
API for game jam hosting

### ISSUE THREAD

**Issue by hach-que** [itchio/itch.io#640]
As per tweets: https://twitter.com/hachque/status/865817100392124416

> Is there any server API for the game jam hosting?
> Hmm not afaik, what kind would you be looking for? (describe example endpoints)
> Create jam with all the fields (including visibility), get url to jam, set visibility
> We run https://jamhost.org/ , which does a ton of stuff, but we don't do submissions or game hosting (intentionally)
> So looking at giving folks an easy way to create an associated itch.io jam that has all the details synced

**Comment by lvivtotoro** [comment]
You could use a web scraper

**Comment by fasterthanlime** [comment]
Note that if we do expose that functionality, there'll probably be a whitelist (on which jamhost will be) so that not everyone can abuse the jam API to further clog the jam calendar :)

**Comment by hach-que** [comment]
It would be good if we could get like, OAuth or something to JamHost for the "Join jam" button, so that we can only allow people who are on-site to be seen as joining the itch.io jam listing.

At the moment anyone can join a jam like https://itch.io/jam/tigjam-australia-4, even though we require on-site registration through JamHost.

**Comment by hach-que** [comment]
I'm not sure this repository is monitored any more, so I'm going to close this issue out as not planned.

**Comment by hach-que** [comment]
Is there any documentation for those jam-related endpoints? https://itch.io/docs/api/serverside doesn't list anything that seems relevant.
