### ISSUE TITLE
"Full Browser" setting for HTML games/tools

### ISSUE THREAD

**Issue by Wahooney** [itchio/itch.io#645]
It looks like games played through the desktop app are run in some sort of sandboxed or otherwise limited mode, which is fine for most cases. But a system that allows more browser features (in my case, allowing users to save an image to disk by right-clicking), enabled on a per project basis, with a possible warning to the users, would be great.

**Comment by fasterthanlime** [comment]
Do you have an example tool itch.io web game/tool that tries to trigger a "Save to disk" feature in the app and fails to do so?

**Comment by Wahooney** [comment]
My example is based on a tool I wrote: https://wahooney.itch.io/texture-grid-generator

When run through the desktop client, doesn't show any options when right-clicking on images in an img tag.

**Comment by fasterthanlime** [comment]
Ah, interesting! Right click menus are actually not a part of HTML5, browsers implement it however they want.

In the app's built-in webviews, there's a meaningful context menu (with stuff like "Open in new tab", "Copy", "Paste", "Copy link address" - depending on what you're clicking on / if there's text selected - it kinda mimics' chrome's).

As for games, currently there's no context menu in the itch.io app. I'm not exactly sure whether to add one, it might conflict with games using the right mouse button? Then again those probably prevent the "oncontextmenu" event from being fired anyway.

I'll investigate further!

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/1230
