### ISSUE TITLE
Is it possible to get the Itch.io API Key in the client directly?

### ISSUE THREAD

**Issue by lvivtotoro** [itchio/itch.io#649]
Without uploading a game that does this

**Comment by fasterthanlime** [comment]
You can get one from https://itch.io/user/settings/api-keys

It won't be a JWT key, like the client would give you - and it'll have access to more of https://itch.io/docs/api/serverside than what the client would give you with `profile:me`, but you can use to test!

### JWT keys

With JWT keys, you'd do `https://itch.io/api/1/jwt/me` and pass the HTTP header `Authorization: your-jwt-key-here`

### Regular API keys

With regular API keys, you just include them in the URL, like so: `https://itch.io/api/1/your-api-key/me`

**Comment by lvivtotoro** [comment]
You know everything

**Comment by lvivtotoro** [comment]
Wait, nevermind. Closed too early.

I used the key and it gave me the following response:

```
<div class="error_page page_widget">
    <div class="padded">
        <h2>There was an error with your request</h2>
    </div>
</div>
```

**Comment by lvivtotoro** [comment]
This seems like an actual serverside error since the page is supposed to respond with JSON
