### ISSUE TITLE
Just bought "Enlightenment" and get "download link is expired".

### ISSUE THREAD

**Issue by Surjin** [itchio/itch.io#667]
I just bought Elightenment a few minutes ago and the download link page says the link is from 11 days ago. I did not purchase it 11 days ago. When i click on the link or the link i have requested to be resent it takes me to a page stating "download link is expired". Is this a itchio problem or do i need to contact the game devs? Thank for any help.

Surjin

**Comment by fasterthanlime** [comment]
Hey,

"11 days ago" is the date the game was last updated on the site.

"Download link is expired" is a message you would get if it takes too much time for your computer to start the download from the time you click "Download". Does your internet connection tend to be slow at times?
 Can you try again?

**Comment by Surjin** [comment]
Thanks but apparently it was something the game devs had to correct. I left a message on their support page and they replied that the link had been fixed. I am now able to download the game as of a few minutes ago. Thanks anyways.
