### ISSUE TITLE
Do sale conditions trigger when you own an item that you bought in a bundle?

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#672]
User wants to use Kenney Studio coupon, but they bought the Kenney Bundle, not `Kenney Studio` individually - and it seems to not work for them.

**Comment by leafo** [comment]
Yes, as long as the DownloadKey entry exists in the database then it counts for the trigger.

**Comment by sonicbomb77** [comment]
Okay - so - what am I supposed to do then?

I bought https://itch.io/s/6789/kenney-bundle and was given a url for a coupon that always 404s when I visit it https://itch.io/s/7645/kenney-studio-coupon-deluxe

**Comment by fasterthanlime** [comment]
@sonicbomb77 I replied to you by e-mail!

(the 404 comes from a lack of coupon code afaict).

**Comment by sonicbomb77** [comment]
Please explain. I have the coupon URL right there. Are you saying I need to ask the developer for something else? If so, what?

**Comment by fasterthanlime** [comment]
> Please explain. I have the coupon URL right there. Are you saying I need to ask the developer for something else? If so, what?

I gave you the correct URL in the e-mail: https://itch.io/s/7645/kenney-studio-coupon-deluxe is not it - it's missing the coupon bit. Visiting that URL will always get you a "page not found".

The correct url is https://kenney.itch.io/studio-dlx - which redirects to https://itch.io/s/7645/kenney-studio-coupon-deluxe?c=studio-dlx (notice the `?c=studio-dlx`).

**Comment by sonicbomb77** [comment]
For some reason, I don't see your email response with that URL in my gmail inbox, so thanks for posting the link here. And yes that url worked for me, so I'll pass it on to Kenney for reference.

Thanks again for the help and setting up a !gh issue.

**Comment by fasterthanlime** [comment]
No problem! I'm not sure what's up with the e-mails :) Kenney definitely knows about the URL, since that's the one he sent out to all Kenney Studio owners.

I'm guessing you were redirected to the coupon-less URL before we improved the flow for non-logged-in users for coupon sales, maybe!
