### ISSUE TITLE
I can not edit a Devlog that I did not write in a game I created

### ISSUE THREAD

**Issue by yvan-sraka** [itchio/itch.io#674]
Hello,

I created this game https://inform.itch.io/malleus and I have all write access to this project.

But when I want to modify this devlog: https://inform.itch.io/malleus/devlog/3987/notepatch-1, I get a 404 error not found: https://itch.io/dashboard/post/3987/edit !

I do not know if this is a wished behavior, but it is a bug: because if we allow the editing of a devlog only to its author, it should not have a large "Edit Post" button on this page.

Thank you in advance for your help !

**Comment by leafo** [comment]
This is a bug, thanks for the report. We'll get a fix out shortly.

**Comment by leafo** [comment]
Fixed now!
