### ISSUE TITLE
<video> tags in game descriptions get escaped and can't be used

### ISSUE THREAD

**Issue by henkboom** [itchio/itch.io#675]
Hi! I'm trying to embed video loops in my game's page. I'm running into an issue though.

The html:

    <img src="http://i.imgur.com/kvfYc1m.gif">
    <video autoplay loop muted type="video/mp4" src="http://stuff.henk.ca/cityglitch/loop.mp4"/>

is on the viewed page shown as:

    <img src="http://i.imgur.com/kvfYc1m.gif">
    &lt;video autoplay loop muted type=&quot;video/mp4&quot; src=&quot;http://stuff.henk.ca/cityglitch/loop.mp4&quot;/&gt;

as a result, I can't use video tags to embed video in game descriptions.

**Comment by leafo** [comment]
Video tags are now whitelisted. Thanks for the report

**Comment by henkboom** [comment]
I just checked and it's working! Thanks!

**Comment by henkboom** [comment]
I'm encountering an issue with the 'playsinline' video attribute, it seems to be removed from the page. Should I submit a new bug?

**Comment by leafo** [comment]
@henkboom try again, should work now

**Comment by henkboom** [comment]
thank you! it does!
