### ISSUE TITLE
Broken Athuntication 

### ISSUE THREAD

**Issue by hamz77** [itchio/itch.io#676]
Hi,

Hope you are good!

Steps to repro:

HOST : https://itch.io/ 
1) Create a itch.io account having email address "a@x.com".
2) Now Logout and ask for password reset link. Don't use the password reset link sent to your mail address.
3) Login using the same password back and update your email address to "b@x.com" and verify the same. Remove "a@x.com".
4) Now logout and use the password reset link which was mailed to "a@x.com" in step 2.
5) Password will be changed.

All previous password reset links should automatically expire once a user changes his email address.

Attack scenario:

1) My email account is compromised. Attacker asks for password reset link for my itch.io account.
2) I got to know, I change my email address on my nuclino account. I now assume i am safe.
3) But the hacker can still use the old password reset links (which he had never used for single time) which were sent to my old email address.4) My account is now compromised again.

Please let me know if you need any other information

Please fix this.
Hamzz

**Comment by leafo** [comment]
Thanks for the report. I've made it so password reset tokens are cleared when changing email and I've wiped out all outstanding reset tokens.

**Comment by hamz77** [comment]
Hi, 
so any appreciation or reward? 

Thanks

**Comment by Deozaan** [comment]
> so any appreciation or reward?

I believe this counts as appreciation:

> Thanks for the report.

**Comment by hamz77** [comment]
Hi, 
 Is there any reason why you give me just appreciation, why not reward because this contains High risk .

Thanks

**Comment by Guard13007** [comment]
@hamz77 Where does itch.io offer bounties for finding bugs? Last I checked that is not listed, so asking for a reward for reporting a bug is a *little* bit offensive..
