### ISSUE TITLE
HTTP 404 on some API endpoints (/login, /me)

### ISSUE THREAD

**Issue by Bunkerbewohner** [itchio/itch.io#679]
I just downloaded the (presumably) latest version of the desktop client from https://itch.io/app.
Installed it on Windows 10 and when I try to login I just get this:

![error](https://user-images.githubusercontent.com/500529/28212522-1850ae7c-68a2-11e7-8b19-addf55412a81.jpg)

```
Error: HTTP 404 /login
    at Client.<anonymous> (C:\Users\mform\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\api.ts:87:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\mform\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Quitting and restarting the app doesn't change anything.
Based on the files in itch's AppData folder it is version 23.4.1.

**Comment by fasterthanlime** [comment]
Does it still happen for you?

**Comment by fasterthanlime** [comment]
(I was able to reproduce the issue locally for a minute, and now it works again)

**Comment by Bunkerbewohner** [comment]
Tried again and on the second attempt (after restarting again just to be sure) it now works.

**Comment by fasterthanlime** [comment]
Alright thanks, we'll keep looking into what happened.

**Comment by tfaehnle** [comment]
Shouldn't there be a better error message, regardless of the cause of this error?

**Comment by fasterthanlime** [comment]
> Shouldn't there be a better error message, regardless of the cause of this error?

"404" is really not something that would usually happen - even if we had regular server issues.

"500" would be an internal server (we might want a good error message for that), "403" would indicate that access is forbidden (we might want a good error message for that too), but 404 is really really fishy.

Investigating at the moment.

**Comment by fasterthanlime** [comment]
Re-opening as I'm still able to reproduce the issue.

After looking a bit into it, though, it's not as fishy as I thought, so that's good.

**Comment by fasterthanlime** [comment]
The issue has been resolved.
