### ISSUE TITLE
Please link to the itch store on the widget

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch.io#680]
For game widgets developers include on their websites, please make the name of the game a direct link to the itch store for it.

It just make everything easier. If I'm writing an article about a game, i can then easily copy that link into an article. Otherwise, I need to go to the itch store, search and then copy it. The other way is to click the developer name (which is a link), but then you need to sift through all the titles they have to find it.

It just makes it simpler. I admit it's a small use case, but little things add up and it could help itch's exposure if it makes it super easy for press to link to :+1: (makes me more likely to link to it then too!)

**Comment by leafo** [comment]
It's an option for widget creators to add a link right now. The original justification was to prevent people from clicking on something, going to another page, and getting confused, when they were trying to buy a game.

Potential approaches are: 
* remove that feature, always show "View on itch.io" link
* make the title of the game a link to the game page, keep the "view on itch.io" option

**Comment by fasterthanlime** [comment]
> make the title of the game a link to the game page, keep the "view on itch.io" option

Voting for this one :+1:

**Comment by Guard13007** [comment]
Agreeing with @fasterthanlime on that one.

**Comment by leafo** [comment]
Sorry about the delay, the title of the game will always link back to the page now
