### ISSUE TITLE
gamejam team ratings

### ISSUE THREAD

**Issue by josefnpat** [itchio/itch.io#682]
Right now, even though my musician is an admin (and marked as contributor) for [our game](https://itch.io/jam/fantasy-console-game-jam-1/rate/158435), he still can't rate and comment on any of the games in the game jam.

![image](https://user-images.githubusercontent.com/646162/28324373-cf1d2396-6ba0-11e7-81cf-621910aeb106.png)

What I would expect to happen:

1) have multiple accounts from team members in a game jam
2) one person submits a game to a game jam
3) add team members to the admin list and mark them as contributors
4) all team members can vote and comment on the other games (there would be a team rating, not a user rating)

**Comment by leafo** [comment]
There's actually a setting for jam hosts to allow contributors to vote as well. This isn't the default because it would mean a submission can get a variable number of votes depending on contributor count.

https://itch.io/docs/creators/game-jams#jam-customization/ranked-jams

**Comment by leafo** [comment]
Gonna close this, open if you think there should be any changes.

**Comment by josefnpat** [comment]
Oh, cool - thank you!
