### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by SavageMoon** [itchio/itch.io#685]
Hello, I tried reporting an issue with a game I purchased, Monster Girl Island, in which I try playing, & it keeps crashing. Never heard back. TY.

**Comment by leafo** [comment]
Hello,

Did you end up getting a reponse? I'm closing this issue but feel free to reply if you didn't get any help.

**Comment by SavageMoon** [comment]
No, your the first to respond, had tried several times afterwards, no success.

**Comment by leafo** [comment]
@SavageMoon For game specific errors we typically will forward the message to the developer of the game, since we don't develop the games on our platform. Can you contact support@itch.io again, include a link to this issue as well so we are aware.

Thanks
