### ISSUE TITLE
Can't edit Profile field in Account settings

### ISSUE THREAD

**Issue by Luna-Rex** [itchio/itch.io#686]
Any time I try to edit the Profile field in the Account settings, and save it, it reverts the changes. I've tried clearing the cache in case it was just on my end, but the problem seems to be with itch.

Also, to clarify, I'm talking about "Account settings->Profile->Profile". Other fields in the same tab seem to work normally.

**Comment by fasterthanlime** [comment]
What's your itch.io profile URL ?

**Comment by Luna-Rex** [comment]
https://lunarex.itch.io

**Comment by Luna-Rex** [comment]
I get no error message of any kind. I'm trying to remove a line.

**Comment by Luna-Rex** [comment]
It would seem removing an entire line and nothing else is the thing that triggers the bug. If I remove the line and change something on another line, it updates properly.

**Comment by Luna-Rex** [comment]
This bug extends to editing install instructions for projects, and presumably other similar editable fields.

The behavior is still the same, deleting one or more lines without changing any remaining lines causes the entire change to be ignored, regardless of pressing Save. No error message.

**Comment by Luna-Rex** [comment]
After testing it again, the bug no longer seems to exist. Still don't know what caused it. Weird Chrome bug that got fixed long ago maybe? Regardless, if the bug isn't there anymore, I figure there's no need to leave this issue open.
