### ISSUE TITLE
Metadata External links are not shown

### ISSUE THREAD

**Issue by hikari-no-yume** [itchio/itch.io#688]
[pet that focks](https://hikari-no-yume.itch.io/pet-tha-focks) has, under its Metadata, an External link pointing to its GitHub repository:

![metadata external links](https://user-images.githubusercontent.com/579774/28641451-4168ff40-7247-11e7-8e7f-da98d0f2118e.png)

But it's nowhere to be seen on the game page:

![game page](https://user-images.githubusercontent.com/579774/28641490-61ed1b3e-7247-11e7-9b32-a0c0af72783c.png)

Is this possibly related to this being an HTML5 game?

**Comment by leafo** [comment]
Hey, I just pushed a fix that will show the links in he more information area. (I also fixed that layout bug).

Thanks for the report

**Comment by hikari-no-yume** [comment]
Fantastic, thanks!
