### ISSUE TITLE
Feature request: Multiple HTML packages per game, and minimum prices for webgames.

### ISSUE THREAD

**Issue by NQNStudios** [itchio/itch.io#691]
Originally wrote this in a series of tweets to @fasterthanlime, now reposting through the proper channel with additional info!

Just wrapped up volume 1 of my [Twine-a-day game](https://natquaylenelson.itch.io/stream-of-pretentiousness) on itch. I have a feature request for when I start volume 2 in a month or so.

I'm gonna keep making the game in volumes of 30 Twine chapters at a time, each volume its own Twine game (to make a clean slate for me before one game gets cluttered with hundreds of chapters) which could technically have its own game page on Itch. But I'd rather have each of the volumes listed on the same game page, as a separate zip file with its own index.html and allow players to choose between volumes to switch which game is playing in the iframe.

So the game page looks something like this:

```
_____________________________________________
| this is the iframe                         |
| which starts showing the index.html        |
| from volume1.zip because volume1           |
| is marked as the default zip to            |
| be played online                           |
---------------------------------------------

<- Playing Volume 1 ->                   # The left and right selectors cycle through which 
                                         # zip file is shown in the iframe

(Support this game)                      # Donation button same as before

...                                      # Game description and download links below as usual.
```

Each zip file should be able to set a minimum price (although in my case, enforcement that someone not be able to play without paying, is a very small issue. I don't care if the payment lock is airtight or anything.) Whenever the player selects a zip file with a minimum price they haven't unlocked, the iframe should show a generic message with a lock icon or something, and say "This game/episode/whatever" is only available for $whateverPrice."

I've thought a lot about it and this is my ideal layout and payment plan for both Stream of Pretentiousness and all other future episodic games I'm planning to make. I prefer this to making a separate game page for each episode of each game because for these episodes, I want the player to pay a single price to access every future episode.

**Comment by Milesloh** [comment]
Any system to require payment for html5 games would be very helpful.

**Comment by NQNStudios** [comment]
Closing as duplicate of #1150
