### ISSUE TITLE
Minor text bug

### ISSUE THREAD

**Issue by dalegdawg** [itchio/itch.io#696]
There's a minor text bug I found on the Edit profile page.

![image](https://user-images.githubusercontent.com/30841350/29085911-aed5bec6-7c68-11e7-9d82-afad2c2ce36e.png)

I'm assuming it's meant to say "Content - How the site shows **your** contnent

**Comment by fasterthanlime** [comment]
Nope, the site shows content to you.

I agree the phrasing is a bit awkward, but it's technically correct :)

**Comment by Guard13007** [comment]
@fasterthanlime Perhaps "How content is shown to you" to remove potential for confusion.

**Comment by leafo** [comment]
Thanks for the suggestion @Guard13007 , I updated it to use that. Will go out next deploy
