### ISSUE TITLE
Game Page states incorrect Ludum Dare compo

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch.io#698]
I submitted a game to Ludum Dare 23 many years ago. I included the LD submission URL on my gamepage. But the itch game page tells me it was submitted to LD39 and clicking "Add Ludum Dare tag" adds a "ludum-dare-39" tag for some reason.

![itch ludum dare](https://user-images.githubusercontent.com/227734/29246565-4e8b1686-7fbc-11e7-9fc0-e3caba24259b.png)

This is wrong and should be corrected.

Game page: https://deozaan.itch.io/btw

**Comment by leafo** [comment]
This is fixed now, thanks for the report
