### ISSUE TITLE
Restricted game has publicly accessible pages (devlog)

### ISSUE THREAD

**Issue by kujovic** [itchio/itch.io#699]
We have two project pages for our game, one is a restricted early access, only available to users with keys:
https://rollingcrown.itch.io/demonheart-early-access (404 for all others)

We published a devlog on the restricted project:
https://rollingcrown.itch.io/demonheart-early-access/devlog/7192/chapter-3 (visible to everyone)

A user who is following our profile somehow got the notification, arrived to the devlog page and commented how they can't download the game (page not found), causing confusion (does this user own the restricted game or not, and how did they get the link to the devlog?). It seems this user doesn't have access to the restricted project, but has access to its devlog.

We were expecting only people with access to the project could see the update, but it's a publicly accessible page, visible even without an itch.io account. Granted, nobody can download the game except the users with keys, but this page shouldn't be visible.

When editing the devlog there is an option for visibility which can be unchecked, but then the page says "Draft" and only the developer has access to it.

**Comment by leafo** [comment]
Thanks for the report, that's definitely a bug. I've just pushed out a fix. Additionally I found they they originally discovered the post through their timeline. I patched the timeline code to not show events if the related game is not available to them.

**Comment by kujovic** [comment]
Thank you for fixing it so quickly and for explaining how they discovered the post. 👍
