### ISSUE TITLE
Credit card tab breaks

### ISSUE THREAD

**Issue by craigperko** [itchio/itch.io#702]
I moved, so I needed to change my credit card's associated zip code. Trying to do so, however, gave me "There was an error with your request". Now whenever I try to visit the credit card section of my settings menu (https://itch.io/user/settings/credit-cards), simply gives me that message, not even displaying the options it displayed before.

This makes it impossible to buy games, so I hope it gets fixed.

If you need to contact me for more details, I'm on your system as https://craigp.itch.io/

**Comment by leafo** [comment]
Hey, sorry about the trouble. Try again, I removed the invalid record from our database.

**Comment by craigperko** [comment]
OK, although now I have to re-enter the credit card. I don't know whether the original bug is gone or not.

**Comment by leafo** [comment]
The original issue was that when updating your card the API for out card processor returned a blank response and cleared out any data we had stored about the card. I changed it so if the API returns nothing it will abort the update.
