### ISSUE TITLE
My text game, if hosted on itch.io, appears messed up on Apple devices

### ISSUE THREAD

**Issue by mikhaildutikov** [itchio/itch.io#706]
Am I the only one seeing this with https://mikhaildutikov.itch.io/selfie-kings? (It does work fine on Android devices.)

![selfie-kings-on-apple](https://user-images.githubusercontent.com/14870668/30253674-1713d32a-968a-11e7-8445-ec85f1029f1e.jpg)

**Comment by leafo** [comment]
We've gotten another report of this issue. I don't have an iOS device to test at the moment, if anyone wants to take a peek that would be appreciated.

**Comment by leafo** [comment]
I tried pushing a change that might fix it, could you test again @mikhaildutikov

**Comment by leafo** [comment]
Found an issue with the first change, I pushed another one. Try it again if you tested it in the last 11 minutes.

**Comment by mikhaildutikov** [comment]
@leafo hey, thank you for looking into this! The text's no longer overlapping, however, there is no scroll-bar showing up, so the text is basically cropped.

![img-20170911-wa0003](https://user-images.githubusercontent.com/14870668/30293285-433c024c-9739-11e7-99bb-f1fb148efe6b.jpg)

**Comment by mikhaildutikov** [comment]
Any news about this?

**Comment by mikhaildutikov** [comment]
@leafo, any news on this?

**Comment by leafo** [comment]
@mikhaildutikov Sorry about the delay, I've been working on rewriting how browser games are injected into the page. Could you try again? We now force games to be launched into fullscreen on mobile devices

**Comment by mikhaildutikov** [comment]
@leafo Hey, indeed this works! Tested with one person's device., but I presume that's sufficient. Thank you very much for this! That issue turned people using Apple devices away from playing my game on itch.io...

**Comment by leafo** [comment]
Great, glad it works. Sorry about taking so long to get a fix out.
