### ISSUE TITLE
Upgrade to Google's Universal Analytics

### ISSUE THREAD

**Issue by OhiraKyou** [itchio/itch.io#708]
Edit: apparently, the Universal code is actually working, which I didn't expect due to the help pages claiming that Classic Analytics is required.

Classic Analytics is not available as a downgrade option for existing Google Analytics accounts. And, data is carried over when upgrading from Classic to Universal. So, is there any reason in particular for itch.io still requiring Classic?

**Comment by leafo** [comment]
Where does it say that classic is required? I can remove that text to avoid any confusion.

**Comment by OhiraKyou** [comment]
Hmm, perhaps it was updated since I posted this. I believe it was either directly above the game or account analytics ID box or in the documentation, but I can now only find it on the original blog update post.

**Comment by leafo** [comment]
Thanks, going to close this.
