### ISSUE TITLE
Bugs in the moderation UI

### ISSUE THREAD

**Issue by felixplesoianu** [itchio/itch.io#712]
First, on the Reports tab, I see all the dates as whenever the page loaded.

Second, if I click "Mark resolved" on a report where the original post was deleted, I get this error message:

> {"errors":["invalid report"]}

which means old reports remain stuck in the interface.

Third, I could really use a link from each category to its associated moderation page, because without one forgetting to check is all too easy. Thanks.

**Comment by leafo** [comment]
Fixed now, also cleaned up the visuals on the reports page

**Comment by felixplesoianu** [comment]
> If you view the top level category then you'll get the reports for all the sub-categories. Is that what you meant?

No, I mean that on the community page, where it goes "All categories", "Recent posts" and so on, moderators should also see a link to "Moderation interface". Or on each category. Whatever.

But yes, buttons on the Reports tab seem to work right now. Thank you!
