### ISSUE TITLE
YouTube integration can produce incorrect links

### ISSUE THREAD

**Issue by heyaurelien** [itchio/itch.io#715]
Hi,
Some YouTube channels can have multiple links. Mine have those for example:
youtube.com/channel/UCCjlo6Ihet_T3X6bKLJzPsA
youtube.com/FoxFiesta40 or youtube.com/user/FoxFiesta40
youtube.com/c/AurelienVideos
I connected my YouTube account on itch and in https://itch.io/partners/application it showed me this http://puu.sh/xIpW4/2fb0c6c8fc.png which is cool, but it produces a wrong link: "https://www.youtube.com/user/aurelienvideos" instead of the /c/ link.
Hope it helps!

**Comment by leafo** [comment]
Thanks for the report, fixed now
