### ISSUE TITLE
Error Uploading Game for CFN Game Jam

### ISSUE THREAD

**Issue by weezyplayer** [itchio/itch.io#716]
I fell asleep while uploading my game to the CFN Game Jam. When I woke up it said that I had an issue while uploading. I checked my game's page and another user said they couldn't access any build or version of the game.

![screenshot 94](https://user-images.githubusercontent.com/32270096/30814005-53bc44d6-a1e5-11e7-927a-1039c4b45dfe.png)

**Comment by leafo** [comment]
I don't see any completed uploads on your page? Are you sure the file is below the upload limit? 

Do you have unreliable internet? If so I recommend using butler: https://itch.io/docs/butler/

There are issues we're aware of with uploads

**Comment by weezyplayer** [comment]
Here are some more pictures. I zipped my game but before it zipped the total file size is 363mb/ 750mb limit. I haven't tried using butler yet I recently have not experienced any internet instability.

![screenshot 95](https://user-images.githubusercontent.com/32270096/30815651-27e99994-a1ea-11e7-817f-466bfe53dd9e.png)
![screenshot 96](https://user-images.githubusercontent.com/32270096/30815666-31eadbb0-a1ea-11e7-8c39-6714bc41ac14.png)

**Comment by leafo** [comment]
A jam submission has no effect on uploads, so it seems like you just can't upload the file? Do smaller files upload okay?

You can try running the upload with your browser console open to see if it reveals any additional errors.

Hit `Ctrl+Shift+I` to open the console, then try starting an upload.

**Comment by weezyplayer** [comment]
I was able to submit my project to one of the judges of the CFN Game Job. I believe I am just experiencing connectivity issues because of increased internet traffic in my area. I will try to upload again later but as far as the Game Jam issue is concerned, that issue has been resolved.

**Comment by leafo** [comment]
Alright, going to close the ticket. Feel free to open it if you figure something out.
