### ISSUE TITLE
The user_links on a user's profile page should declare rel="me"

### ISSUE THREAD

**Issue by 00dani** [itchio/itch.io#719]
Currently you can optionally add a Twitter account and a personal website URL to your user profile - when your profile is viewed, the website link is displayed with `rel="nofollow"`, and the Twitter link is displayed with no `rel` attribute.

It would be appropriate for both links to use [the `rel="me"` attribute](http://microformats.org/wiki/rel-me) - this link type means that the referenced page represents the same person as the current page. Twitter and many other sites already do this. It's useful because it allows [automatic verification](http://www.kevinmarks.com/distributed-verify.html) that both pages belong to the same person.

Also, in this particular case - since Itch profiles are subdomains - this change would make it immediately possible to [IndieAuth](https://indieauth.com/) *using* your Itch subdomain. Which is pretty cool.

(It's valid to declare multiple link types, so the website link could become `rel="me nofollow"`. Although I think `nofollow` isn't really necessary here anyway.)

**Comment by leafo** [comment]
I added `rel=me`, we don't add nofollow to that twitter link, maybe you were looking at something else?
