### ISSUE TITLE
Feature Request: Clickable banner image on game pages

### ISSUE THREAD

**Issue by mattconsto** [itchio/itch.io#725]
Essentially the request is that if a game has a banner image and the user clicks on it, it links back to the front page of the game. Currently if you want to return to the main page from a dev blog or forum post you have to click a tiny little link which isn't user friendly.

**Comment by leafo** [comment]
This is deployed now, tell me if you encounter any issues!

**Comment by mattconsto** [comment]
Works perfectly, thank you very much
