### ISSUE TITLE
Blank pages, CSS rendering error

### ISSUE THREAD

**Issue by filipemeneses** [itchio/itch.io#730]
There is something wrong with the CSS in the pages.
![image](https://user-images.githubusercontent.com/10226292/31851616-1a86d902-b648-11e7-9fe9-c8c7a955ffc1.png)

Once I deleted the CSS sources in Chrome Inspector, it showed the content.

I'm using Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by filipemeneses** [comment]
Never mind, it was my Chrome bug. Updated the version to 62.0.3202.62 and solved.

**Comment by fasterthanlime** [comment]
That sounds like a pretty bad bug - could you link to the related Chrome issue?

**Comment by filipemeneses** [comment]
I suppose is a Chrome bug since after updating solved this issue and CodePen website (which had the same behavior at the login screen https://codepen.io/login?secure=true)
