### ISSUE TITLE
Difficulties Logging In 

### ISSUE THREAD

**Issue by kandiiyuutaamu** [itchio/itch.io#733]
I am still trying to log onto @itch.io with my account but so far it is not working. My old computer crashed so I am trying my very best to recover my account with some games I have either purchased or collected when the crash happened. Is there another way to this?

**Comment by leafo** [comment]
If you've purchased things then we can use your payment information to recover your account. You should contact support@itch.io with details about previous transactions and we'll ask for any additional information.

**Comment by leafo** [comment]
Closing this, feel free to open again if you've found a bug on the site
