### ISSUE TITLE
Recover username

### ISSUE THREAD

**Issue by kandiiyuutaamu** [itchio/itch.io#734]
Hi @itch.io again! I am also trying to recover my username when I tried to register it as I can't directly log into my account within the current situation but it doesn't identify me as it thinks I am another/different user trying to create a new account. #733

**Comment by leafo** [comment]
Is this a bug or have you forgotten your account information? For account support you should reach out to support@itch.io

**Comment by leafo** [comment]
Closing this, feel free to open again if you've found a bug on the site
