### ISSUE TITLE
Butler not showing my new Update

### ISSUE THREAD

**Issue by Blackdiskette** [itchio/itch.io#736]
hi all !!
I make an Update for my game this morning.I push it with butler,and has always butler do the job and at the end say to me, my upload will be on soon.
But it was  5 hours ago ans i can't see my Update on my game page. 
I tcheck butler status and everything seems good.
What can i do ? Please help.

**Comment by Blackdiskette** [comment]
i have a files size limit of 2GB and my game size is 2.62GB ?But i read,with butler there is no more size limit is it true ? or my problem came from this ?

**Comment by fasterthanlime** [comment]
We've had a few server issues today, but everything is back to normal - all builds should be processed in a few minutes.

Thanks for your patience!
