### ISSUE TITLE
Bulk Keys info grid - External keys - Clarification needed

### ISSUE THREAD

**Issue by adambiser** [itchio/itch.io#740]
I have two existing bulk key groups and in the "External keys" column they both have a null symbol ∅.
Does this mean those groups do not have access to external keys?

Could this be made a little clearer?  Such as "no" or checkmark as in the Download keys Claimed column?

Thanks.

**Comment by leafo** [comment]
Sure, it's now deployed.

**Comment by leafo** [comment]
Sure, it's now deployed.
