### ISSUE TITLE
The Itch.io Android app for developers can't be moved to the SD card.

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch.io#741]
I recently purchased an SD card for my phone. I can move some apps to the SD card, but others don't let me. It appears that Android requires apps to specify if they are able to be moved to the SD card or not. 

While the Itch.io app doesn't take up too much space anyway (and therefore this is low-priority), it would be nice if you allowed us to move it to the SD card. Thanks.

**Comment by leafo** [comment]
We don't maintain the itch.io android app, and it wasn't developed by us either. I don't think that project is going to see any more development either. In the future we might make our own.

**Comment by aaronfranke** [comment]
Oh wow, I didn't realize this was an unofficial app. I'll leave this issue open, in case you do decide to make an official app. Meanwhile, I've reported it here instead: https://github.com/itchio/itch.io/issues/741
