### ISSUE TITLE
Closing itch.io app shuts down game - Unity doesn't save

### ISSUE THREAD

**Issue by Democide** [itchio/itch.io#742]
So I had this reported from one of my beta testers:

> Bad Bug?   My program seems to have closed while i was alt tabbed.     I lost all my progress.    When i just restarted the program, I was back on the 2nd map.  I lost all my progess since the last time i quit out to the menu.     I was on the 3rd map.(edited)
> Does this mean it crashed and didn't save?
> oh i see how it happened....  that's horrible
> I quit out of Itch.io!    i closed that program... and it shuts down my Nowhere Prophet!!
> it shuts it down so hard that it doesn't even bother to save.

As far as I can tell the app closes hard and then doesn't save properly. The game is built with Unity and uses

OnApplicationPause() 
and 
OnDisable() (which is also called when destroying)

to save the game state. Obviously this did not seem to happen here.

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch/issues/1567
