### ISSUE TITLE
discussion boards not available to users when game is restricted???

### ISSUE THREAD

**Issue by charliesgames** [itchio/itch.io#743]
This seems to be the case here. I've restricted my game (son of scoregasm) so it's only accessible to those who have the link and password, but the community/discussion board isn't showing up on the page and isn't directly linkable. I can see the board if i log in as myself (i've even made a post!) but it doesn't seem to be showing up for others.

I'm guessing this is a bug? Though if not it would be a super useful feature to have.

Cheers
Charlie

**Comment by leafo** [comment]
when you put your game into restricted mode then only people who can access the game page can access the discussion board. Are you saying you want the page to be restricted but the discussion board to be public, or there's a but that's preventing people from finding the discussion board?

**Comment by charliesgames** [comment]
I'm saying if i issue a password to someone to access the page, that the community stuff isn't showing up. They also can't directly access the discussion board via url.

Cheers
Charlie

**Comment by leafo** [comment]
Thanks for the clarification, that's a bug :). I'll try to fix it shortly.

**Comment by charliesgames** [comment]
Thanks :)

**Comment by leafo** [comment]
This should be fixed now, give it another try and tell me if you notice any issues.
