### ISSUE TITLE
Image Upload error "404"

### ISSUE THREAD

**Issue by dalegdawg** [itchio/itch.io#744]
I'm not sure if it's just me but when I'm adding a comment onto my game and I click the image icon to upload a new image file, I just get the loading overlay. Checking the Chrome's developer console it's giving this error "Failed to load resource: the server responded with a status of 404 (Not found)" dashboard/upload-image?lightbox=true.

I'm using Chrome Version 62.0.3202.89 64bit and Windows 10 64 bit.
![untitled](https://user-images.githubusercontent.com/30841350/32756821-04f80d42-c8d4-11e7-878d-15c16105ae8d.png)

**Comment by leafo** [comment]
Thanks for the report, definitely a bug. I just pushed out a fix.
