### ISSUE TITLE
Layout of Tiled page messed up on Firefox (looks fine in Chromium)

### ISSUE THREAD

**Issue by bjorn** [itchio/itch.io#745]
It is not possible to read the text properly on Firefox. See screenshot comparing it to Chromium:

![selection_227](https://user-images.githubusercontent.com/531764/32827596-05815092-c9ed-11e7-8705-f824e74d6635.png)

https://thorbjorn.itch.io/tiled

I have a hunch that it may be because Chromium elided "Tiled for Windows (64-bit), installer (without Python support)" (a download at the bottom), whereas Firefox didn't and maybe that caused the whole page to become wider and then clipped.

**Comment by leafo** [comment]
Sorry about that, thanks for the report. It's from switching to flexbox for columns with the [new theme editor](https://itch.io/updates/a-new-theme-editor-for-project-pages). Fixed now
