### ISSUE TITLE
build stuck processing.

### ISSUE THREAD

**Issue by charliesgames** [itchio/itch.io#747]
Hi,

I've pushed a build of my game with butler, which normally works great, though this time it seems to be stuck processing. 

The game is charliesgames/son-of-scoregasm build #54394 (from #54060). it's a linux version.

Could this be un-stuck? I'm intending to launch soon and need to get things out to testers. I can't see an option in butler to cancel/overwrite a build that's processing.

Cheers
Charlie

**Comment by charliesgames** [comment]
This has been  fixed now.

**Comment by fasterthanlime** [comment]
For reference:

This was a bug in the new concurrent version of butler's backend, some builds got skipped over. In this particular case, 4 were "stuck" - after deploying the fix, these were all processed and this shouldn't happen anymore.
