### ISSUE TITLE
Bug: External keys - Remaining keys - View all shows all keys for all types

### ISSUE THREAD

**Issue by adambiser** [itchio/itch.io#750]
I have a game with two external key types: Steam and Desura.  To the right of each type in the Remaining keys grid is a "View all" link.  Both links show the same list, a combination of all keys from both types, instead of the list of keys for each individual type.

**Comment by leafo** [comment]
Thanks for the report, it's fixed now. (I also updated the keys page to show the total keys added in addition to the available ones)
