### ISSUE TITLE
Bug: Link to Steam page from "App store links" doesn't show up

### ISSUE THREAD

**Issue by dos1** [itchio/itch.io#751]
When I use "App store links" feature to add Google Play link, it works nicely - the button shows up on the game page in "Also available on" section: https://dos.itch.io/love-case

However, if I add link to Steam, it doesn't show up at all: https://dos.itch.io/the-secret-of-tremendous-corporation

**Comment by leafo** [comment]
Steam now shows up in the "Links" section on the more information dropdown like the other links on the page.

**Comment by dos1** [comment]
Fair enough, thanks!
