### ISSUE TITLE
Feature request: Add browser icon to platform icons

### ISSUE THREAD

**Issue by dos1** [itchio/itch.io#752]
Due to #206, I'm often ending up with setting up a duplicated game pages with no downloads, just a big link to the same game on other user's profile. Those end up with no platform icons being shown up.

On the other hand, when I add a game which is played in the browser... it also doesn't show up any platform icons at all.

Those two cases are visually undistinguishable while on the profile page. A small tag like "Play in the browser" visible on collections or jams would be nice.

I have workaround this on my profile - https://dos.itch.io/ - by adding the globe icon to browser games using custom CSS. It would be nice to have this out of the box.

**Comment by leafo** [comment]
The "play in browser" label is now shown on games on profile pages. Also if you didn't notice, you can add games to your profile that you are an admin for, so you don't need to use duplicate project pages anymore.

I'm working on updating the profile theme editor, if you've got any ideas for things you'd like to see feel free to make a new ticket with requests. Thanks
