### ISSUE TITLE
Can itch.io be used for something other than games?

### ISSUE THREAD

**Issue by EnzoBM** [itchio/itch.io#758]
I have a book that I would like to publish by myself and have the ability to either give it away for free or let people pay for it, which is exactly what itch.io allows, but the website seems to be aimed only at videogames.

**Comment by quyse** [comment]
itch.io supports all sorts of content, and there's a whole section for books: https://itch.io/books :) See links to different types of content on the left side of the frontpage, under "Browse". To upload a book, just choose proper value for "Classification" field when you create a project, or change it later in a dashboard.

**Comment by leafo** [comment]
Just to add to above, although the site is primary focused on games, when you choose a different content type we change how we refer to your project everywhere. You can even provide a custom noun if our names aren't right for what you're building. If you see something that's overly game specific feel free to open a ticket and we can update the copy on the page. (Much of it was written it where games were the only thing)
