### ISSUE TITLE
Can't sign in with GitHub authentication

### ISSUE THREAD

**Issue by Kazuo256** [itchio/itch.io#760]
Since I first created my account, I had left it signed in so it wasn't an issue. Today, I had to re-sign in, but got the following error when trying to use GitHub authentication:

![error](https://user-images.githubusercontent.com/645222/33720594-8f7b4e50-db4b-11e7-9e38-8bc6e74eae98.png)

As you can see from me posting this issue, my github account is working properly.

**Comment by leafo** [comment]
Sorry about the issue, our server had a scheduled reboot from our host and a service didn't start up correctly. GitHub login should be working again now. Thanks

**Comment by Kazuo256** [comment]
Yes, it works now. Thanks!

**Comment by korgibaniclub** [comment]
Is Happen again

**Comment by jrgibson** [comment]
I can confirm that it’s still happening. 2020-04-03.

**Comment by maschere** [comment]
Same here 
![chrome_gKoN1dYgRx](https://user-images.githubusercontent.com/15802614/78934601-83f3a300-7aab-11ea-9708-b23081ab6f58.png)

**Comment by leafo** [comment]
Could you try again, issue should be resolved.

Thanks

**Comment by maschere** [comment]
Yes it's working now. Thank you!

**Comment by KhanessKA** [comment]
![image](https://user-images.githubusercontent.com/82938832/204154570-3662e3e9-d384-466d-96df-aff37e8dcab7.png)
Pls help i cant sign in with Github

**Comment by koliwbr** [comment]
I have same problem, while login in via GitHub, I get 'missing token' error

**Comment by FeuerTiger86** [comment]
Same for me, though I could still log in with my e-mail address and the GitHub password. I had just changed my user name, maybe that has something to do with it.

**Comment by Sasy00** [comment]
I too am getting this error right now

**Comment by merick97** [comment]
I'm getting this error as well

**Comment by danspinola** [comment]
I'm getting this error as well. "missing token" when I try login-in through GitHub.

**Comment by gu-fan** [comment]
got this error. but get recovered after I changed my proxy server

**Comment by macosgupta** [comment]
Currently have the same problem on mobile, whether on Wifi or 4G

**Comment by Geezgus** [comment]
Me too :(

**Comment by WeebyJay** [comment]
I'm also having this issue, specifically after I cleared my cookies.

**Comment by KirillKuzyk** [comment]
Same issue, can't login.

**Comment by danspinola** [comment]
I found a workaround, but it might not work for everyone. Previously I only used the social authentication through github, so I had not yet setup a password. Luckily I still had itch logged in one of my devices, so I went to `Settings -> Basic -> Password` and set up a password for my account. Now I can login normally using email + password instead of the github.

**Comment by Daniel-Chin** [comment]
It's happening again over 2 minutes. Maybe consider at least changing the error message?

**Comment by lmReef** [comment]
Happening to me too on all my devices. Checked using vivaldi, chrome, and firefox as well as in incognito.

**Comment by alperenbabagil** [comment]
I have the same problem. Please fix it ASAP, I cannot acceess my assets

**Comment by heldermmelo** [comment]
Me too

**Comment by K0rvaxX** [comment]
Hi ! 
I'm getting the same error as well =/
Any news or workaround ? :)

**Comment by ChromicQuanta** [comment]
Ditto.

**Comment by Beetrootmonkey** [comment]
I have the same issue. For anyone else that gets the "missing token" error, please have a look at https://github.com/itchio/itch.io/issues/1409 since https://github.com/itchio/itch.io/issues/760 is closed.

**Comment by tonnniiii** [comment]
![image](https://user-images.githubusercontent.com/92284777/229182318-2f09b654-5cb3-446a-8e91-1d9945f47e4a.png)

Same issue, Anyone can help?

**Comment by BatturTugsuu** [comment]
![ae41ac957a971a606075a7070df29163](https://user-images.githubusercontent.com/65908031/229359410-2fd9644f-5c35-4b51-98bb-dc737a5ed9e0.png)
still happening after many many months down the road

**Comment by R4Y-repo** [comment]
removing the cookies solved the issue

**Comment by lmReef** [comment]
> removing the cookies solved the issue

This doesn't seem to help for me. I tried removing cookies for both itch and github :c

**Comment by CrochetOtterStudioz** [comment]
1/22/24 still happening

**Comment by Shouri69** [comment]
SOMEONE PLEASE DO SOMETHING.
I'M UNABLE TO ASK THE DEV THAT HOW TO IMPORT & USE PATCH FILE IN RENPY'S GAMES ON ANDROID?!
PLEASE SOMEONE HELP !!
