### ISSUE TITLE
Unpublished devlogs are actually published on the "View all posts" page

### ISSUE THREAD

**Issue by bjorn** [itchio/itch.io#762]
Currently writing a new devlog and I didn't publish it yet, but I noticed it's already visible here:

https://thorbjorn.itch.io/tiled/devlog

(even when not logged in)

I would suggest to show it only when I am logged in, with a "DRAFT" label on it. Check out how GitHub does this for releases, for example.

**Comment by leafo** [comment]
Sorry about that, another feature messed up visibility checking. It's fixed now. I also added a **DRAFT** label in front of the title if the post displayed isn't published
