### ISSUE TITLE
Cloudflare is showing captcha on static assets 

### ISSUE THREAD

**Issue by badon** [itchio/itch.io#764]
![itch io hidden captcha s 2017-12-12-tue-23-39-37](https://user-images.githubusercontent.com/5954485/33927156-0071c406-df96-11e7-9ecf-f255864f0a67.png)
CAPTCHA's should not block CDN files because the user can't see the hidden CAPTCHA's on embedded files. This is the most common site-breaking bug on the internet, and it happens because people setup CloudFlare or other domain-specific CAPTCHA systems without ever testing them. If you want CloudFlare CAPTCHA's on all of your page's resources, you have to have all of your resources on a single domain. So, for example, instead of mixing itch.io and static.itch.io, you would simply put everything on itch.io. Probably a better solution is to put your CAPTCHA's on itcho.io, but DO NOT put any CAPTCHA's on static.itch.io. Turning CAPTCHA's off for static.itch.io would immediately solve this problem.

For now, the workaround is to open one of the CDN  files individually, pass the CloudFlare CAPTCHA, then reload the itch.io page. That workaround will work only briefly before the hidden CAPTCHA is (not) presented again (invisibly hidden so the user can't see it). Here is a 25-second YouTube video I made showing this exact same type of problem on reddit - I'm not exaggerating when I say this problem is the most common site-breaking bug on the internet:

https://www.youtube.com/watch?v=eVtEoXsO9-Y

It used to be I could use Tor Browser to test for these kinds of problems, but CloudFlare has started passing Tor Browser, so you have to have another way to reliably trigger CloudFlare CAPTCHA's. As far as I am aware, there is no "test mode" that CloudFlare offers so you can trigger CAPTCHA's and test your site. It might be worthwhile to ask them to provide tools for testing their CAPTCHA's. Something like a ?CAPTCHA=YES parameter inserted on URL's would probably be an easy way to do it.

**Comment by badon** [comment]
Your title change is wrong. CloudFlare's CAPTCHA's are specific to a domain, not to the type of content sourced from that domain. So, the problem is absolutely 100% about static.itch.io, not "static assets". I will test again with the new settings you have applied and report back.

**Comment by leafo** [comment]
the subdomain static.itch.io is only used by use to serve static assets, and it's the domain using cloudflare (the top level domain is not)

**Comment by badon** [comment]
Right. That's where the problem is, and that's why I specified it in my bug report. Makes sense, yeah?

I tested the PC software and the site again, and the problem is still there. Is there a delay for the new configuration to propagate to CloudFlare's network? Screenshots below.

![itch io hidden captcha s 2017-12-13-wed-09-13-24](https://user-images.githubusercontent.com/5954485/33952265-1fb3e88a-dfe6-11e7-8ee8-6b0fd0aae077.png)
![itch io pc software captcha 2017-12-13-wed-09-13-03](https://user-images.githubusercontent.com/5954485/33952267-203b43ac-dfe6-11e7-983e-f9c4bd3d9807.png)

**Comment by leafo** [comment]
I don't know how long until it takes affect, I would assume it's almost instant. I've lowered the security settings as much as I can on our plan. Could you also try loading it in a browser that doesn't have cookies set, you might have been tagged for a challenge page despite it being turned off.

**Comment by badon** [comment]
I just tried it again in a web browser, both with and without cookies. Both worked! So that appears to be solved, then. The software still doesn't work, but it's probably just showing me a cached page. I'm not sure how to test it further. Maybe it's best to just wait. It should eventually work if everything else is working.

**Comment by leafo** [comment]
Thanks for checking. Feel free to open again if it's still not working on the app.

**Comment by badon** [comment]
It looks like I don't have the privileges needed to reopen this, so can you do it for me? I finally found why it won't update, when I stumbled on the log file. It's getting a CloudFlare CAPTCHA when it tries to fetch an update from this URL:

https://nuts.itch.zone/update/win32_ia32/23.6.0

Here's the log output:

[2017-12-17 @ 20:32:11.425] [reactors/self-update] Checking...
[2017-12-17 @ 20:32:13.847] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/win32_ia32/23.6.0: 403
[2017-12-17 @ 20:32:13.848] [reactors/self-update] Error: While trying to reach update server: 
[2017-12-17 @ 20:32:19.694] [reactors/self-update] Checking...
[2017-12-17 @ 20:32:20.072] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/win32_ia32/23.6.0: 403
[2017-12-17 @ 20:32:20.073] [reactors/self-update] Error: While trying to reach update server: 

You need to disable CAPTCHA's on nuts.itch.zone too. That should fix it.

**Comment by leafo** [comment]
I set nuts.itch.zone to bypass cloudflare, you can try again

**Comment by badon** [comment]
I'm getting a slightly different error message in the logs now:

[2017-12-17 @ 21:33:50.723] [reactors/self-update] Checking...
[2017-12-17 @ 21:33:51.926] [reactors/self-update] Server-side error on HTTP GET https://nuts.itch.zone/update/win32_ia32/23.6.0
[2017-12-17 @ 21:33:51.926] [reactors/self-update] Error: While trying to reach update server: net::ERR_CONNECTION_CLOSED

**Comment by leafo** [comment]
Hmm, looks like we're using cloudflare to handle SSL certificate generation on that domain. I had to turn it back on, but I tried updating the security settings. Please try once more, thanks

**Comment by leafo** [comment]
You might want to wait a bit though, looks like it's taking a moment to re-enable the https. This URL should load in your browser: https://nuts.itch.zone/update/win32_ia32/23.6.0

**Comment by badon** [comment]
I tried it several times, and it appears to be fixed, with no errors in the UI or the logs:

[2017-12-17 @ 21:45:44.415] [reactors/fetch] Fetching the usuals
[2017-12-17 @ 21:45:45.980] [reactors/self-update] Checking...
[2017-12-17 @ 21:45:47.118] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/win32_ia32/23.6.0: 204
