### ISSUE TITLE
Sales default to "draft" status, but this isn't obvious

### ISSUE THREAD

**Issue by Draknek** [itchio/itch.io#770]
I think about 50% of the time I set up a discount, I don't realise that it hasn't actually been scheduled. You need to submit the form, notice the message at the top saying it's not active, go *back* to the form, and change it from "draft" to "published".

This is because the draft/published option exists on the "edit sale" form but not the "new sale" form.

This option should exist on both forms, so you can create a sale and make it live immediately.

**Comment by leafo** [comment]
I agree that it's not obvious that a sale is in draft mode. But, I'd also like people to get an opportunity to review the page they just created before publishing it. Maybe a much larger and obvious banner up top saying that it's in draft mode?

I think it's also worth adding a section to the dashboard that shows draft sales that are upcoming as a reminder.

**Comment by Draknek** [comment]
This is fair, but you can do that by having the draft/published option default to draft - this is how it works when you create a new game.

**Comment by leafo** [comment]
Just a small update, I made the draft text on the top of the page more obvious. I still plan to make some more changes to address this.
