### ISSUE TITLE
Support links are not easily accessible

### ISSUE THREAD

**Issue by keshav-c** [itchio/itch.io#773]
Sorry and ignore this if I'm doing something wrong. 

Say you are in the page "https://itch.io/games", the navigation bar with the support links (support, blog team, faq) is in the bottom of the page which keeps loading more titles as you keep scrolling.

So I had to disconnect the wifi to stop the page from updating, then I could access those links. I only encountered this in the mentioned page though, and not in the home page.

**Comment by leafo** [comment]
You can disable autoloading on your account settings page. Otherwise, instead of disabling wifi you should be able to go to any other page on the site other than our browse pages.
