### ISSUE TITLE
Browser games don't work on iOS

### ISSUE THREAD

**Issue by dos1** [itchio/itch.io#776]
I've recently got an iPhone for testing, but I can't seem to open any in-browser game on itch.io using it. I only see the button "Play game", which changes into "Resume game" after I tap on it and nothing else happens.

I've looked into the devtools and it looks seems like the iframe gets loaded, but its width and height is set to 0. Supposedly it should enter the fullscreen mode, but Mobile Safari does not support it at all (yes, it's that bad :P)

I've tested with iPhone 5S on iOS 11.2.1.

**Comment by leafo** [comment]
Could you try again, I've pushed out some changes with how games are loaded.

iOS does not have a fullscreen browser api that we were previously depending on

**Comment by dos1** [comment]
Much better, thanks :)
