### ISSUE TITLE
Script 'Sprite_Battler' line 80 TypeError occurred

### ISSUE THREAD

**Issue by MysticRob** [itchio/itch.io#779]
I get to what I believe is the final boss in the long hall (without spoiling this for anyone). I talk to the NPC several times and get "..." about four or five times, and then the full dialog triggers and then the battle begins - but before the battle initiates I'm hit with a black screen and an error window that reads: 

"Script 'Sprite_Battler' line 80 TypeError occurred.
no implicit conversion from nil to integer" 

I got this point this morning with v4.2 and then saw that version 5 was released and was excited assuming this may fix the bug. However, the game still crashes.
![crash](https://user-images.githubusercontent.com/35476768/34970393-32e0cbaa-fa42-11e7-9452-f10922b91da9.png)

**Comment by fasterthanlime** [comment]
Hey, I see you've also reported this as a comment on the game's page - which is the proper place to discuss game bugs :)

Closing this.
