### ISSUE TITLE
Game Jam not showing up?

### ISSUE THREAD

**Issue by kestrelm** [itchio/itch.io#785]
Hello,

I created a Game Jam here:

https://itch.io/jam/creature-2d-animation-with-godot-engine-hackathon

But it is not showig up on the Game Jam, not even the upcoming Game Jam(s) list. Is there any option/flag I need to set to make it visible?

Thanks

**Comment by leafo** [comment]
Jams are reviewed before being put on the calendar. Once you publish your jam it's available directly by URL though. Your jam should be on the calendar now.
