### ISSUE TITLE
Mobile app not letting me login

### ISSUE THREAD

**Issue by dalegdawg** [itchio/itch.io#788]
​The app doesn't seem to let you log in if you have multiple projects.

I have 2 projects (one public and one restricted). The restricted project is new and since creating it, I can't log into the app anymore. It constantly says the login details aren't recognised.

I know they're correct though cause I tried logging into the website with the same details and I got in fine.

**Comment by leafo** [comment]
We didn't develop any of the native mobile apps, and they don't support our latest login API. Your best bet is to use the mobile website (but the dashboard isn't responsive yet).

What os are you on?

**Comment by dalegdawg** [comment]
Don't know which os you're referring to so;

Desktop - Win 10
Phone - Android 7.0



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by leafo** [comment]
I was just curious which app your were using. Thanks.
