### ISSUE TITLE
itch.io main page has misleading Twitter Card

### ISSUE THREAD

**Issue by salty-horse** [itchio/itch.io#791]
If someone mentions "itch.io" on Twitter, Twitter automatically parses it as a link, and generates a "Twitter Card" based on metadata in itch.io

The Twitter card includes an image.

The main page of itch.io defines its card to be the image of the first featured game. This is misleading and makes one think the link is to a specific game.

The markup also seems wrong. It's currently showing
```html
<meta name="twitter:card" content="gallery"/>
```

but "gallery" isn't a valid value, according to [Twitter's documentation](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started). It should be "summary" or "summary_large_image", "app" or "player".
It seems to get interpreted as "summary_large_image".

It should instead use the itch logo, and the card type should be "summary".

**Comment by eevee** [comment]
Along similar lines: the Twitter card for a game jam is initially the jam's cover image, but once games start to be submitted, it becomes the cover image of an (arbitrary?) game _within_ the jam.  Which can have some [curious side effects](https://twitter.com/WAHa_06x36/status/961635060444254208).

**Comment by leafo** [comment]
I updated the outdated twitter cards. I also removed showing the games from the homepage and jam pages. (might take a moment to appear, since cache has to purge)
