### ISSUE TITLE
Theme editor link not visible

### ISSUE THREAD

**Issue by ptimebank** [itchio/itch.io#793]
On the page "Designing your page" it says:
"On the page of any project you're allowed to edit you'll find a series of settings links on the top of the page. The Edit theme link will open up itch.io’s theme editor."

I'm not seeing that link on my "edit game" page, 
https://itch.io/game/edit/225189
screenshot here: 
![itchio_where_theme_editor](https://user-images.githubusercontent.com/13146009/36301341-4f7fc236-12b9-11e8-8d71-8fe5a536de34.png)

Where can I find the theme editor link?

**Comment by fasterthanlime** [comment]
> Where can I find the theme editor link?

On the game page itself! Click "View page" to see it.

**Comment by ptimebank** [comment]
Thanks! I knew it had to be simple.
