### ISSUE TITLE
Cannot change primary email when certain condition is met

### ISSUE THREAD

**Issue by buckle2000** [itchio/itch.io#800]
## How to Reproduce:

1. register an itch.io account
2. [go here](https://itch.io/user/settings/email-addresses); set primary email to aaa.example.com
3. add additional email bbb.example.com
4. attempt to change primary email to bbb.example.com

## Expected Behavior:
Primary email changed

## Current Behavior
No error message, nothing changed

**Comment by leafo** [comment]
I just tested this and did not encounter the same issue. Depending on if the secondary email is verified or not, I get an error message saying that the email address is already in use. The error message is placed at the very top of the screen though, so it's possible you missed it?

I think having a "make primary" button on the secondary emails list seems like what you want.

**Comment by buckle2000** [comment]
Wierd. Closing for now.
