### ISSUE TITLE
Feature: Bitcoin Payouts

### ISSUE THREAD

**Issue by Masken8** [itchio/itch.io#801]
Since purchasing games with bitcoin have been available for about 2-3 years i thought why not have bitcoin payouts too(since im a little kid with no credit card or bank stuff)

I don't really know about any service to do this tho but it would be a nice addition if you find a way
it does not necesarily need to be bitcoin since it have gonne down maybe Litecoin or Etherum?

**Comment by bjorn** [comment]
Duplicate of #199.
