### ISSUE TITLE
Jam's "unrated games" page not discoverable, missing title and Twitter card

### ISSUE THREAD

**Issue by salty-horse** [itchio/itch.io#804]
While browsing a jam page, you may get a message directing you to /jam/JAMNAME/unrated (e.g. [https://itch.io/jam/finally-finish-something-2018/unrated])

This page includes entries that have less than 10 ratings.

1. The page should be more discoverable. I am guessing the message telling you about itonly appears if you're signed in AND submitted page to the jam...?
2. The page's title is just `<title>itch.io</title>`. It should be more informative.
3. The page should have a Twitter card (Unless this is on purpose, and only meant for jam participants to even see...?)

**Comment by leafo** [comment]
The link appears to people who are eligible to vote. It will never show to logged out users.

I added a title & twitter card to the page.
