### ISSUE TITLE
Feature request: Download icon

### ISSUE THREAD

**Issue by pfefferminzz** [itchio/itch.io#805]
If no platform icon and no 'Play in browser' are shown, there should be some kind of download available, right? In this case you could add a generic download icon (on listings, profile pages):

![itch-download](https://user-images.githubusercontent.com/5459440/37617693-23dac1e4-2bb4-11e8-80bf-318620f62558.png)

**Comment by leafo** [comment]
Do you think people are confused when they see pages like this, thinking there's nothing there?

**Comment by pfefferminzz** [comment]
I am confused when Games and Assets/Books/... are shown next to each other and both have no symbols (or some games have symbols). Feels like a bug. I do not think that pages without symbols would not offer any content. You are right, the problem is not 'no symbol' and whole pages filled with the same generic download icons won't help. So the better question might be:
Why is it possible to upload digital games without specifying platform(s)?

**Comment by leafo** [comment]
> Why is it possible to upload digital Games without specifying platform

Some people can upload pages that have placeholder or preview material for an unreleased games. Additionally some games maybe only be available for alternative platforms, like roms for retro consoles. It's unlikely we'll ever have icons for those since it would be a lot of assets to organize.

**Comment by pfefferminzz** [comment]
Hmmm okay. Sounds reasonable. Thank you for taking your time to answer my questions. I thought there was a simple solution, but obviously it's not that easy. Have a good day! :)
