### ISSUE TITLE
Our game is removed from the search results without notice

### ISSUE THREAD

**Issue by Ippokratis** [itchio/itch.io#808]
Our game, Baa politics and sheep, https://ippokratis.itch.io/baa-politics-and-sheep is removed from the search results without notice.

More than that, when I enter the site with my account and search Baa - I can see it, if I enter in incognito mode or if someone else enters from their itchio accounts no results are shown. So, I could be left with the impression that the game exists in the search results - while the rest of the world would not be able to see it.

https://youtu.be/4kfSo4YlfbU

Can someone from the stuff please explain what is the situation please ?

**Comment by fasterthanlime** [comment]
You marked the game as NSFW, so it only appears in search for

  * logged in users
  * who have NSFW enabled

That's why you see it when you're logged in - and many others do too :)

**Comment by Ippokratis** [comment]
Thanks Amos - Kind regards.
