### ISSUE TITLE
Email Requires Approval - Download Keys

### ISSUE THREAD

**Issue by neuroplanner** [itchio/itch.io#809]
Hello Itch IO team,

I've created download keys and will be sending an email to my Kickstarter backers.  Can you help approve the email content so I can send the reward The Brain Hacker Book to my backers?

Thanks a lot,
Kar Villard
NEUROPLANNER

**Comment by leafo** [comment]
Hello,

You account should be verified for email now. You can send it from your dashboard.

Thanks

**Comment by neuroplanner** [comment]
Thanks a bunch!

Warm hello from the lion city of Singapore.
Sent while crushing my goals!
