### ISSUE TITLE
Feature Request: Show duration of upcoming jams

### ISSUE THREAD

**Issue by prvak** [itchio/itch.io#813]
I would like to try a game jam. Ideally some longer one that haven't started yet. But how to find one? When I look at the [upcoming jams page](https://itch.io/jams/upcoming) I can see only how much time remains until the jam starts.

I have go to each jam's page and decipher the duration from the start and end information:
`May 18th 2018 at 11:59 PM to May 20th 2018 at 11:59 PM`
or
`Friday at 9:00 AM to May 11th 2018 at 9:00 AM`

It would be nice to be able to see duration of each jam directly at the [upcoming jams page](https://itch.io/jams/upcoming).

What do you think?

**Comment by leafo** [comment]
I agree, thanks for the feature request. I've added the duration to those pages (and any page that shows an upcoming jam like that)
