### ISSUE TITLE
Stripe not processing payments correctly

### ISSUE THREAD

**Issue by zratchet** [itchio/itch.io#814]
A user was unable to get through the payment process but got charged multiple times. However, my analytics screen shows no new purchase from them. (analytics screen is not attached due to private information)

**Comment by zratchet** [comment]
![Multiple payments](https://user-images.githubusercontent.com/7037698/38450386-849174d8-39e2-11e8-8364-9b5850935c8f.png)
![Unable to progress](https://user-images.githubusercontent.com/7037698/38450387-84a1f56a-39e2-11e8-9dc4-ddcd5fe2e68d.png)

**Comment by zratchet** [comment]
Chrome and Edge were used. Both failed.

**Comment by zratchet** [comment]
I believe the user tried one browser, got here and it failed to complete so tried the other one resulting in 2 charges causing the return

**Comment by zratchet** [comment]
Chrome was used first.

**Comment by leafo** [comment]
Thanks, I found the problem with the error handler, the glitch should be fixed.

Regarding the payments, I checked our payment logs and the transaction was denied due to invalid zip or postal code.
