### ISSUE TITLE
Feature Request: Blog

### ISSUE THREAD

**Issue by Doppp** [itchio/itch.io#816]
I love the DevLog feature (which we should keep) but I was wondering if it was possible to have full blogs for users (similar to https://itch.io/blog)? Basically, a user will have a main blog where they can post anything they want e.g. a tutorial article. It should also have the ability to link to devlog posts, we could have tags or categories for this. For example, I can post a devlog post on the main blog, tag it to game _x_, then when i go to _x_'s devlog, this post also shows up there.

**Comment by leafo** [comment]
You can do it but it's unadvertised and probably incomplete right now. If you want to try it out: https://itch.io/dashboard/posts

It's something we want to expand on in the future but not sure when that will happen

**Comment by Doppp** [comment]
Ah okay! What's the URL for the personal blog? Would it be `https://<username>.itch.io/blog`?

**Comment by Bigaston** [comment]
I think it can be a very good idea!

**Comment by leafo** [comment]
At the moment you don't get a blog post list, but I would imagine it would show up on your profile. The individual blog post URLs are shown to you when you create a post. They are on our top level domain right now.

**Comment by Bigaston** [comment]
Maybe create like a "project" to our blog post. We that we can made a post with no game?

And in our profile we can have a space with this post?

**Comment by tobiasvl** [comment]
Just chiming in here: It'd be great to have a list of all devlogs written by a user on the creator profile. (Right now they don't even show up on the community profile?)
