### ISSUE TITLE
Ludum Dare Browser Issues

### ISSUE THREAD

**Issue by Doppp** [itchio/itch.io#819]
I got this error when browsing through the [Ludum Dare page](http://ludumdare.itch.io).

![ludum dare games browser](https://user-images.githubusercontent.com/627410/39189557-17ed8390-4805-11e8-8316-c17c7ab49b42.png)

Also, the scrollbar on Windows is quite big and almost covers the other LD links. Maybe increase the height of that row or change the UI there? I would suggest a dropdown for choosing specific LDs, along the same row of the `All Games` and `Most rated` dropdowns. The current display is clunky.

**Comment by leafo** [comment]
That's a strange error, if you hard refresh does it still happen? What if you have the browser console open and refresh the page.

What browser are you on? The scrollbar should only appear when you hover over the jam listing, letting you go horizontally if necessary.

**Comment by Doppp** [comment]
The error doesn't happen anymore. Console is clean too. Might have been a one-off thing.

I'm on Chrome on Windows. It just looks weird because Windows renders the scrollbar differently from Mac. I understand that Mac's scrollbars are thinner so they don't appear as bulky as the Windows' ones.

**Comment by leafo** [comment]
Thanks for the update, maybe the json endpoint with the data had a hiccup.

> I'm on Chrome on Windows. It just looks weird because Windows renders the scrollbar differently from Mac.

I don't use mac, I use chrome on linux, which has same scrollbar style as windows chrome AFAIK. I don't mind the uglyness of the ui, it's easy enough to access all the jams.

**Comment by leafo** [comment]
Going to close this, if you have any further issues the relevant repository is is: https://github.com/leafo/ludum-dare-browser
