### ISSUE TITLE
Social sharing links on DevLog seem broken

### ISSUE THREAD

**Issue by bjorn** [itchio/itch.io#821]
When I go to my [latest devlog post](https://thorbjorn.itch.io/tiled/devlog/31935/tiled-115-released) and try to share it on Twitter or Facebook, the text on the shared message is "I just downloaded Tiled Map Editor by Thorbjørn", and it links to the main page for my tool.

Expected result (and I think this worked fine a few months back), is that the text uses the title of the DevLog and that it links to that particular DevLog.

**Comment by leafo** [comment]
Thanks for the report, it's fixed now.
