### ISSUE TITLE
Feature Request: Analytics: Track launch count for web games

### ISSUE THREAD

**Issue by yscik** [itchio/itch.io#822]
Hi,

It would be nice to see how many times players started the html5 embed on the game page. (When autostart is off). It could be tied to the 'Run game' button. 

I know this would probably be possible with using our own Google Analytics account or putting something in the embedded html, but those seem a bit overkill, and I think this would be a good fit for the built-in analytics view which already shows page views and download counts.

**Comment by leafo** [comment]
We have a metric we collect called plays that increments when a html game has been run & open for more than 30 seconds. Does that work for you? We currently don't expose it on analytics but we can add it.

**Comment by stavrossk** [comment]
@leafo Where can I see this metric?

**Comment by leafo** [comment]
@stavrossk it's not public right now

**Comment by stavrossk** [comment]
@leafo It would be nice if you could add it to analytics.

**Comment by yscik** [comment]
That would be perfect!

**Comment by rubenlg** [comment]
+1 I would also love to see that metric. I can also measure this with Google Analytics, but until #794 is fixed, I get ~double counting of users and it's a bit harder to do reliable math between visitor and player counts.

Extra points for having the number in the graph, next to Views, to see how the play-through-rate changes over time as we change the landing page.

**Comment by GieziJo** [comment]
+1 Is there any progress on this? Would be really nice!

**Comment by azsdaja** [comment]
@leafo — can you tell if it's still in plan to add this feature? Fingers crossed for seeing this one day on Itch.

**Comment by nathanseyler** [comment]
@leafo yes I'd love to see this.  My page features my game strictly as WebGL embedded content.  Please do expose that metric so that we can see how many folks actually launched our content.

**Comment by GieziJo** [comment]
The metric has been implemented, thanks a lot :)
The issue could be closed I think.
