### ISSUE TITLE
shallow .exe would not be visible after update

### ISSUE THREAD

**Issue by delahee** [itchio/itch.io#824]
I am adding a .exe to my release to bootstrap swf interpretation ( in the .exe, I have some nvidia api calls to trigger the discrete gpu )

Problem was my exe was not transmitted when I updated the game, I had to run "integrity check" so local version got verified.

Maybe there is a tiny thing that got overlooked by the update script?

![capture d ecran 2018-04-30 14 01 07](https://user-images.githubusercontent.com/644444/39426155-04ed182c-4c7f-11e8-81da-cfad12cbdfef.png)
![capture d ecran 2018-04-30 14 01 29](https://user-images.githubusercontent.com/644444/39426156-05019090-4c7f-11e8-944b-d88da8efc5ce.png)

Thank you!

**Comment by delahee** [comment]
Btw since the problem might be related to me doing stupid things feel free to close if you don't reproduce.

**Comment by fasterthanlime** [comment]
@delahee I've checked the latest build and the `.exe` is indeed there.

My best guess is that your version of the game had not been updated by the app yet when you checked if the .exe was there (v23 checks for game updates every 30 minutes by default).

**Comment by delahee** [comment]
Well the .toml was update actually... That is why I thought something was odd ^^'. 
When you read this, please do close as it's quite a minor issue but it may help understanding some other thing.

Thanks a lot for your time and dedication.

**Comment by fasterthanlime** [comment]
Mhh that is odd indeed. I'd look into it deeper but I've grown tired of investigating v23 bugs, I've spent 6+ months on a rewrite so I don't have to do that, so thanks for offering to close it - if you're able to reproduce that with v25 (coming out soon(TM)), then I'll definitely be interested!
