### ISSUE TITLE
PuzzleScript games don't run on mobile

### ISSUE THREAD

**Issue by Draknek** [itchio/itch.io#826]
E.g. https://marcosd.itch.io/sleepy-players

It says "This game is not designed to run on your device", and tapping "run game" anyway results in the title screen appearing but not being interactive.

Puzzlescript games should run on touchscreen devices. E.g. https://www.puzzlescript.net/play.html?p=9ebe1e5ad44ac22259343de170a3b337 works fine.

This is on my Android phone with Chrome 66.0.3359.126

**Comment by leafo** [comment]
In order to remove the warning about not being compatible, you need to check *Mobile friendly* on the game edit page.

I'll take a closer look to see why the iframe embed of the game isn't working on a phone

**Comment by leafo** [comment]
I tested sleepy players by direct url in the phone and it still doesn't work. You can try here: https://v6p9d9t4.ssl.hwcdn.net/html/877883/index.html

Do you know if the mobile support is something that needs to be enabled when the game is exported?

**Comment by Draknek** [comment]
Huh! It shouldn't be. I guess this is a PuzzleScript bug not an itch.io bug

**Comment by leafo** [comment]
It might be code that's injected by puzzlescript.net on top of the game. In any case, if you figure out what's going on I'd like to know because it would be cool to support mobile puzzlescript games.
