### ISSUE TITLE
Feature Request: Export a game collection to a CSV file.

### ISSUE THREAD

**Issue by stavrossk** [itchio/itch.io#830]
It would be nice if itch.io would allow me to export and save to my computer a CSV file from any of my own collections to keep it for my records. It would have all the basic game info metadata.

**Comment by Sahriyaljhee** [comment]
Feedback on issue

**Comment by Sahriyaljhee** [comment]
receiving notifications thereads

**Comment by stavrossk** [comment]
@leafo Perfect, thanks a lot for responding to my request. This file has everything I need. An XML or CSV file so I can import the data to other applications programmaticaly would be a welcome addition but I'm also very happy with the feature as it is.

**Comment by leafo** [comment]
Glad it works, going to close this issue.
