### ISSUE TITLE
brute anneversery

### ISSUE THREAD

**Issue by freekbertens** [itchio/itch.io#832]
i was downloading brute for free because of the anneversary and needed to go so closed it of now i can't redo the download and i would need to buy it and wel it said i claimed it

**Comment by leafo** [comment]
Hello, in order to keep access you need to claim the download page. If it said you claimed it then it's attached to your itch.io account. 

If you weren't able to claim it then you can try reaching out to the developer to see if they are willing to generate a key for you.

**Comment by freekbertens** [comment]
alright thx
