### ISSUE TITLE
HTML games breaks on relative paths

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#836]
[Original issue](https://github.com/itchio/itch/issues/1823) by @anissen:

---

Since a recent change, relative paths breaks HTML games.

I have a HTML game with the following script:

```<script type="text/javascript" src="./stoneset.js"></script>```

This _used_ to work. However, now the game fails to load entirely (stuck at the "Loading the game for the first time"-screen).

Changing the line to avoid relative paths like this
```<script type="text/javascript" src="stoneset.js"></script>```
fixes the issue.

**Comment by fasterthanlime** [comment]
@anissen could you upload a version that's broken to a private page so we can investigate it?

Or at least link to the game you're working on that was broken by it

**Comment by anissen** [comment]
Thanks for the quick reply!

> @anissen could you upload a version that's broken to a private page so we can investigate it?

https://anissen.itch.io/html-break-example

*However*, I cannot reproduce it on this new project :/

> Or at least link to the game you're working on that was broken by it. Thanks 🌟

I've downgraded my game to the broken version: https://anissen.itch.io/stoneset

Please let me know when I can revert to a working version!

**Comment by leafo** [comment]
I'm playing the version that's currently there and not experiencing any issues.

**Comment by anissen** [comment]
To days later, it now appears to work again without any changes. How long does the "Loading game for the first time" take?

**Comment by leafo** [comment]
There was a separate issue related to how web games were extracted when uploaded with butler. The issue has been fixed.

**Comment by anissen** [comment]
Great to have it fixed! Thanks a lot for investigating this issue, even if the issue was elsewhere. And, if nothing else, I at least got **leafo** to play my game 😄
