### ISSUE TITLE
How can I put a @if they don't leave me 

### ISSUE THREAD

**Issue by kato-san15** [itchio/itch.io#841]
In https://itch.taxidentity.com/Interview/AX8/en/start_1.aspx
When i try to create my profile, I complete everything right but when I try to put my email address this happen.
![image](https://user-images.githubusercontent.com/39783384/40755672-4902148c-644d-11e8-8627-6ca6bb4db16f.png)
and don't leave me continue, How can i put my email with no @?

**Comment by leafo** [comment]
Hello, it appears you're the same person who posted in this thread: https://itch.io/t/235962/issues-with-tax-interview

I'm going to close this issue in favor of the thread on itch.io.
