### ISSUE TITLE
Tax interview thing does not like my legal name

### ISSUE THREAD

**Issue by windo** [itchio/itch.io#842]
What the title says. The form mysteriously stops working (continue does not proceed) on the individual/corporation choice page. I suspect it does not like my name which sometimes happens on sites.

On Chrome on Android.

**Comment by leafo** [comment]
Is it possible for you to share your name with us so we can submit a bug report to the company that runs the tax interview? If you're unwilling to share it here you can email it to support@itch.io. Include a link to this issue as a reference
