### ISSUE TITLE
macOS sandbox breaks LÖVE 11 games

### ISSUE THREAD

**Issue by fluffy-critter** [itchio/itch.io#844]
I updated two of my games, http://fluffy.itch.io/refactor and http://fluffy.itch.io/cat-catcher, to use LÖVE 11.1. Ever since doing so, the macOS itch.io app cannot launch them; they just start up and immediately segfault.

Other games of mine running LÖVE 0.10.2 still launch just fine, and if I disable itch's sandbox mode 

Presumably this is actually a bug in LÖVE, but I'd like to know if there's something that could be done differently on the itch side, or what actual sandboxing API itch is using so that I can furnish this information to the LÖVE devs.

Thanks!

**Comment by leafo** [comment]
You probably want to post here: https://github.com/itchio/itch/issues

**Comment by fluffy-critter** [comment]
Ah, thanks.
