### ISSUE TITLE
Dead link in payments form

### ISSUE THREAD

**Issue by pshem** [itchio/itch.io#850]
The link in the following form, http://ec.europa.eu/taxation_customs/taxation/vat/how_vat_works/telecom/index_en.htm leads to a 404 error page.
![selectionshot_2018-06-24_19 34 50](https://user-images.githubusercontent.com/26800787/41822319-b50abafc-77e5-11e8-89c9-2341f2623bef.png)

The correct link seems to be one of the following:
- https://europa.eu/youreurope/citizens/consumers/shopping/vat/index_en.htm,
- https://europa.eu/youreurope/business/vat-customs/moss-scheme/index_en.htm,
- https://ec.europa.eu/taxation_customs/business/vat/telecommunications-broadcasting-electronic-services/content/mini-one-stop-shop_en.

**Comment by leafo** [comment]
Thanks, the URL is now fixed.
