### ISSUE TITLE
Require listing of platform support in a standardized way

### ISSUE THREAD

**Issue by yaomtc** [itchio/itch.io#852]
On an itch.io page, whether in "more information" or in Downloads, there should be some text and/or icons indicating which platforms a game supports. Right now it seems to be up to the developer to include that information in the description, and sometimes it's left out.

**Comment by leafo** [comment]
Uploaded files are tagged with the platforms they support, and the union of all of those is the platforms supported by the game. We don't expect developers to manually write in platforms because then it won't get indexed on our browse pages.

**Comment by yaomtc** [comment]
Right, but there's no indication of those tags to the user, is there? At least not when looking at the game's page.

**Comment by leafo** [comment]
It's listed next to the files on the download/purchase area. On pages that link to the game there are platform icons.

**Comment by yaomtc** [comment]
​I just saw this page, where there's no icon:
https://juliansanchez.itch.io/devil-block


Are the icons optional, or do they only show up when there's more than one
download?

​

**Comment by leafo** [comment]
No, this person did not tag their game with a platform. I edited their page. If you come across pages that are missing platform information feel free to open a report from the link on the bottom of the page and we can forward it to the developer

**Comment by yaomtc** [comment]
Okay, thanks!
