### ISSUE TITLE
Urgent Email Admin Approval Required

### ISSUE THREAD

**Issue by sherwoodsoundstudios** [itchio/itch.io#853]
Dear itch.io team,

We're on a tight schedule today and need our Kickstarter distribution email  for _The Coming of the Martians_ approved ASAP please. I wish I knew this was a thing before signing up and uploading files.

Many thanks,
Martin
sherwoodsoundstudios

**Comment by leafo** [comment]
Hello, your account is approved for sending emails. It's hard for us to notify you before you create an account. Did you read about it on our guide? I can make a note there.

Thanks
