### ISSUE TITLE
Jam emails: who are considered "participating"?

### ISSUE THREAD

**Issue by akien-mga** [itchio/itch.io#854]
(Also asked on Twitter [here](https://twitter.com/Akien/status/1009409325922648069), but might be more visible/manageable here).

itch.io jams offer a "Jam email" feature which is described like this:
![screenshot_20180701_095302](https://user-images.githubusercontent.com/4701338/42132246-8ca1cb4e-7d14-11e8-96b8-35eaf5b11693.png)

And the documentation is https://itch.io/docs/creators/game-jams#jam-emails
> Everyone who joins your jam is put on the jam’s mailing list. You can use this to email everyone who’s participating.

What's not clear to me in these descriptions is who exactly will receive jam emails? As it's written it could be:
1. All users who clicked "Join" before the jam started; those may not have actually taken part in the jam eventually
2. All users who joined and then submitted a game to the jam, including potential spam submissions that were removed by jam hosts
3. All users who joined and then submitted a game to the jam, minus those that were removed by jam hosts

It might also be a combination of those based on the current jam period (pre-jam joining, during jam, post-jam reviewing, after jam end).

I'd like to know who I will be writing to exactly as my use case now would be to email (3) (i.e. all participants with a valid game in the jam) with a promotion code for a gamedev book.

**Comment by akien-mga** [comment]
Well I've now started drafting an email and I see that there's an option to select (1), (3) or (1) - (3): 
![screenshot_20180703_144746](https://user-images.githubusercontent.com/4701338/42220711-0dd4a454-7ed0-11e8-8efa-57059ab03294.png)

So feature-wise it's all good already, but it needs to be made clearer in the documentation IMO. I've been wondering about this for 3 weeks before actually trying to send an email and seeing that the option exists.

**Comment by leafo** [comment]
Here's the original feature announcement: <https://itch.io/updates/jam-hosts-can-now-email-participants>

I've updated the docs with some information from that post: https://itch.io/docs/creators/game-jams#jam-emails

Thanks
