### ISSUE TITLE
Cannot set languages in Metadata

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch.io#859]
Hello!

My game has a Simplified Chinese translation. On the Game > Metadata page, I add the translation, like this:

![image](https://user-images.githubusercontent.com/2874150/42637617-939db246-85e3-11e8-8597-e43e39331384.png)

However, when I Save Changes and view the page, this does not appear:

![image](https://user-images.githubusercontent.com/2874150/42637658-a877a41a-85e3-11e8-9e6d-c51e664dad1f.png)

...and when I go back to the Metadata page, the translation has disappeared:

![image](https://user-images.githubusercontent.com/2874150/42637677-b80b04b2-85e3-11e8-82d1-6f435137f420.png)

(Sorry if this is already a known issue!)

**Comment by leafo** [comment]
Not a known but, thanks for reporting. It's fixed now
