### ISSUE TITLE
Can you buy games on itch.io without a USD card?

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch.io#862]
I got this request via email recently:

>Can I pay money for your game with Australian dollars or RMB？ I don't have a USD card :(

I'm not sure what to tell him. Is this possible?

**Comment by fasterthanlime** [comment]
It's definitely possible - you're using the Deferred payment mode, so the vast majority of countries/currencies should have no problem.

The price shows up in US $ on itch.io, but when you get redirected to Paypal, for example, it shows you the total in your own currency.

**Comment by TerryCavanagh** [comment]
Oh, huh! I guess I assumed he tried to do it and it didn't work, but maybe he didn't (or maybe he ran into some other issue). I'll check with him and see what he says.

(On this subject, I'm very interested in where itch.io is on the topic of localised store pages and regional pricing! I've had a few Chinese customers express concern about buying on itch.io because they don't have regional pricing yet. I understand that implementing this stuff is a lot of work and maybe not your highest priority, but though I should pass it along.)

**Comment by leafo** [comment]
Adding new payment processor is a slow process for us since it's a lot of work to implement. We have started talking with someone who will be able to give us many more processors and localized rates but at a higher merchant fee. Not sure when we'll start implementation though.

**Comment by TerryCavanagh** [comment]
This person got in touch to say they were able to buy it after all, so it was probably an issue on their end. Closing this!
