### ISSUE TITLE
many games can't be searched for by title

### ISSUE THREAD

**Issue by gh89275** [itchio/itch.io#863]
Seemingly about half of games can't be searched for by title.

I've manually checked the first 20 in my library (that hadn't [gone missing](https://github.com/itchio/itch.io/issues/858#issuecomment-404714770)) and found nine that can't be searched for:

name / link | archived search | current search
--- | -- | --
[The Legend of The Artifact](https://felixblobdev.itch.io/the-legend-of-the-artifact) | [archived search](http://archive.is/xfYoO) | [current search](https://itch.io/search?q=The+Legend+of+The+Artifact)
[Stellar 2D](https://danvox.itch.io/stellar-2d) | [archived search](http://archive.is/pLkz8) | [current search](https://itch.io/search?q=Stellar+2D)
[The LootCastle](https://stevencolling.itch.io/the-lootcastle) | [archived search](http://archive.is/shRtv) | [current search](https://itch.io/search?q=The+LootCastle)
[At the Mountains of Madness Steam Early Access](https://mountainsgame.itch.io/at-the-mountains-of-madness) | [archived search](http://archive.is/ofHem) | [current search](https://itch.io/search?q=At+the+Mountains+of+Madness+Steam+Early+Access)
[Void Vikings](https://uglybeardgames.itch.io/void-vikings) | [archived search](http://archive.is/jaRYw) | [current search](https://itch.io/search?q=Void+Vikings)
[The Tower Of Elements](https://danvox.itch.io/the-tower-of-elements-) | [archived search](http://archive.is/8SJFd) | [current search](https://itch.io/search?q=The+Tower+Of+Elements)
[New Kind Of Adventure](https://danvox.itch.io/new-kind-of-adventure) | [archived search](http://archive.is/Wvhkw) | [current search](https://itch.io/search?q=New+Kind+Of+Adventure)
[Escape Machines](https://danvox.itch.io/escape-machines) | [archived search](http://archive.is/XY9dc) | [current search](https://itch.io/search?q=Escape+Machines)
[Porradaria 2: Pagode of the Night](https://cleanwatersoft.itch.io/porradaria-2) | [archived search](http://archive.is/n3Gux) | [current search](https://itch.io/search?q=Porradaria+2%3A+Pagode+of+the+Night)

**Comment by leafo** [comment]
If a developer unlists a page or removes access to files on their page then their project will no longer be indexed in search. At the moment our search engine only indexes games that are "available." There must be some files available for purchase or download to show up in search. Additionally, developers can opt out of search if they wish, even if their game is available. Games that are "Restricted" are not indexed in search. Since the search index is global, this applies to projects even if your account owns them.

**Comment by gh89275** [comment]
Fair enough, but The LootCastle is still available for purchase and download so I'm not sure why the dev would opt out of search.

**Comment by leafo** [comment]
The game has been put in restricted mode, so only people who already own the project can access it.
