### ISSUE TITLE
Feature request: Make it possible to leave game jams that have ended

### ISSUE THREAD

**Issue by tobiasvl** [itchio/itch.io#867]
If you change your mind about joining a game jam, you are able to leave the jam again before the jam has ended. However, if you forget about the jam completely, and it ends before you leave it, it will be listed on https://itch.io/jams forever.

It should be possible to leave a game jam after it has ended, or otherwise remove it from your game jams, as long as you haven't submitted a game to the jam.

**Comment by tobiasvl** [comment]
Solved by https://itch.io/t/255557/remove-previous-game-jams-attended

Although I would have preferred it if only jams I didn't submit an entry to were removed from /jams.

**Comment by tobiasvl** [comment]
Nevermind, [the Dashboard already does what I want](https://itch.io/dashboard/jams) (list jams I've submitted to, but not the ones I've joined but not submitted to). So now that past jams are no longer displayed on itch.io/jams I'm happy.

**Comment by SamyBencherif** [comment]
Thanks for posting this. I had the same frustration. So the trick is then to use `https://itch.io/dashboard/jams` instead of `https://itch.io/jams/joined` to see what you want.

**Comment by WillAiChan** [comment]
If this is possible. I still want this Feature could be added. Cause It still bothers me to manage the joined jam.

**Comment by LamentConfiguration** [comment]
Necro-ing this, it's kinda triggering my OCD that I can't remove an ended jam that I didn't participate in.
