### ISSUE TITLE
Forum .topic_author vertical-align issue.

### ISSUE THREAD

**Issue by neauoire** [itchio/itch.io#871]
<img width="1129" alt="screen shot 2018-08-10 at 12 27 22 pm" src="https://user-images.githubusercontent.com/1455726/43932561-eb68d372-9c98-11e8-8f0e-67526595fe18.png">

The `vertical-align:-3px` is vertically offsetting usernames in the community page.
Browser: **Safari**

**Comment by leafo** [comment]
I think this should be fixed now, but I have no way to test. Tell me if it looks good. 

BTW if you have any other design tweaks or suggestions feel free to send them my way.

**Comment by neauoire** [comment]
Fixed! 
Thank you
