### ISSUE TITLE
Content does not show up when editing old devlog post

### ISSUE THREAD

**Issue by bjorn** [itchio/itch.io#873]
I'm unable to edit any of my old devlog posts because the "Post content" field is empty after clicking "Edit post". I was trying to add a missing tag.

I guess this may be related to the recent addition of post types. I did not post any new devlogs yet so I can't test whether the post content does show up for posts made after that feature was added.

**Comment by leafo** [comment]
Ah, sorry missed this ticket. This bug was fixed the day it was introduced, sorry for any trouble!
