### ISSUE TITLE
Bad UX when editing blurb for a game in a collection

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#874]
Originally reported by @tobiasvl on https://github.com/itchio/itch/issues/2037

---

I wrote a blurb for a game that I added to one of my collections.

If I go to the collection and click "Edit blurb", the blurb appears in a textbox, wrapped in a `<p></p>` tag. That's weird. Should I remove them or keep them in?

When I click "Save", I don't get sent back to the collection, but itch dumps the JSON representation of the blurb in my browser.

```{"success":true,"blurb":"<p>Blurb goes here<\/p>"}```

**Comment by leafo** [comment]
Fixed now
