### ISSUE TITLE
Allow cherrypick of Devlog thumbnail

### ISSUE THREAD

**Issue by henriiquecampos** [itchio/itch.io#882]
Hey there, first things first. You're all awesome itch is awesome, I love you guys.

Second things second.

I've been struggling trying to correctly set a thumbnail for my devlogs. As I can see itch.io automatically pick the first image added to the post's **body**.

It would be really, really helpful if we could be able to select one of the images from the **Selected Attachments** section instead. Then, if none is set, it picks the first one that is on the post's body (the current behavior).

What do you think?

**Comment by leafo** [comment]
There's now a "Cover image" field on the devlog post editor. Thanks
