### ISSUE TITLE
When editing collection title, set different text color

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#892]
Originally opened by @darkslategray at https://github.com/itchio/itch/issues/2021

---

1. Making the title of the collection darker while i editing mode inside the _manage collections/my library_ section.
![1](https://user-images.githubusercontent.com/24625611/43353008-e0b7c7de-9203-11e8-9a34-3b8472cfeee2.png)

**Comment by leafo** [comment]
fixed
