### ISSUE TITLE
Project types that don't have genres/platforms still mention them in the context of tags

### ISSUE THREAD

**Issue by tobiasvl** [itchio/itch.io#910]
For project types that don't have platforms or genres (like "Books" – don't books normall have genres, by the way?), the text above the tag text field still says:

> Avoid using the genre or platforms provided above.

This is a very minor issue, but it did make me believe I'd missed some kind of book genre classification system somewhere.

**Comment by leafo** [comment]
Thanks, I changed the text to not mention genre when the genre field is hidden. (BTW Genre is another tag input that's separate to encourage people to pick at least one. Books definitely have genres too, so we could pick a separate list to show up for them for a future update. But in the meantime using tags will accomplish the same end result)
