### ISSUE TITLE
TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by silbinarywolf** [itchio/itch.io#911]
I've uploaded a work-in-progress game I don't want to link here to itch.io that was built using Go 1.11.

I get the following error message in Chrome DevTools:
```
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```

Here's also the related loader code from the Golang repo:
https://github.com/golang/go/blob/master/misc/wasm/wasm_exec.html

I sent a support email as well, but I discovered this issue board so I figured I'd also raise an issue so others could chime in if they were experiencing similar problems!

**Comment by leafo** [comment]
Do you have a itch.io project page you can link to so we can take a closer look.

Thanks

**Comment by silbinarywolf** [comment]
Yup! Just over here;
https://silbinarywolf.itch.io/abworld

FYI, It's a secret URL as I'd rather people not be able to access it publically access it yet :)

**Comment by leafo** [comment]
It looks like the webasm file type isn't an official mime type yet, so I've patched our uploader to manually set the mime type. The existing files you've uploaded are cached so I recommend re-uploading a new build to trigger a new extraction.

**Comment by silbinarywolf** [comment]
I re-uploaded a new build and now I'm getting 403 forbidden error. I've put some information below for you and I hope it helps makes things a bit easier.

Thanks for being so quick!

**Console:**
```
VM48:1 GET https://v6p9d9t4.ssl.hwcdn.net/html/945649-107866/abgame-go.wasm?v=2 403
index.html:1 Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

**Response:**
```xml
<?xml version='1.0' encoding='UTF-8'?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied.</Message>
  <Details>Anonymous caller does not have storage.objects.get access to itchio/html/945649-107866/abgame-go.wasm.</Details>
</Error>
```

**Screenshot of Headers/Request:**
File: https://v6p9d9t4.ssl.hwcdn.net/html/945649-107866/abgame-go.wasm?v=2
![image](https://user-images.githubusercontent.com/3859574/46240884-87f03080-c3f1-11e8-91e8-7e7e2d1d076f.png)

**Screenshot of console**
![image](https://user-images.githubusercontent.com/3859574/46240894-ae15d080-c3f1-11e8-9794-c2841de5f5a9.png)

**Comment by silbinarywolf** [comment]
Sorry, I'm incorrect. I was linking to a file that didn't exist and had a typo.

Apologies! I hope I didn't waste your time.
Thanks again for your fast response!

**Comment by leafo** [comment]
Glad you figured it out. For future reference and anyone else that ends up here: 403 errors on our storage bucket are effectively 404 errors. It returns 403 since files that don't exist don't have permissions set. So if you see 403 error it's most likely because you're referencing a path incorrectly.
