### ISSUE TITLE
Installing Error on Windows

### ISSUE THREAD

**Issue by Damvit** [itchio/itch.io#916]
Hello,this is what shows me when I try to install the      #####app

Something went wrong

itch-setup, v1.11.0, built on Sep 12 2018 @ 09:57:02, ref a5e3b45488f415d4799bdfcf8891cf9553aa8a7d

open C:\Users\Hp\AppData\Local\itch\staging\app-25.2.0\api-ms-win-core-console-l1-1-0.dll: Accesso negato.
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:274
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1665
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1665
while installing
Error during warm-up

**Comment by fasterthanlime** [comment]
What Antivirus are you using?

**Comment by Damvit** [comment]
I'm using 
-360 total security
-malwarebyte
-

**Comment by Damvit** [comment]
and superantyspyware free edition

**Comment by fasterthanlime** [comment]
That's definitely it :) Try to find out which Antivirus is preventing the itch app from installing itself, and follow the instructions in the "Antivirus" section here: https://itch.io/docs/itch/installing/windows.html
