### ISSUE TITLE
Block form submission on Chrome 

### ISSUE THREAD

**Issue by CaptEmulation** [itchio/itch.io#923]
When I try to search, like or comment on a dev log or community forum I get an  error in Chrome devtools:

```
Blocked form submission to 'https://itch.io/blog-post/51668/like' because the form's frame is sandboxed and the 'allow-forms' permission is not set.
```

The URL will be the POST URL.  Chrome seems to be rejecting these POSTs.  I had to switch to IE to use Itch.IO :-(

**Comment by fasterthanlime** [comment]
> because the form's frame is sandboxed and the 'allow-forms' permission is not set.

Huh that's a surprising message - none of the community pages on itch.io involve iframes at all..

What browser extensions do you have installed?

**Comment by CaptEmulation** [comment]
Problem was on my end, thanks.  Sorry I missed your otherwise prompt reply :-(

**Comment by fasterthanlime** [comment]
@CaptEmulation no probs, thanks for the update!
