### ISSUE TITLE
Project hydra 0.41 will not let me leave!

### ISSUE THREAD

**Issue by JRMlover** [itchio/itch.io#925]
Hello I have a problem with the game: Project Hydra. I cannot close the tab and it keeps me on the space where the window is up. Help

**Comment by leafo** [comment]
Hello, itch.io is a platform that hosts over 100 thousand games. We don't provide support for the individual projects on the site. You'll have to reach out to the project creator if you need help. You can often find a way to contact them via their project page. Thanks
