### ISSUE TITLE
Installing tar.gz

### ISSUE THREAD

**Issue by SebastianPfliegel** [itchio/itch.io#928]
Not sure whether this is an issue with the publisher/developer of the game I purchased or it's a potential feature request. I bought Broken Age for Linux. Version 3 and Version 2 are simply provided as tarball instead of single files (Version 1 comes with all the files). As it's only a tarball the itch app can't launch the game. Is this something the publisher should take care off or should the itch app be able to work with?

**Comment by fasterthanlime** [comment]
It's.. an unfortunate combination of circumstances. (see https://github.com/itchio/butler/issues/47 and https://github.com/itchio/butler/issues/48 )

But yes, the publisher should upload just the files, not a .tar.gz. I'll get in touch with them.

**Comment by fasterthanlime** [comment]
Update: for now, I've reuploaded the contents of the .tar on the linux channel, so you should be able to play it right now @SebastianPfliegel

**Comment by SebastianPfliegel** [comment]
Thank you @fasterthanlime for the quick reply and solution :)
