### ISSUE TITLE
Typo in browse filters

### ISSUE THREAD

**Issue by TwinkieCamel** [itchio/itch.io#932]
Typo found at: https://itch.io/games below the "When" filter: "Lasy Day"

![ytpo](https://user-images.githubusercontent.com/45082560/48587222-5deec100-e900-11e8-9a97-1341644bb7e3.PNG)

(I know the image probably isn't necessary; I just want to be as clear as possible)

**Comment by leafo** [comment]
Thanks, it's fixed now.
