### ISSUE TITLE
Itch Hosted HTML5 Games forced into landscape mode (only on Itch Hosting)

### ISSUE THREAD

**Issue by ainslec** [itchio/itch.io#936]
I am released a game called "The Beast of Torrack Moor" which is a text adventure game. I am also the author of the (text adventure) game engine on which it sits. The game is contained in a single HTML file, uploaded as "index.html", running on the Adventuron Text Adventure game engine. 

When not hosted on Itch, the standalone Beast game scales properly on mobile when in portrait orientation (it was designed to be mobile friendly but the player is free to switch between landscape and portait modes naturally, by turning their phones. You know - normal behaviour.

The problem when I host this game on Itch is that when the player clicks "Run Game" the game automatically switches to landscape orientation, even when the phone is being held in portrait mode, turning the phones physical orientation doesn't seem to matter. This makes the game UI unplayable, not least because landscape software keyboard is really difficult to use.

Some screenshots to illustrate the rendering issue:

**The Itch Wrapper Force-Landscape Bug (forced to landscape orientation via the Itch wrapper):**

(Note: the player sees this when holding the game in portrait orientation, which is absolutely not the behavior without the Itch wrapper)

![screenshot_20181217-222457a](https://user-images.githubusercontent.com/201870/50120272-eb4d6a00-024c-11e9-8bb8-52b18785da71.png)

**How it should render (same index.html hosted on my own web server):**

![screenshot_20181217-222647](https://user-images.githubusercontent.com/201870/50119538-f4d5d280-024a-11e9-968a-119226b79d93.png)

**Suggestion**

Make it so that Itch can let the game developer switch off orientation hardcoding to landscape. Or if not switch it off, so that we can toggle it to landscape or portrait.

**Admin settings for this game (on Itch):**

![image](https://user-images.githubusercontent.com/201870/50119029-6876e000-0249-11e9-9de9-87ee8b6de30b.png)

**Comment by ainslec** [comment]
Another example of this bug (but in the form of a full game):

https://adventuron.itch.io/thebeast

**Comment by leafo** [comment]
Hey, sorry I didn't get a chance to address this sooner. I've just deployed an update that will allow you to select an orientation when enabling "mobile friendly." Please give it a shot and tell me if you have any issues.

**Comment by ainslec** [comment]
Thank you so very much. The game is working perfectly now (as far as the platform is concerned).
