### ISSUE TITLE
Cannot scroll down on "My rated games"

### ISSUE THREAD

**Issue by seleb** [itchio/itch.io#937]
When viewing the auto-generated collection "My rated games" (https://itch.io/my-collections/rated), only the first page ever loads. The bottom of the page shows the "Loading more games..." spinner, but it never resolves.

It doesn't seem to be making a network request that looks like paging, and an error (`Uncaught TypeError: I.MyRatedGames is not a constructor`) is being thrown on page load which is pretty likely related.

**Comment by leafo** [comment]
Thanks for the report, it's fixed now
