### ISSUE TITLE
"Scan Install Locations For Games" Not Working

### ISSUE THREAD

**Issue by SentryOverwatch** [itchio/itch.io#940]
When I updated the itch.io app all of my installed games were "removed" from my library. They're still on my computer, and when I click the "search  locations for installed games" some of them are accounte for (17 it sayed) which it then added those to my library. The problem is that I have about 41 games installed, and only those 17 are accounted for, which is strange. Any idea why this is, and any solutions?
~Thanks,
           Sentry
![bunchagames](https://user-images.githubusercontent.com/46277672/50557302-fde68b00-0cb1-11e9-80cc-d178378fa3f3.jpg)

**Comment by fasterthanlime** [comment]
Hey there, I'd like you to click "Scan install locations" once more and then attach the file at `%APPDATA%/itch/logs/itch.txt`

Typically games that don't get imported have either had their pages deleted, or the upload that was installed has been deleted (and replaced with a new one).

**Comment by SentryOverwatch** [comment]
> Hey there, I'd like you to click "Scan install locations" once more and then attach the file at `%APPDATA%/itch/logs/itch.txt`
> 
> Typically games that don't get imported have either had their pages deleted, or the upload that was installed has been deleted (and replaced with a new one).

Ok so there are multiple files but i did the one that i think you mean? (although i'm not entirely sure...)
[itch.txt](https://github.com/itchio/itch.io/files/2719060/itch.txt)

**Comment by fasterthanlime** [comment]
Thanks! That's the correct file.

As I suspected, the remaining games either:

  * Were installed with a much older version of itch originally (older than v23, or with a setup program like InnoSetup etc.)
  * Deleted the upload that was installed (probably replacing it with a newer one)

All these won't get imported:

![image](https://user-images.githubusercontent.com/7998310/50638915-b6852680-0f5f-11e9-8d86-ae66a68514ac.png)

You might want to remove those folders, then install them from itch v25 - if they have save data in `%APPDATA%`, then normally you shouldn't lose any progress (but make backups, better safe than sorry!)

I apologize for the mess, supporting a large number of install methods got a little messy up until v23, I didn't figure out a "clean way" to handle everything until v25. A migration like that shouldn't happen again!
