### ISSUE TITLE
[Feature request] Add a theme-color meta

### ISSUE THREAD

**Issue by YellowAfterlife** [itchio/itch.io#950]
With a growing number of websites and services using `theme-color` meta to show an accent color on embeds or tabs, it might make sense to include one on itch pages, like so
```
<meta property="theme-color" content="#FA5C5C" />
```
Example of how Discord shows accents:
![image](https://user-images.githubusercontent.com/731492/51531481-3bb87880-1e46-11e9-81fa-c2366854e5c3.png)
Edit: Correction - the meta tag is present on main itch pages, but not user/project pages

**Comment by leafo** [comment]
I added it to project pages, using the BG color property. Tell me how it works out.
