### ISSUE TITLE
Sortable "Project totals" games list at Dashboard/Analytics

### ISSUE THREAD

**Issue by rubna** [itchio/itch.io#958]
Would be nice to be able to sort your creations per views/downloads/payments etc. at the "Project totals" section of the dashboard/analytics page. 

![itch recommendation](https://user-images.githubusercontent.com/15164273/52534329-8d1aa000-2d40-11e9-8b50-b9069f0fa977.png)

**Comment by leafo** [comment]
this was added a while ago! woop
