### ISSUE TITLE
Ability to change public account URL. 

### ISSUE THREAD

**Issue by DaemonLee** [itchio/itch.io#96]
Currently, as far as I can tell, I can't change the public URLs for accounts. At the time of creation of my developer account I wasn't aware that it would convert spaces to dashes when I was adding my username. And I'd prefer to not abandon my developer email and create a whole new account... 

Thanks in advance.

**Comment by leafo** [comment]
In the meantime, send a support ticket from the email that controls the account and I'd be glad to update your account name/URL http://itch.io/about/support

**Comment by fasterthanlime** [comment]
Looks like you're [all set](https://github.com/BrassPipeDreams/BrassPipeDreams.github.io/commit/41a338592e4a29b04777e0b6c3ed741c15e32b57)

:shipit: Closing!

**Comment by leafo** [comment]
It would be nice to make a feature in the user settings page to change your URL.

There are a couple implications about this. Any old URLs floating around would break unless we leave a redirect. We could leave a redirect but then should the redirect prevent anyone else from registering with that URL? I don't think so. I'm fine with not having a redirect but just putting a warning on the field when you go to change it.

**Comment by DaemonLee** [comment]
Well, thank you again! That had me really worried. And if my input means anything... I would prefer the idea of just having a warning as well.

**Comment by fasterthanlime** [comment]
> It would be nice...

I read that comment as if written by DaemonLee so was gonna ask leafo for his opinion, but since it's official, I can add that to my TODO list!

> I would prefer the idea of just having a warning as well, because of mistakes such as this.

When signing up? I can definitely cook up some slug preview, like we have in the edit game page.

**Comment by leafo** [comment]
Ah, yup, thanks for the reminder. Also meant to add some sort of a preview of your URL when signing up, and possibly a way to customize the URL at that time as well

**Comment by kujovic** [comment]
Guys, any updates on this? I would also prefer not having a redirect but just putting a warning on the field when you go to change your public URL. Something like this:

*Warning! After changing your public URL, any references to your current URL will not redirect to your new one and your current URL will become available for someone else to use.*

> When signing up?

I don't think the warning would be necessary on the sign up page if it would be easily changeable in the settings. Same goes for the URL preview/customize on the sign up page.

> I can definitely cook up some slug preview, like we have in the edit game page.

Please do! :)

**Comment by fasterthanlime** [comment]
> > I can definitely cook up some slug preview, like we have in the edit game page.
> Please do! :)

We did that one a while ago :)

<img width="463" alt="screen shot 2015-09-22 at 20 02 11" src="https://cloud.githubusercontent.com/assets/7998310/10026978/deadbbec-6164-11e5-9afb-562719ac4a68.png">

**Comment by kujovic** [comment]
That's great! But I was talking about the option to change your username/URL. If you follow my quote of your quote of DaemonLee's quote, I thought he was referring to leafo's idea about having the warning when changing your username and not this which you already implemented, but maybe I'm wrong :)

**Comment by s-ol** [comment]
It's implemented with a redirect, so I guess this could get closed?

**Comment by leafo** [comment]
Yup, we have automatic redirects now.
