### ISSUE TITLE
"This file will be played in browser" setting checks itself

### ISSUE THREAD

**Issue by wickworks** [itchio/itch.io#962]
I normally host the HTML5 version of my game through the embed system, but last week I temporarily needed to have it playable its itch page, so I checked "this game will be played in browser" for the html file.

However, now when I uncheck that, save, and look at my page, I get a "Failed to find index.html" error. Going back to the edit game page, the first file in the list (a downloadable .exe) has the played-in-browser setting checked. Unchecking that setting and saving has no effect; it re-checks itself.

It is possible to check the played-in-browser setting for my html5 file and have it show up instead of the error, but I would like to have no playable file on the itch page.

Thank you!

**Comment by leafo** [comment]
You have your project type set to HTML and since you're saving the page with nothing selected it's trying to use the first ZIP file. Change the project type back to downloadable and it won't do this anymore. I agree this is confusing, thanks for the report.

**Comment by wickworks** [comment]
D'oh, that fixed it. Thanks again!
