### ISSUE TITLE
Unsolveable Captcha

### ISSUE THREAD

**Issue by LWFlouisa** [itchio/itch.io#963]
Issue solved. But it's not necessary to have to completely reset my password, just to be able to log in on different laptops.

**Comment by LWFlouisa** [comment]
Solved.

**Comment by leafo** [comment]
If you enable 2fa on your account then there will never be a captcha when attempting to log into it. CAPTCHA is used as protection on all itch.io accounts to prevent people from using password database dumps to hijack accounts. I know it sucks, but security benefit it provides outweighs the annoyance.

https://itch.io/docs/advanced/two-factor-authentication
