### ISSUE TITLE
'Screenshots: Hidden' dropdown option not working on mobile layout

### ISSUE THREAD

**Issue by ArmelGibson** [itchio/itch.io#965]
As the title says, if you select 'hidden' under Layout > Screenshots on the 'Edit theme' interface, the screenshots are hidden on desktop, but not on mobile. This is especially problematic when using custom css to fancy up a page. 

Cheers!

**Comment by leafo** [comment]
So it's intentional how it works right now, to ensure a consistent mobile experience. If you're doing custom CSS and also checking mobile looks good then I recommend hiding the element yourself. Tell me if you have any issues.

**Comment by ArmelGibson** [comment]
Sorry for the late reply, this this what I ended up doing, which wasn't very hard indeed: 
`.right_col
{
    display: none !important;
}`

Thanks for the help!
