### ISSUE TITLE
Images seem to be down on the website.

### ISSUE THREAD

**Issue by kicknbrit** [itchio/itch.io#976]
The last few days images seem to not be loading for me. 

I picked a random image from a pages source, a random image from an asset page and tried to go to both and it wouldn't let me for either of them.. 

https://img.itch.zone/aW1hZ2UvMjU0MTE0LzEyMjA4NDkucG5n/347x500/VUFRph.png

https://img.itch.zone/aW1hZ2UvMjU0MTE0LzEyMjA4NTIuZ2lm/original/iJfNI%2F.gif

Is anyone else having this problem?

**Comment by fasterthanlime** [comment]
Images load fine here (France). What's your country & browser?

**Comment by leafo** [comment]
We haven't gotten any other reports as far as I'm aware.

**Comment by kicknbrit** [comment]
Hey. Sorry for the late reply. They finnally started working today idk why. D:
Im from the US and I use google chrome. 
Thanks. Sorry for the useless thread lol
