### ISSUE TITLE
[legal issue] Copyright and license violation

### ISSUE THREAD

**Issue by 4144** [itchio/itch.io#978]
Hello,
I am author of the mana world game client named manaplus (http://manaplus.org/)

On your site at url https://deltazero.itch.io/manabreak present renamed manaplus binaries without any copyrights. Also in game archive missing license and authors files.
Original license is GPL 2.

Links to original manaplus sources: https://gitlab.com/manaplus/manaplus/ and https://github.com/manaplus/manaplus

https://deltazero.itch.io/manabreak is completly stolen game. Man who posted it on this site not have any relation to manaplus or to The Mana World. He not included license in distribution and not include any original authors.
Game with same violations was posted also on site https://gamejolt.com/ (issue on github https://github.com/gamejolt/issue-tracker/issues/1265)

Please remove this game from your site.

**Comment by Proto-ai** [comment]
taken down

**Comment by 4144** [comment]
thanks

**Comment by Proto-ai** [comment]
can both issues be closed

**Comment by fasterthanlime** [comment]
Hi,

It looks like the page has been switched to "restricted" visibility - this was not an admin action.

For copyright claims, DMCA notices should be sent to https://itch.io/support, not GitHub issues.

**Comment by Proto-ai** [comment]
sorry lmao here ill remove it

**Comment by 4144** [comment]
@fasterthanlime i sent same request by report form. Need do same with support form?

**Comment by leafo** [comment]
@4144 the report functionality is fine as well, thanks
