### ISSUE TITLE
API to return game/store information based on game ID?

### ISSUE THREAD

**Issue by alexguichet** [itchio/itch.io#992]
Howdy! 

I'm building itch support into my CMS, for my project https://www.themissingquests.com. 

I want to be able to hit a search or game API endpoint, get some (live) information, and cache the result for ~24 hours.

I see that some sort of support like this exists, based on the `https://itch.io/api/1/me/search/games` endpoint documented at: 
https://github.com/itchio/itch.io/issues/289 (which returns everything I really care about). However, this just takes an arbitrary game name, but I'd really prefer to be able to pass a canonical ID (which I'm capable of fetching myself, thus far) *or* a game and a game author, which will give me a higher likelihood of getting safer results. My current fallback, the `https://$author.itch.io/$game/data.json` endpoint, doesn't return enough information for my taste.

My end goal is to build it into some sort of enhanced link that looks like screenshot below, (which will ultimately adapt to whatever game I'm posting about.
![Screen Shot 2019-05-18 at 11 46 15 PM](https://user-images.githubusercontent.com/1219315/57978711-23f19b00-79c7-11e9-8a43-96d7336162d3.png)

Any ideas/help/etc?

**Comment by fasterthanlime** [comment]
There it is! https://api.itch.io/games/415790

This link should work for you in the browser, if you're logged in - for API usage, you'll need an API key (see User settings). You can pass it with the `Authorization` header.

**Comment by alexguichet** [comment]
Ayy, perfect, and it returns what I'm looking for. I was hoping something like this already existed but didn't see anything while trawling the documentation. Thank you!
