### ISSUE TITLE
Content warning page shows message with missing spacing

### ISSUE THREAD

**Issue by salty-horse** [itchio/itch.io#995]
If am logged in and visit a page with a content warning, this message appears:

"Remember my setting for accountUSERNAME"

The USERNAME appears adjacent to the word "account" on Chrome and Firefox. There should be some spacing.

![screenshot](https://user-images.githubusercontent.com/28355/58559911-bf3b0980-822c-11e9-89f5-aa760c5a772f.png)

The HTML is:
```html
<label class="check_row"><input name="remember" type="checkbox"/>Remember my setting for account <em>USERNAME</em></label>
```

**Comment by leafo** [comment]
Thanks for the report. It's fixed for next deploy
