### ISSUE TITLE
I am unable to Submit my games in Jams

### ISSUE THREAD

**Issue by ManixTorres** [itchio/itch.io#999]
I have been unable to submit my projects to Game jams for nearly two weeks now. I've contacted Itch.io support, but they haven't replied in days? Please help me.

**Comment by fasterthanlime** [comment]
Yep, seems like you've been abusing the jam system, everything checks out here:

![image](https://user-images.githubusercontent.com/7998310/58764005-92576100-8562-11e9-9235-0becf0ccefc9.png)
